// Trophées : [id, catégorie, nom, description, condition, bonus XP, titre honorifique?, secret?, indice?]
const A = ['FOR', 'DEX', 'CON', 'INT', 'SAG', 'CHA'];
const LABEL = { FOR: 'Courage', DEX: 'Créativité', CON: 'Vitalité', INT: 'Savoir', SAG: 'Équilibre', CHA: 'Liens' };

const rows = [
  // ── Constance (21)
  ['premier-pas', 'constance', 'Le Premier Pas', 'Accomplir ta première quête.', { kind: 'quests_total', target: 1 }, 25, null],
  ['premier-elan', 'constance', 'Premier élan', 'Accomplir 10 quêtes.', { kind: 'quests_total', target: 10 }, 50, null],
  ['cinquante-pas', 'constance', 'Cinquante pas', 'Accomplir 50 quêtes.', { kind: 'quests_total', target: 50 }, 100, 'Marcheur fidèle'],
  ['centurion', 'constance', 'Le Centurion', 'Accomplir 100 quêtes.', { kind: 'quests_total', target: 100 }, 150, 'Centurion'],
  ['deux-cent-cinquante', 'constance', 'Chemin parcouru', 'Accomplir 250 quêtes.', { kind: 'quests_total', target: 250 }, 250, null],
  ['cinq-cents', 'constance', 'Les Cinq Cents', 'Accomplir 500 quêtes.', { kind: 'quests_total', target: 500 }, 400, 'Infatigable'],
  ['mille-quetes', 'constance', 'Le Millénaire', 'Accomplir 1 000 quêtes.', { kind: 'quests_total', target: 1000 }, 500, 'Légende des mille quêtes'],
  ['serie-3', 'constance', 'Trois d’affilée', 'Tenir une série de 3 jours.', { kind: 'streak_best', target: 3 }, 25, null],
  ['feu-sacre', 'constance', 'Feu sacré', 'Tenir une série de 7 jours.', { kind: 'streak_best', target: 7 }, 50, 'Gardien du feu'],
  ['serie-14', 'constance', 'Deux semaines de flamme', 'Tenir une série de 14 jours.', { kind: 'streak_best', target: 14 }, 100, null],
  ['serie-30', 'constance', 'Un mois sans faillir', 'Tenir une série de 30 jours.', { kind: 'streak_best', target: 30 }, 200, 'Le Constant'],
  ['serie-60', 'constance', 'Deux lunes', 'Tenir une série de 60 jours.', { kind: 'streak_best', target: 60 }, 300, null],
  ['increvable', 'constance', 'Increvable', 'Tenir une série de 100 jours.', { kind: 'streak_best', target: 100 }, 500, 'L’Increvable'],
  ['serie-200', 'constance', 'Roc dans la tempête', 'Tenir une série de 200 jours.', { kind: 'streak_best', target: 200 }, 500, null],
  ['annee-heros', 'constance', 'L’Année du Héros', 'Tenir une série de 365 jours.', { kind: 'streak_best', target: 365 }, 500, 'Héros de l’année'],
  ['journee-parfaite', 'constance', 'Journée accomplie', 'Accomplir toutes tes quêtes du jour.', { kind: 'perfect_days', target: 1 }, 25, null],
  ['sept-journees-parfaites', 'constance', 'Sept journées parfaites', 'Accomplir toutes tes quêtes du jour 7 fois.', { kind: 'perfect_days', target: 7 }, 100, null],
  ['trente-journees-parfaites', 'constance', 'Trente journées parfaites', 'Accomplir toutes tes quêtes du jour 30 fois.', { kind: 'perfect_days', target: 30 }, 250, 'L’Exemplaire'],
  ['lieve-tot', 'constance', 'Le Lève-tôt', 'Valider 10 quêtes avant 8 h.', { kind: 'early_quests', target: 10 }, 100, 'Le Lève-tôt'],
  ['chouette', 'constance', 'La Chouette', 'Valider 10 quêtes après 21 h.', { kind: 'late_quests', target: 10 }, 75, 'La Chouette'],
  ['repos-du-sage', 'constance', 'Le Repos du Sage', 'Déclarer un premier jour de repos.', { kind: 'rest_days', target: 1 }, 25, null],
  // ── Maîtrise (24)
  ...A.flatMap((a) => [
    [`${a.toLowerCase()}-14`, 'maitrise', `${LABEL[a]} aguerri`, `Atteindre un score de ${LABEL[a]} de 14.`, { kind: 'ability_score', ability: a, target: 14 }, 75, null],
    [`${a.toLowerCase()}-18`, 'maitrise', `${LABEL[a]} remarquable`, `Atteindre un score de ${LABEL[a]} de 18.`, { kind: 'ability_score', ability: a, target: 18 }, 200, null],
  ]),
  ['niveau-5', 'maitrise', 'Héros du royaume', 'Atteindre le niveau 5.', { kind: 'level', target: 5 }, 100, 'Héros du royaume'],
  ['niveau-10', 'maitrise', 'Dix niveaux de patience', 'Atteindre le niveau 10.', { kind: 'level', target: 10 }, 200, null],
  ['niveau-11', 'maitrise', 'Maître du royaume', 'Atteindre le niveau 11.', { kind: 'level', target: 11 }, 250, 'Maître du royaume'],
  ['niveau-15', 'maitrise', 'Quinze niveaux', 'Atteindre le niveau 15.', { kind: 'level', target: 15 }, 300, null],
  ['niveau-17', 'maitrise', 'Légende vivante', 'Atteindre le niveau 17.', { kind: 'level', target: 17 }, 400, 'La Légende'],
  ['niveau-20', 'maitrise', 'La Fiche dorée', 'Atteindre le niveau 20.', { kind: 'level', target: 20 }, 500, 'Légende des Légendes'],
  ['rang-legendaire', 'maitrise', 'Au-delà du plafond', 'Faire passer une caractéristique au rang légendaire (score 21).', { kind: 'legendary_abilities', target: 1 }, 500, 'Au-delà des limites'],
  // ── Exploration (16)
  ['decouvreur-10', 'exploration', 'Premiers horizons', 'Accomplir 10 quêtes différentes.', { kind: 'discovered', target: 10 }, 50, null],
  ['decouvreur-50', 'exploration', 'Explorateur du Grimoire', 'Accomplir 50 quêtes différentes.', { kind: 'discovered', target: 50 }, 150, 'Curieux'],
  ['decouvreur-100', 'exploration', 'Cartographe', 'Accomplir 100 quêtes différentes.', { kind: 'discovered', target: 100 }, 250, null],
  ['decouvreur-200', 'exploration', 'Le Grimoire complet', 'Accomplir 200 quêtes différentes.', { kind: 'discovered', target: 200 }, 500, 'Bibliothécaire du royaume'],
  ['premier-journal', 'exploration', 'Première page', 'Valider une quête Journal.', { kind: 'journal_entries', target: 1 }, 25, null],
  ['journal-10', 'exploration', 'Le Carnet se remplit', 'Écrire 10 entrées de journal.', { kind: 'journal_entries', target: 10 }, 100, null],
  ['journal-50', 'exploration', 'Chroniqueur du royaume', 'Écrire 50 entrées de journal.', { kind: 'journal_entries', target: 50 }, 250, 'Chroniqueur'],
  ['forgeron', 'exploration', 'Premier coup de marteau', 'Forger ta première quête personnalisée.', { kind: 'custom_quests', target: 1 }, 50, null],
  ['maitre-forgeron', 'exploration', 'Maître forgeron', 'Forger 5 quêtes personnalisées.', { kind: 'custom_quests', target: 5 }, 150, 'Maître forgeron'],
  ['premiere-publication', 'exploration', 'La Plume du Crieur', 'Publier ta première victoire au Village.', { kind: 'posts_shared', target: 1 }, 25, null],
  ['dix-publications', 'exploration', 'Voix du Village', 'Publier 10 victoires au Village.', { kind: 'posts_shared', target: 10 }, 100, null],
  ['cinquante-publications', 'exploration', 'Barde du Village', 'Publier 50 victoires au Village.', { kind: 'posts_shared', target: 50 }, 250, 'Barde du Village'],
  ['premier-compagnon', 'exploration', 'Une main tendue', 'Ajouter ton premier compagnon.', { kind: 'friends', target: 1 }, 50, null],
  ['cinq-compagnons', 'exploration', 'La Compagnie', 'Avoir 5 compagnons.', { kind: 'friends', target: 5 }, 100, null],
  ['vingt-compagnons', 'exploration', 'La Grande Compagnie', 'Avoir 20 compagnons.', { kind: 'friends', target: 20 }, 250, 'Rassembleur'],
  ['encourageur', 'exploration', 'Le Mot Gentil', 'Encourager 100 publications de tes compagnons.', { kind: 'reactions_given', target: 100 }, 150, 'Le Bienveillant'],
  // ── Exploits (11)
  ['tueur-de-dragons-1', 'exploits', 'Premier Dragon', 'Accomplir une quête Légendaire.', { kind: 'quests_by_difficulty', difficulty: 'expert', target: 1 }, 100, null],
  ['tueur-de-dragons-5', 'exploits', 'Chasseur de dragons', 'Accomplir 5 quêtes Légendaires.', { kind: 'quests_by_difficulty', difficulty: 'expert', target: 5 }, 250, null],
  ['tueur-de-dragons', 'exploits', 'Tueur de Dragons', 'Accomplir 10 quêtes Légendaires.', { kind: 'quests_by_difficulty', difficulty: 'expert', target: 10 }, 400, 'Tueur de Dragons'],
  ['tueur-de-dragons-25', 'exploits', 'Fléau des dragons', 'Accomplir 25 quêtes Légendaires.', { kind: 'quests_by_difficulty', difficulty: 'expert', target: 25 }, 500, null],
  ['audacieux-10', 'exploits', 'Audacieux', 'Accomplir 10 quêtes Audacieuses.', { kind: 'quests_by_difficulty', difficulty: 'high', target: 10 }, 100, null],
  ['audacieux-50', 'exploits', 'Le Téméraire', 'Accomplir 50 quêtes Audacieuses.', { kind: 'quests_by_difficulty', difficulty: 'high', target: 50 }, 300, 'Le Téméraire'],
  ['semainier', 'exploits', 'Maître de la semaine', 'Accomplir 10 quêtes hebdomadaires.', { kind: 'weekly_done', target: 10 }, 150, null],
  ['moissonneur', 'exploits', 'Le Moissonneur', 'Accomplir 6 quêtes mensuelles.', { kind: 'monthly_done', target: 6 }, 250, null],
  ['dix-heures-silence', 'exploits', 'Dix heures de silence', 'Cumuler 10 heures sur le chronomètre intégré.', { kind: 'timer_minutes', target: 600 }, 150, null],
  ['cinquante-heures', 'exploits', 'Cinquante heures de présence', 'Cumuler 50 heures sur le chronomètre intégré.', { kind: 'timer_minutes', target: 3000 }, 400, 'Le Patient'],
  ['inspire-1', 'exploits', 'Première étincelle', 'Utiliser un point d’Inspiration.', { kind: 'inspiration_used', target: 1 }, 25, null],
  ['inspire-10', 'exploits', 'Étincelle', 'Utiliser 10 points d’Inspiration.', { kind: 'inspiration_used', target: 10 }, 150, null],
  // ── Équilibre (6)
  ['equilibre-10', 'equilibre', 'Fondations', 'Avoir toutes les caractéristiques à 10 ou plus.', { kind: 'all_scores_min', target: 10 }, 75, null],
  ['equilibre-12', 'equilibre', 'Bien campé', 'Avoir toutes les caractéristiques à 12 ou plus.', { kind: 'all_scores_min', target: 12 }, 150, null],
  ['polymathe', 'equilibre', 'Polymathe', 'Avoir toutes les caractéristiques à 14 ou plus.', { kind: 'all_scores_min', target: 14 }, 300, 'Polymathe'],
  ['equilibre-16', 'equilibre', 'Héros complet', 'Avoir toutes les caractéristiques à 16 ou plus.', { kind: 'all_scores_min', target: 16 }, 400, null],
  ['six-couleurs', 'equilibre', 'Les Six Couleurs', 'Accomplir une quête dans chacune des six caractéristiques au cours d’une même semaine.', { kind: 'week_all_abilities', target: 6 }, 150, 'Arc-en-ciel'],
  ['equilibre-20', 'equilibre', 'La Perfection tranquille', 'Avoir toutes les caractéristiques à 20.', { kind: 'all_scores_min', target: 20 }, 500, 'Perfection tranquille'],
  // ── Secrets (6)
  ['retour-du-roi', 'secrets', 'Le Retour du Roi', 'Reprendre après 14 jours d’absence.', { kind: 'comeback', target: 14 }, 100, 'Le Revenant', true, 'Les rois partent parfois. Les grands reviennent.'],
  ['retour-30', 'secrets', 'Le Long Exil', 'Reprendre après 30 jours d’absence.', { kind: 'comeback', target: 30 }, 150, null, true, 'Il n’est jamais trop tard.'],
  ['dix-mille-xp', 'secrets', 'Dix mille voix', 'Gagner 10 000 XP au total.', { kind: 'total_xp', target: 10000 }, 200, null, true, 'Les chiffres ronds portent chance.'],
  ['cinquante-mille-xp', 'secrets', 'Un royaume d’XP', 'Gagner 50 000 XP au total.', { kind: 'total_xp', target: 50000 }, 400, null, true, 'Peu de héros vont jusque-là.'],
  ['repos-10', 'secrets', 'Le Sage Patient', 'Déclarer 10 jours de repos.', { kind: 'rest_days', target: 10 }, 100, 'Le Sage Patient', true, 'Savoir s’arrêter est aussi une force.'],
  ['inspire-30', 'secrets', 'Cœur d’étincelles', 'Utiliser 30 points d’Inspiration.', { kind: 'inspiration_used', target: 30 }, 250, null, true, 'Une étincelle a grandi.'],
];

export default rows;
