// Tâches précises des quêtes guidées, une ligne par activité (clé : nom de l’activité dans guided.mjs).
// [titre du jour, objectif du jour, validation du jour, titre de la semaine, objectif de la semaine, validation de la semaine, unité (mois et épique)]
// validation : s | c:cible:unité | t:minutes | e:étape1|étape2 | j
// Le mois et l’épique comptent des « unités » (cours, séances, sorties…) : leur nombre vient du rythme de la discipline.
const lang = (nom, article) => [
  `${nom}, un cours aujourd’hui`,
  `Suivre un cours ${article}${nom.toLowerCase()} aujourd’hui (application, vidéo ou professeur), avec les exercices.`,
  's',
  `${nom}, un texte lu à voix haute`,
  `Rédiger un texte en ${nom.toLowerCase()}, le corriger, puis le lire à voix haute.`,
  'e:Rédiger un texte de quelques phrases|Le relire et le corriger|Le lire à voix haute',
  `cours ${article}${nom.toLowerCase()}`,
];

export default {
  danse: {
    'Salsa': ['Salsa, un cours aujourd’hui', 'Suivre un cours de salsa guidé aujourd’hui : pas de base, tours et déplacements.', 's', 'Salsa, une chorégraphie complète', 'Apprendre une petite chorégraphie de salsa et la danser de bout en bout sur la musique.', 'e:Apprendre les pas de base|Apprendre les tours et déplacements|Enchaîner la chorégraphie sur la musique', 'cours de salsa'],
    'Hip-hop': ['Hip-hop, un enchaînement de 8 temps', 'Apprendre un enchaînement de 8 temps de hip-hop et le répéter 5 fois sans t’arrêter.', 'c:5:répétitions', 'Hip-hop, un enchaînement présenté', 'Apprendre un enchaînement de hip-hop d’environ 2 minutes, puis le présenter à quelqu’un.', 'e:Apprendre l’enchaînement par blocs|Le répéter sur la musique|Le présenter à quelqu’un', 'cours de hip-hop'],
    'Valse': ['Valse, dix séries de pas', 'Réussir 10 séries de pas de base de valse à trois temps, en comptant à voix haute.', 'c:10:séries', 'Valse, un morceau entier', 'Apprendre les rotations puis danser une valse sur un morceau entier, seul ou avec un partenaire.', 'e:Maîtriser les pas de base|Apprendre les rotations|Danser un morceau entier', 'cours de valse'],
    'Danse contemporaine': ['Danse contemporaine, un cours', 'Suivre un cours de danse contemporaine aujourd’hui : échauffement, travail au sol, traversée.', 's', 'Danse contemporaine, une phrase dansée', 'Créer une courte phrase chorégraphique de 4 mouvements, la répéter, puis la danser devant quelqu’un.', 'e:Choisir 4 mouvements|Les enchaîner 10 fois|La danser devant quelqu’un', 'cours de danse contemporaine'],
    'Zumba': ['Zumba, un cours aujourd’hui', 'Suivre un cours de zumba aujourd’hui, en vidéo ou en salle.', 's', 'Zumba, trois cours dans la semaine', 'Suivre 3 cours de zumba sur la semaine.', 'c:3:cours', 'cours de zumba'],
  },
  musculation: {
    'Muscu haut du corps': ['Haut du corps, 30 répétitions', 'Faire 30 répétitions de haut du corps : 10 pompes, 10 rowings et 10 développés.', 'c:30:répétitions', 'Haut du corps, 3 séances', 'Faire 3 séances de haut du corps dans la semaine : pompes, tirages et développés.', 'c:3:séances', 'séances de haut du corps'],
    'Jambes et fessiers': ['Jambes, 40 répétitions', 'Faire 40 répétitions de jambes : 20 squats et 10 fentes par jambe.', 'c:40:répétitions', 'Jambes et fessiers, 3 séances', 'Faire 3 séances de jambes et de fessiers : squats, fentes, ponts fessiers.', 'c:3:séances', 'séances de jambes'],
    'Dos et tirage': ['Dos, 30 tirages', 'Faire 30 tirages (rowing, élastique ou tractions assistées) en gardant le dos droit.', 'c:30:tirages', 'Dos et tirage, 3 séances', 'Faire 3 séances de dos et de tirage dans la semaine.', 'c:3:séances', 'séances de dos'],
    'Corps entier haltères': ['Haltères, un circuit corps entier', 'Faire un circuit avec haltères : 10 squats, 10 développés et 10 rowings.', 'e:10 squats|10 développés|10 rowings', 'Haltères, 3 séances', 'Faire 3 séances corps entier avec haltères dans la semaine.', 'c:3:séances', 'séances aux haltères'],
    'Kettlebell': ['Kettlebell, 20 swings', 'Faire 20 swings de kettlebell, hanches en avant et dos plat.', 'c:20:swings', 'Kettlebell, 100 swings', 'Cumuler 100 swings de kettlebell sur la semaine.', 'c:100:swings', 'séances de kettlebell'],
  },
  pilates: {
    'Pilates débutant': ['Pilates débutant, un cours', 'Suivre un cours de Pilates pour débutants aujourd’hui.', 's', 'Pilates débutant, 3 cours', 'Suivre 3 cours de Pilates pour débutants dans la semaine.', 'c:3:cours', 'cours de Pilates'],
    'Pilates gainage': ['Pilates gainage, 2 minutes', 'Tenir 2 minutes au total en gainage de style Pilates, en plusieurs séries.', 't:2', 'Pilates gainage, 3 séances', 'Faire 3 séances de gainage Pilates dans la semaine.', 'c:3:séances', 'séances de gainage'],
    'Pilates dos et posture': ['Pilates dos, trois exercices', 'Faire 10 rotations du bassin, 10 élévations de bras allongé et 10 chats-vaches.', 'e:10 rotations du bassin|10 élévations de bras allongé|10 chats-vaches', 'Pilates dos, 3 séances', 'Faire 3 séances de Pilates dos et posture dans la semaine.', 'c:3:séances', 'séances pour le dos'],
    'Pilates jambes et fessiers': ['Pilates jambes, 30 répétitions', 'Faire 30 répétitions de jambes en Pilates : ponts, élévations latérales, cercles de jambe.', 'c:30:répétitions', 'Pilates jambes, 3 séances', 'Faire 3 séances de Pilates jambes et fessiers dans la semaine.', 'c:3:séances', 'séances de jambes'],
    'Pilates avec ballon': ['Pilates ballon, un cours', 'Suivre un cours de Pilates avec ballon aujourd’hui.', 's', 'Pilates ballon, 2 cours', 'Suivre 2 cours de Pilates avec ballon dans la semaine.', 'c:2:cours', 'cours avec ballon'],
  },
  yoga: {
    'Yoga doux': ['Yoga doux, une séance', 'Faire une séance de yoga doux aujourd’hui, en suivant une vidéo ou un cours.', 's', 'Yoga doux, 3 séances', 'Faire 3 séances de yoga doux dans la semaine.', 'c:3:séances', 'séances de yoga doux'],
    'Yoga vinyasa': ['Vinyasa, 3 salutations au soleil', 'Enchaîner 3 salutations au soleil, en coordonnant mouvement et respiration.', 'c:3:salutations', 'Vinyasa, 15 salutations', 'Cumuler 15 salutations au soleil sur la semaine.', 'c:15:salutations', 'séances de vinyasa'],
    'Yoga du dos': ['Yoga du dos, trois postures', 'Enchaîner chien tête en bas, chat-vache et posture de l’enfant, 5 respirations chacune.', 'e:Chien tête en bas|Chat-vache|Posture de l’enfant', 'Yoga du dos, 3 séances', 'Faire 3 séances de yoga du dos dans la semaine.', 'c:3:séances', 'séances de yoga du dos'],
    'Yin yoga': ['Yin yoga, trois postures tenues', 'Tenir 3 postures de yin yoga (papillon, libellule, sphinx) avec des respirations lentes.', 'c:3:postures', 'Yin yoga, 3 séances', 'Faire 3 séances de yin yoga dans la semaine.', 'c:3:séances', 'séances de yin yoga'],
    'Yoga équilibres': ['Yoga équilibres, 4 tenues', 'Tenir l’arbre et le guerrier III, 2 fois de chaque côté.', 'c:4:postures', 'Yoga équilibres, 3 séances', 'Faire 3 séances d’équilibres en yoga dans la semaine.', 'c:3:séances', 'séances d’équilibres'],
  },
  cuisine: {
    'Pâtes fraîches': ['Pâtes fraîches, une pâte maison', 'Préparer une pâte à pâtes fraîches maison : farine, œufs, pétrissage et repos.', 's', 'Pâtes fraîches, un plat complet', 'Préparer des pâtes fraîches de bout en bout et les déguster avec une sauce maison.', 'e:Préparer et reposer la pâte|Façonner tagliatelles ou raviolis|Cuire et servir avec une sauce maison', 'plats de pâtes fraîches'],
    'Pain maison': ['Pain maison, une fournée', 'Préparer et enfourner un pain maison aujourd’hui.', 's', 'Pain maison, 2 fournées', 'Réussir 2 pains maison dans la semaine.', 'c:2:pains', 'pains maison'],
    'Cuisine du monde': ['Cuisine du monde, un plat inconnu', 'Cuisiner un plat d’un pays dont tu ne connais pas la cuisine.', 's', 'Cuisine du monde, 2 recettes', 'Cuisiner 2 plats de pays différents dans la semaine.', 'c:2:recettes', 'plats du monde'],
    'Batch cooking': ['Batch cooking, 2 repas d’avance', 'Préparer à l’avance 2 repas pour les jours qui viennent.', 'c:2:repas', 'Batch cooking, une session de 5 repas', 'Organiser une session de batch cooking pour 5 repas.', 'e:Planifier le menu|Faire les courses|Cuisiner toutes les préparations|Ranger en portions', 'sessions de batch cooking'],
    'Pâtisserie': ['Pâtisserie, un dessert maison', 'Réaliser un gâteau ou un dessert maison aujourd’hui.', 's', 'Pâtisserie, 2 desserts', 'Réaliser 2 desserts maison différents dans la semaine.', 'c:2:desserts', 'desserts maison'],
  },
  botanique: {
    'Plantes d’intérieur': ['Plantes, un tour de soins', 'Faire le tour de tes plantes : arroser si besoin, retirer les feuilles sèches, tourner vers la lumière.', 's', 'Plantes, une fiche pour chacune', 'Identifier tes plantes d’intérieur et noter leurs besoins, puis rempoter ou bouturer l’une d’elles.', 'e:Identifier chaque plante|Noter ses besoins en eau et en lumière|Rempoter ou bouturer une plante', 'soins aux plantes'],
    'Potager': ['Potager, un geste', 'Faire un geste au potager : semer, arroser, désherber ou récolter.', 's', 'Potager, 3 interventions', 'Faire 3 interventions au potager dans la semaine.', 'c:3:interventions', 'séances de potager'],
    'Herbes aromatiques': ['Herbes aromatiques, une herbe fraîche', 'Utiliser une herbe aromatique fraîche dans un plat aujourd’hui.', 's', 'Herbes aromatiques, 3 herbes', 'Reconnaître et utiliser 3 herbes aromatiques différentes dans la semaine.', 'c:3:herbes', 'herbes utilisées'],
    'Reconnaître les arbres': ['Arbres, 3 identifiés', 'Identifier 3 arbres autour de toi grâce à leurs feuilles, leur écorce ou leurs fruits.', 'c:3:arbres', 'Arbres, 10 identifiés', 'Identifier 10 arbres différents dans la semaine.', 'c:10:arbres', 'arbres identifiés'],
    'Compost et sol': ['Compost, un geste', 'Alimenter ton compost ou observer la terre de ton jardin ou d’un parc.', 's', 'Compost, trois étapes', 'Soigner un compost : trier les déchets, le retourner, observer sa couleur et son odeur.', 'e:Trier les déchets compostables|Retourner le compost|Observer la couleur et l’odeur', 'gestes de compost'],
  },
  course: {
    'Footing facile': ['Footing facile, 20 minutes', 'Courir 20 minutes à allure facile, où tu peux encore parler.', 't:20', 'Footing facile, 3 sorties', 'Faire 3 footings faciles dans la semaine.', 'c:3:sorties', 'footings'],
    'Fractionné': ['Fractionné, 6 accélérations', 'Faire 6 accélérations de 30 secondes séparées de 1 minute de récupération, après échauffement.', 'c:6:accélérations', 'Fractionné, 2 séances', 'Faire 2 séances de fractionné dans la semaine.', 'c:2:séances', 'séances de fractionné'],
    'Préparation 10 km': ['Préparation 10 km, 3 kilomètres', 'Courir 3 kilomètres à ton rythme.', 'c:3:km', 'Préparation 10 km, 12 kilomètres', 'Cumuler 12 kilomètres de course sur la semaine.', 'c:12:km', 'sorties de préparation'],
    'Côtes et dénivelé': ['Côtes, 5 montées', 'Monter 5 côtes en courant, redescendre en marchant.', 'c:5:côtes', 'Côtes, 2 séances', 'Faire 2 séances de côtes dans la semaine.', 'c:2:séances', 'séances de côtes'],
    'Marche-course': ['Marche-course, 8 cycles', 'Faire 8 cycles de 1 minute de course et 2 minutes de marche.', 'c:8:cycles', 'Marche-course, 3 sorties', 'Faire 3 sorties de marche-course dans la semaine.', 'c:3:sorties', 'sorties de marche-course'],
  },
  natation: {
    'Crawl': ['Crawl, 10 longueurs', 'Nager 10 longueurs de crawl, en soufflant dans l’eau.', 'c:10:longueurs', 'Crawl, 3 séances', 'Faire 3 séances de crawl dans la semaine.', 'c:3:séances', 'séances de crawl'],
    'Brasse': ['Brasse, 10 longueurs', 'Nager 10 longueurs de brasse, bien glissées.', 'c:10:longueurs', 'Brasse, 3 séances', 'Faire 3 séances de brasse dans la semaine.', 'c:3:séances', 'séances de brasse'],
    'Dos crawlé': ['Dos crawlé, 8 longueurs', 'Nager 8 longueurs de dos crawlé, bassin haut.', 'c:8:longueurs', 'Dos crawlé, 3 séances', 'Faire 3 séances de dos crawlé dans la semaine.', 'c:3:séances', 'séances de dos crawlé'],
    'Endurance en piscine': ['Endurance, 20 longueurs', 'Nager 20 longueurs en continu, à ton rythme.', 'c:20:longueurs', 'Endurance en piscine, 3 séances', 'Faire 3 séances de nage d’endurance dans la semaine.', 'c:3:séances', 'séances de natation'],
    'Aquagym': ['Aquagym, un cours', 'Suivre un cours d’aquagym aujourd’hui.', 's', 'Aquagym, 2 cours', 'Suivre 2 cours d’aquagym dans la semaine.', 'c:2:cours', 'cours d’aquagym'],
  },
  'arts-martiaux': {
    'Boxe': ['Boxe, 3 rounds dans le vide', 'Faire 3 rounds de boxe dans le vide : directs, crochets, esquives.', 'c:3:rounds', 'Boxe, 3 séances', 'Faire 3 séances de boxe dans la semaine.', 'c:3:séances', 'séances de boxe'],
    'Judo': ['Judo, 10 chutes', 'T’entraîner à tomber en sécurité : 10 chutes avant et arrière.', 'c:10:chutes', 'Judo, 2 cours', 'Suivre 2 cours de judo dans la semaine.', 'c:2:cours', 'cours de judo'],
    'Karaté': ['Karaté, 5 katas', 'Répéter 5 fois le kata que tu travailles en ce moment.', 'c:5:katas', 'Karaté, 3 séances', 'Faire 3 séances de karaté dans la semaine.', 'c:3:séances', 'séances de karaté'],
    'Taï-chi': ['Taï-chi, une forme complète', 'Enchaîner une fois en entier la forme de taï-chi que tu apprends.', 's', 'Taï-chi, 3 séances', 'Faire 3 séances de taï-chi dans la semaine.', 'c:3:séances', 'séances de taï-chi'],
    'Self-défense': ['Self-défense, trois techniques', 'Apprendre 3 techniques : se dégager d’une saisie, frapper, s’échapper.', 'e:Se dégager d’une saisie|Frapper|S’échapper', 'Self-défense, 2 cours', 'Suivre 2 cours de self-défense dans la semaine.', 'c:2:cours', 'cours de self-défense'],
  },
  escalade: {
    'Bloc débutant': ['Bloc, 5 blocs réussis', 'Réussir 5 blocs de ton niveau.', 'c:5:blocs', 'Bloc, 2 séances', 'Faire 2 séances de bloc dans la semaine.', 'c:2:séances', 'séances de bloc'],
    'Escalade technique': ['Escalade technique, 3 blocs', 'Travailler 3 blocs en cherchant des placements de pieds précis.', 'c:3:blocs', 'Escalade technique, 2 séances', 'Faire 2 séances centrées sur la technique dans la semaine.', 'c:2:séances', 'séances de technique'],
    'Grimpe en voie': ['Grimpe en voie, 2 voies', 'Réussir 2 voies de ton niveau, assuré par un partenaire.', 'c:2:voies', 'Grimpe en voie, 2 séances', 'Faire 2 séances de grimpe en voie dans la semaine.', 'c:2:séances', 'séances en voie'],
    'Renfo pour grimpeurs': ['Renfo grimpeur, trois blocs', 'Faire 3 séries de tractions, de gainage et de pompes.', 'e:3 séries de tractions|3 séries de gainage|3 séries de pompes', 'Renfo grimpeur, 2 séances', 'Faire 2 séances de renforcement pour grimpeurs dans la semaine.', 'c:2:séances', 'séances de renfo'],
    'Souplesse du grimpeur': ['Souplesse grimpeur, trois étirements', 'Étirer hanches, épaules, doigts et avant-bras.', 'e:Étirement des hanches|Étirement des épaules|Étirement des doigts et avant-bras', 'Souplesse grimpeur, 3 séances', 'Faire 3 séances de souplesse dans la semaine.', 'c:3:séances', 'séances de souplesse'],
  },
  musique: {
    'Guitare': ['Guitare, 10 enchaînements d’accords', 'Enchaîner deux accords 10 fois de suite sans t’arrêter.', 'c:10:enchaînements', 'Guitare, une chanson simple', 'Apprendre une chanson simple à la guitare et la jouer devant quelqu’un.', 'e:Apprendre les accords|La jouer en entier|La jouer devant quelqu’un', 'séances de guitare'],
    'Piano': ['Piano, 5 gammes', 'Jouer 5 gammes, mains séparées puis ensemble.', 'c:5:gammes', 'Piano, un morceau appris', 'Apprendre un morceau court au piano et le jouer en entier.', 'e:Déchiffrer la main droite|Déchiffrer la main gauche|Jouer mains ensemble', 'séances de piano'],
    'Ukulélé': ['Ukulélé, 10 enchaînements d’accords', 'Enchaîner trois accords 10 fois de suite.', 'c:10:enchaînements', 'Ukulélé, une chanson', 'Apprendre une chanson simple au ukulélé et la chanter en t’accompagnant.', 'e:Apprendre les accords|La jouer en entier|La chanter en jouant', 'séances de ukulélé'],
    'Batterie ou percussions': ['Batterie, un rythme 20 fois', 'Jouer un rythme de base 20 mesures de suite sans erreur.', 'c:20:mesures', 'Batterie, 3 rythmes', 'Apprendre 3 rythmes de base (rock, funk, shuffle).', 'e:Apprendre le rythme rock|Apprendre le rythme funk|Apprendre le shuffle', 'séances de batterie'],
    'Chant et solfège': ['Chant, trois exercices', 'Faire 5 vocalises, chanter une chanson et lire une ligne de solfège.', 'e:5 vocalises|Chanter une chanson|Lire une ligne de solfège', 'Chant, une chanson enregistrée', 'Apprendre une chanson, la chanter en entier et l’enregistrer.', 'e:Apprendre les paroles et la mélodie|La chanter en entier|L’enregistrer et la réécouter', 'séances de chant'],
  },
  theatre: {
    'Improvisation': ['Improvisation, une scène d’une minute', 'Improviser une scène d’une minute à partir d’un thème tiré au hasard.', 's', 'Improvisation, 3 scènes', 'Improviser 3 scènes avec un partenaire dans la semaine.', 'c:3:scènes', 'séances d’improvisation'],
    'Éloquence': ['Éloquence, un discours d’une minute', 'Préparer et dire à voix haute un discours d’une minute.', 's', 'Éloquence, un discours devant quelqu’un', 'Écrire un discours en trois parties, le répéter, puis le prononcer devant quelqu’un.', 'e:Écrire un discours en trois parties|Le répéter 3 fois|Le prononcer devant quelqu’un', 'séances d’éloquence'],
    'Chant': ['Chant, 5 vocalises', 'Faire 5 vocalises puis chanter un refrain.', 'c:5:vocalises', 'Chant, une chanson présentée', 'Apprendre une chanson et la chanter devant quelqu’un.', 'e:Apprendre la chanson|La chanter en entier|La chanter devant quelqu’un', 'séances de chant'],
    'Lecture à voix haute': ['Lecture à voix haute, 2 pages', 'Lire 2 pages à voix haute en articulant et en variant le ton.', 'c:2:pages', 'Lecture à voix haute, un texte partagé', 'Choisir un texte et le lire à voix haute devant quelqu’un, puis demander un retour.', 'e:Choisir un texte|Le lire à voix haute devant quelqu’un|Demander un retour', 'séances de lecture à voix haute'],
    'Théâtre': ['Théâtre, 5 répliques apprises', 'Apprendre 5 répliques par cœur et les dire avec intention.', 'c:5:répliques', 'Théâtre, une scène jouée', 'Apprendre une scène à deux et la jouer devant quelqu’un.', 'e:Apprendre mon texte|Répéter la scène|La jouer devant quelqu’un', 'séances de théâtre'],
  },
  dessin: {
    'Dessin d’observation': ['Dessin d’observation, un objet', 'Dessiner un objet que tu as sous les yeux, en regardant plus qu’en traçant.', 's', 'Dessin d’observation, 5 dessins', 'Faire 5 dessins d’observation dans la semaine.', 'c:5:dessins', 'dessins d’observation'],
    'Aquarelle': ['Aquarelle, une petite étude', 'Peindre une petite étude à l’aquarelle : paysage, fruit ou nature morte.', 's', 'Aquarelle, 3 études', 'Peindre 3 études à l’aquarelle dans la semaine.', 'c:3:aquarelles', 'études à l’aquarelle'],
    'Croquis urbain': ['Croquis urbain, 3 croquis', 'Faire 3 croquis rapides de ce que tu vois dehors : bâtiments, passants, mobilier.', 'c:3:croquis', 'Croquis urbain, 10 croquis', 'Faire 10 croquis urbains dans la semaine.', 'c:10:croquis', 'croquis urbains'],
    'Peinture acrylique': ['Acrylique, une petite étude', 'Peindre une petite étude à l’acrylique.', 's', 'Acrylique, une toile en trois temps', 'Réaliser une petite toile : esquisse, grandes masses, détails.', 'e:Esquisser la composition|Peindre les grandes masses|Finir les détails', 'séances d’acrylique'],
    'Calligraphie': ['Calligraphie, 10 lignes', 'Écrire 10 lignes de lettres en calligraphie, avec régularité.', 'c:10:lignes', 'Calligraphie, un alphabet complet', 'Écrire l’alphabet entier, puis un mot, puis une phrase en calligraphie.', 'e:Écrire l’alphabet entier|Écrire un mot soigné|Écrire une phrase complète', 'séances de calligraphie'],
  },
  langues: {
    'Anglais': lang('Anglais', 'd’'),
    'Espagnol': lang('Espagnol', 'd’'),
    'Italien': lang('Italien', 'd’'),
    'Allemand': lang('Allemand', 'd’'),
    'Langue des signes': ['Langue des signes, 10 signes', 'Apprendre 10 signes nouveaux et les répéter sans aide.', 'c:10:signes', 'Langue des signes, une présentation signée', 'Apprendre le vocabulaire d’un thème, signer une présentation de toi et la montrer à quelqu’un.', 'e:Apprendre le vocabulaire d’un thème|Signer ma présentation|La montrer à quelqu’un', 'cours de langue des signes'],
  },
  programmation: {
    'Python débutant': ['Python, 2 exercices', 'Résoudre 2 exercices de Python sur un site d’apprentissage.', 'c:2:exercices', 'Python, un mini-programme', 'Écrire un petit programme Python (calculatrice, jeu de devinette), le tester et le corriger.', 'e:Écrire le programme|Le tester|Corriger les erreurs', 'séances de Python'],
    'HTML et CSS': ['HTML et CSS, une page modifiée', 'Modifier une page web : titre, couleurs et mise en page.', 's', 'HTML et CSS, une page personnelle', 'Construire une petite page personnelle avec titre, texte, image et styles.', 'e:Écrire la structure HTML|Ajouter le style CSS|Vérifier sur téléphone et ordinateur', 'séances de HTML et CSS'],
    'JavaScript': ['JavaScript, 2 exercices', 'Résoudre 2 exercices de JavaScript.', 'c:2:exercices', 'JavaScript, une petite interaction', 'Créer une petite interaction en JavaScript : bouton, compteur ou mini-jeu.', 'e:Écrire le code|Le tester dans le navigateur|Corriger les erreurs', 'séances de JavaScript'],
    'Algorithmique': ['Algorithmique, 2 problèmes', 'Résoudre 2 problèmes d’algorithmique en expliquant ta méthode.', 'c:2:problèmes', 'Algorithmique, 5 problèmes', 'Résoudre 5 problèmes d’algorithmique dans la semaine.', 'c:5:problèmes', 'séances d’algorithmique'],
    'Automatiser avec un script': ['Script, une tâche répétitive', 'Écrire un petit script qui fait une tâche répétitive à ta place.', 's', 'Script, une tâche automatisée', 'Repérer une tâche répétitive, écrire le script, puis le lancer et le corriger.', 'e:Repérer une tâche répétitive|Écrire le script|Le lancer et le corriger', 'scripts écrits'],
  },
  'lecture-ecriture': {
    'Roman': ['Roman, 10 pages', 'Lire 10 pages de ton roman en cours.', 'c:10:pages', 'Roman, 100 pages', 'Lire 100 pages de roman dans la semaine.', 'c:100:pages', 'séances de lecture'],
    'Essai ou documentaire': ['Essai, 10 pages', 'Lire 10 pages d’un essai ou d’un livre documentaire.', 'c:10:pages', 'Essai, un chapitre résumé', 'Lire un chapitre, le résumer en cinq lignes, puis en parler à quelqu’un.', 'e:Lire un chapitre|Le résumer en cinq lignes|En parler à quelqu’un', 'séances de lecture'],
    'Écriture créative': ['Écriture créative, 5 phrases', 'Écrire 5 phrases à partir d’une image ou d’un mot tiré au hasard.', 'c:5:phrases', 'Écriture créative, une nouvelle', 'Écrire une courte nouvelle d’une page, la relire et la partager.', 'e:Écrire la nouvelle|La relire et la corriger|La partager avec quelqu’un', 'séances d’écriture'],
    'Journal de bord': ['Journal de bord du jour', 'Écrire dans ton journal ce que tu as vécu aujourd’hui et ce que tu en retiens.', 'j', 'Journal de bord, 5 entrées', 'Écrire 5 entrées dans ton journal dans la semaine.', 'c:5:entrées', 'entrées de journal'],
    'Poésie': ['Poésie, un poème lu à voix haute', 'Lire un poème, puis le relire à voix haute en soignant le rythme.', 's', 'Poésie, un poème écrit', 'Écrire un poème de huit vers, le relire, puis le lire à voix haute.', 'e:Écrire un poème de huit vers|Le relire et le corriger|Le lire à voix haute', 'séances de poésie'],
  },
  meditation: {
    'Méditation de pleine conscience': ['Pleine conscience, 10 minutes', 'Méditer 10 minutes en portant l’attention sur la respiration.', 't:10', 'Pleine conscience, 5 séances', 'Faire 5 séances de méditation de pleine conscience dans la semaine.', 'c:5:séances', 'séances de méditation'],
    'Cohérence cardiaque': ['Cohérence guidée, 5 minutes', 'Respirer 5 minutes à 6 respirations par minute.', 't:5', 'Cohérence cardiaque, 7 séances', 'Faire une séance de cohérence cardiaque chaque jour pendant la semaine.', 'c:7:séances', 'séances de cohérence cardiaque'],
    'Scan corporel': ['Scan corporel, 10 minutes', 'Parcourir mentalement ton corps des pieds à la tête, en relâchant chaque zone.', 't:10', 'Scan corporel, 3 séances', 'Faire 3 scans corporels dans la semaine.', 'c:3:séances', 'séances de scan corporel'],
    'Méditation de bienveillance': ['Bienveillance, 10 minutes', 'Méditer 10 minutes en envoyant des pensées bienveillantes à toi, puis à un proche.', 't:10', 'Bienveillance, trois personnes', 'Pratiquer la méditation de bienveillance envers toi, un proche, puis une personne avec qui c’est difficile.', 'e:Bienveillance envers moi|Bienveillance envers un proche|Bienveillance envers une personne difficile', 'séances de bienveillance'],
    'Respiration profonde': ['Respiration profonde, 5 minutes', 'Respirer profondément 5 minutes par le ventre, sans effort.', 't:5', 'Respiration profonde, 7 séances', 'Faire une séance de respiration profonde chaque jour pendant la semaine.', 'c:7:séances', 'séances de respiration'],
  },
  bricolage: {
    'Menuiserie simple': ['Menuiserie, une pièce travaillée', 'Découper, poncer ou assembler une pièce de bois.', 's', 'Menuiserie, un petit objet fini', 'Fabriquer un petit objet en bois : étagère, boîte ou support.', 'e:Dessiner le projet|Découper et poncer|Assembler et finir', 'séances de menuiserie'],
    'Couture': ['Couture, 20 points droits', 'Faire 20 points droits réguliers à la main ou à la machine.', 'c:20:points', 'Couture, une réparation faite', 'Réparer un vêtement : bouton, ourlet ou déchirure.', 'e:Choisir le vêtement à réparer|Préparer fil et aiguille|Réparer et vérifier la solidité', 'séances de couture'],
    'Réparation': ['Réparation, un objet réparé', 'Réparer un petit objet cassé : prise, charnière, jouet, accessoire.', 's', 'Réparation, un objet remis en état', 'Diagnostiquer une panne, trouver la pièce ou le tutoriel, puis réparer.', 'e:Diagnostiquer la panne|Trouver la pièce ou le tutoriel|Réparer et tester', 'réparations'],
    'Modélisme': ['Modélisme, une étape de maquette', 'Assembler ou peindre une pièce de maquette.', 's', 'Modélisme, une maquette avancée', 'Faire avancer une maquette en trois étapes : assembler, peindre, finir.', 'e:Assembler les pièces|Peindre|Faire les finitions', 'séances de modélisme'],
    'Tricot ou crochet': ['Tricot ou crochet, 10 rangs', 'Tricoter ou crocheter 10 rangs réguliers.', 'c:10:rangs', 'Tricot ou crochet, un petit carré', 'Réaliser un petit carré de tricot ou de crochet jusqu’à la finition.', 'e:Monter les mailles|Tricoter ou crocheter le carré|Rabattre et rentrer les fils', 'séances de tricot ou de crochet'],
  },
  randonnee: {
    'Rando facile': ['Rando facile, une sortie', 'Faire une petite randonnée sur un sentier balisé.', 's', 'Rando facile, 2 sorties', 'Faire 2 randonnées faciles dans la semaine.', 'c:2:sorties', 'randonnées'],
    'Marche en dénivelé': ['Dénivelé, 100 mètres', 'Monter 100 mètres de dénivelé positif à pied.', 'c:100:mètres', 'Dénivelé, 500 mètres', 'Cumuler 500 mètres de dénivelé positif à pied dans la semaine.', 'c:500:mètres', 'sorties en dénivelé'],
    'Randonnée en forêt': ['Forêt, une balade attentive', 'Marcher en forêt et repérer trois arbres, un animal ou un oiseau.', 's', 'Forêt, 2 sorties', 'Faire 2 sorties en forêt dans la semaine.', 'c:2:sorties', 'sorties en forêt'],
    'Marche nordique': ['Marche nordique, 30 minutes', 'Marcher 30 minutes avec bâtons, en poussant bien.', 't:30', 'Marche nordique, 3 sorties', 'Faire 3 sorties de marche nordique dans la semaine.', 'c:3:sorties', 'sorties de marche nordique'],
    'Randonnée à la journée': ['Randonnée, une journée', 'Faire une randonnée d’une journée avec pause pique-nique.', 's', 'Randonnée, une journée préparée', 'Préparer et réussir une randonnée à la journée.', 'e:Choisir un itinéraire|Préparer le sac|Faire la randonnée', 'randonnées à la journée'],
  },
  cyclisme: {
    'Vélo de route': ['Vélo de route, 15 kilomètres', 'Rouler 15 kilomètres sur route à allure régulière.', 'c:15:km', 'Vélo de route, 50 kilomètres', 'Cumuler 50 kilomètres de vélo de route dans la semaine.', 'c:50:km', 'sorties de vélo de route'],
    'VTT': ['VTT, une sortie sur chemin', 'Faire une sortie de VTT sur chemin ou sentier.', 's', 'VTT, 2 sorties', 'Faire 2 sorties de VTT dans la semaine.', 'c:2:sorties', 'sorties de VTT'],
    'Vélo d’appartement': ['Vélo d’appartement, 20 minutes', 'Pédaler 20 minutes sur vélo d’appartement, résistance modérée.', 't:20', 'Vélo d’appartement, 3 séances', 'Faire 3 séances de vélo d’appartement dans la semaine.', 'c:3:séances', 'séances de vélo d’appartement'],
    'Vélo au quotidien': ['Vélo au quotidien, un trajet utile', 'Faire un trajet utile à vélo à la place de la voiture ou des transports.', 's', 'Vélo au quotidien, 3 trajets', 'Faire 3 trajets utiles à vélo dans la semaine.', 'c:3:trajets', 'trajets à vélo'],
    'Sortie longue à vélo': ['Sortie longue, 30 kilomètres', 'Rouler 30 kilomètres à allure régulière.', 'c:30:km', 'Sortie longue, une sortie préparée', 'Préparer l’itinéraire, vérifier le vélo, puis faire la sortie.', 'e:Préparer l’itinéraire|Vérifier le vélo|Faire la sortie', 'sorties longues'],
  },
  strategie: {
    'Échecs': ['Échecs, une partie', 'Jouer une partie d’échecs en entier.', 's', 'Échecs, 5 parties', 'Jouer 5 parties d’échecs dans la semaine et analyser une défaite.', 'c:5:parties', 'parties d’échecs'],
    'Go': ['Go, une partie sur petit plateau', 'Jouer une partie de go sur plateau 9×9.', 's', 'Go, 3 parties', 'Jouer 3 parties de go dans la semaine.', 'c:3:parties', 'parties de go'],
    'Jeux de société stratégiques': ['Jeu stratégique, une partie', 'Jouer une partie d’un jeu de société stratégique avec d’autres personnes.', 's', 'Jeu stratégique, 2 parties', 'Jouer 2 parties de jeux de société stratégiques dans la semaine.', 'c:2:parties', 'parties de jeux stratégiques'],
    'Sudoku et logique': ['Sudoku, une grille', 'Résoudre une grille de sudoku ou de logique.', 's', 'Sudoku, 7 grilles', 'Résoudre 7 grilles de sudoku ou de logique dans la semaine.', 'c:7:grilles', 'grilles de logique'],
    'Jeux de réflexes': ['Réflexes, 3 parties', 'Jouer 3 parties d’un jeu de réflexes : cartes, balle, jeu de vitesse.', 'c:3:parties', 'Réflexes, 10 parties', 'Jouer 10 parties de jeux de réflexes dans la semaine.', 'c:10:parties', 'parties de réflexes'],
  },
  sommeil: {
    'Rituel du soir': ['Rituel du soir, trois gestes', 'Ce soir : éteindre les écrans, baisser la lumière et faire un geste calme (lecture, étirements).', 'e:Éteindre les écrans|Baisser la lumière|Faire un geste calme', 'Rituel du soir, 5 soirs', 'Faire ton rituel du soir pendant 5 soirs dans la semaine.', 'c:5:soirs', 'soirs de rituel'],
    'Sieste récupératrice': ['Sieste, 20 minutes', 'Faire une sieste de 20 minutes en début d’après-midi, sans te forcer à dormir.', 't:20', 'Sieste, 3 jours', 'Faire une sieste courte 3 jours dans la semaine.', 'c:3:siestes', 'siestes'],
    'Respiration pour dormir': ['Respiration pour dormir, 5 minutes', 'Au lit, respirer lentement 5 minutes (inspire 4 secondes, expire 6 secondes).', 't:5', 'Respiration pour dormir, 5 soirs', 'Pratiquer la respiration d’endormissement 5 soirs dans la semaine.', 'c:5:soirs', 'soirs de respiration'],
    'Étirements du soir': ['Étirements du soir, trois zones', 'Étirer le dos, les hanches et la nuque avant de te coucher.', 'e:Étirement du dos|Étirement des hanches|Étirement de la nuque', 'Étirements du soir, 5 soirs', 'Faire tes étirements du soir pendant 5 soirs dans la semaine.', 'c:5:soirs', 'soirs d’étirements'],
    'Chambre propice au sommeil': ['Chambre, trois réglages', 'Aérer la chambre, baisser la température et retirer écrans et lumières.', 'e:Aérer la chambre|Baisser la température|Retirer écrans et lumières', 'Chambre, 5 nuits', 'Garder ta chambre fraîche, sombre et sans écran pendant 5 nuits.', 'c:5:nuits', 'nuits en chambre aménagée'],
  },
  nutrition: {
    'Lire les étiquettes': ['Étiquettes, 3 produits', 'Lire l’étiquette de 3 produits : sucre, sel, additifs, liste d’ingrédients.', 'c:3:produits', 'Étiquettes, 10 produits', 'Lire l’étiquette de 10 produits dans la semaine et en comparer deux.', 'c:10:produits', 'étiquettes lues'],
    'Planifier ses repas': ['Planifier, les repas de demain', 'Décider aujourd’hui des repas de demain.', 's', 'Planifier, un menu de la semaine', 'Faire le menu de la semaine, la liste de courses, puis les courses.', 'e:Faire le menu de la semaine|Écrire la liste de courses|Faire les courses', 'semaines planifiées'],
    'Assiette équilibrée': ['Assiette équilibrée, un repas', 'Composer un repas avec une protéine, un légume et un féculent.', 's', 'Assiette équilibrée, 5 repas', 'Composer 5 repas équilibrés dans la semaine.', 'c:5:repas', 'repas équilibrés'],
    'Hydratation': ['Hydratation, 8 verres', 'Boire 8 verres d’eau dans la journée.', 'c:8:verres', 'Hydratation, 5 jours réussis', 'Boire 8 verres d’eau pendant 5 jours dans la semaine.', 'c:5:jours', 'jours d’hydratation'],
    'Manger en pleine conscience': ['Pleine conscience, un repas', 'Prendre un repas sans écran, en savourant chaque bouchée.', 's', 'Pleine conscience, 5 repas', 'Prendre 5 repas en pleine conscience dans la semaine.', 'c:5:repas', 'repas en pleine conscience'],
  },
  entraide: {
    'Aide à un voisin': ['Voisin, un petit service', 'Rendre un petit service à un voisin : courses, colis, bricolage.', 's', 'Voisin, une aide concrète', 'Repérer un voisin qui a besoin d’aide, lui proposer ton aide, puis l’aider concrètement.', 'e:Repérer un voisin qui a besoin d’aide|Lui proposer mon aide|L’aider concrètement', 'services rendus à des voisins'],
    'Bénévolat associatif': ['Association, une mission choisie', 'Choisir une association, la contacter et proposer ton aide.', 'e:Choisir une association|La contacter|Fixer une mission', 'Association, 2 heures de bénévolat', 'Donner 2 heures de bénévolat à une association dans la semaine.', 'c:2:heures', 'heures de bénévolat'],
    'Cuisine solidaire': ['Cuisine solidaire, un plat en plus', 'Cuisiner un plat de plus pour quelqu’un qui en a besoin.', 's', 'Cuisine solidaire, un repas partagé', 'Préparer un repas pour quelques personnes et le partager.', 'e:Préparer un repas pour 4|Le porter ou le partager|Manger ensemble', 'repas solidaires'],
    'Soutien scolaire': ['Soutien scolaire, des devoirs aidés', 'Aider un élève à faire ses devoirs ou à comprendre une leçon.', 's', 'Soutien scolaire, 2 séances', 'Faire 2 séances de soutien scolaire dans la semaine.', 'c:2:séances', 'séances de soutien'],
    'Visite et écoute': ['Visite, une personne isolée', 'Rendre visite ou téléphoner à une personne âgée ou isolée.', 's', 'Visite, 2 heures auprès d’une personne', 'Passer 2 heures avec une personne âgée ou isolée dans la semaine.', 'c:2:heures', 'visites'],
  },
  mobilite: {
    'Étirements complets': ['Étirements guidés, 6 zones', 'Étirer nuque, épaules, dos, hanches, cuisses et mollets, 30 secondes par zone.', 'c:6:zones', 'Étirements complets, 4 séances', 'Faire 4 séances d’étirements complets dans la semaine.', 'c:4:séances', 'séances d’étirements'],
    'Mobilité des hanches': ['Mobilité des hanches, 10 cercles', 'Faire 10 cercles lents et amples de chaque hanche.', 'c:10:cercles', 'Mobilité des hanches, 4 séances', 'Faire 4 séances de mobilité des hanches dans la semaine.', 'c:4:séances', 'séances pour les hanches'],
    'Mobilité des épaules': ['Mobilité des épaules, 10 cercles', 'Faire 10 cercles lents et amples de chaque épaule.', 'c:10:cercles', 'Mobilité des épaules, 4 séances', 'Faire 4 séances de mobilité des épaules dans la semaine.', 'c:4:séances', 'séances pour les épaules'],
    'Mobilité du dos': ['Mobilité du dos guidée, 15 mouvements', 'Faire 15 mouvements de mobilité du dos : chat-vache, rotations, bascule du bassin.', 'c:15:mouvements', 'Mobilité du dos, 4 séances', 'Faire 4 séances de mobilité du dos dans la semaine.', 'c:4:séances', 'séances pour le dos'],
    'Grand écart': ['Grand écart, 3 tenues', 'Tenir 3 fois la position préparatoire du grand écart, 30 secondes chacune.', 'c:3:tenues', 'Grand écart, 4 séances', 'Faire 4 séances de préparation au grand écart dans la semaine.', 'c:4:séances', 'séances de grand écart'],
  },
};
