// 200 noms de fantasy pour le bouton « Nom aléatoire ».
export default [
  'Aldric', 'Maëlle', 'Thorin', 'Elowen', 'Gaspard', 'Isaure', 'Bran', 'Liora', 'Fenris', 'Sélène',
  'Orlan', 'Mirelle', 'Kaelen', 'Anwen', 'Dorian', 'Sylvaine', 'Eldrin', 'Nolwenn', 'Hadrien', 'Ysolde',
  'Cassiel', 'Brunehilde', 'Tristan', 'Morgane', 'Perceval', 'Viviane', 'Lancelin', 'Aveline', 'Garrick', 'Lyssandre',
  'Merlin', 'Oriane', 'Roderic', 'Elara', 'Baldric', 'Thaïs', 'Corwin', 'Maëlys', 'Galéon', 'Iseult',
  'Alaric', 'Faustine', 'Gwendal', 'Séraphine', 'Dagobert', 'Rosalinde', 'Arthfael', 'Célestine', 'Ronan', 'Lunaire',
  'Évrard', 'Amaryllis', 'Théodric', 'Clothilde', 'Kerian', 'Blanche', 'Octavien', 'Mélusine', 'Gauvain', 'Éléonore',
  'Wulfric', 'Ismérie', 'Hyacinthe', 'Aurélien', 'Fiona', 'Balthazar', 'Cerise', 'Ulric', 'Perrine', 'Valdemar',
  'Océane', 'Arnauld', 'Solveig', 'Tancrède', 'Brunelle', 'Hélios', 'Nérée', 'Sidonie', 'Léandre', 'Ophélie',
  'Ferdinand', 'Jocelyne', 'Mordred', 'Gisèle', 'Anselme', 'Yseult', 'Eudes', 'Ludivine', 'Zéphyr', 'Aliénor',
  'Rolland', 'Capucine', 'Gontran', 'Hermine', 'Archibald', 'Bérengère', 'Lothaire', 'Marjolaine', 'Cédric', 'Sibylle',
  'Fulbert', 'Domitille', 'Amaury', 'Eglantine', 'Barnabé', 'Philomène', 'Thibaut', 'Azénor', 'Savinien', 'Pervenche',
  'Évariste', 'Juliette', 'Quentin', 'Mathilde', 'Aymeric', 'Aude', 'Basile', 'Léocadie', 'Emeric', 'Armelle',
  'Gunnar', 'Freya', 'Ragnar', 'Astrid', 'Leif', 'Ingrid', 'Bjorn', 'Sigrid', 'Torvald', 'Helga',
  'Elric', 'Tamsin', 'Caradoc', 'Rhiannon', 'Taliesin', 'Branwen', 'Cadfael', 'Eluned', 'Idris', 'Seren',
  'Aramis', 'Rosalie', 'Cyrano', 'Roxane', 'Athos', 'Constance', 'Porthos', 'Milady', 'Lagardère', 'Aurore',
  'Malik', 'Samira', 'Idriss', 'Yasmine', 'Rafik', 'Leïla', 'Soren', 'Nahia', 'Tiago', 'Amara',
  'Kéthan', 'Nysa', 'Veyran', 'Ilyria', 'Dravos', 'Elaris', 'Torvan', 'Mylène', 'Zorian', 'Aelith',
  'Brutus', 'Calista', 'Dracan', 'Esmée', 'Faolan', 'Galadriel', 'Haldir', 'Ilmarë', 'Jorun', 'Kelda',
  'Lothar', 'Maelis', 'Nimrod', 'Odalys', 'Pyrrha', 'Quillan', 'Rowena', 'Sorin', 'Tessaly', 'Urien',
  'Valéry', 'Wendeline', 'Xavière', 'Yvain', 'Zélie', 'Abélard', 'Bertille', 'Clovis', 'Diane', 'Erwann',
  'Florentin', 'Garance', 'Hilarion', 'Ingeborg', 'Jehan', 'Kenza', 'Lucien', 'Mahaut', 'Néolie', 'Osmond',
];
