// Phrases modèles des bilans. Variables : {name} {best} {weak} {done} {xp}
const openers = {
  up: [
    'Cette période, {name} a pris de l’élan : {xp} XP, plus que la précédente.',
    '{name} a accéléré. Les chiffres le disent, mais les sourires aussi.',
    'Une belle montée en puissance : {done} quêtes accomplies et un rythme qui s’installe.',
    'Le feu de camp brillait fort cette période, et {name} y a gardé la main.',
    'Plus d’XP que la fois d’avant : {name} avance, et on le voit.',
    'On sent l’élan : {done} quêtes, {xp} XP, et la route devant soi.',
  ],
  down: [
    'Une période plus calme pour {name}. Les routes ne sont pas toujours des lignes droites.',
    'Moins d’XP que la précédente, mais {done} quêtes tout de même. Rien n’est perdu.',
    'Le rythme a ralenti. Ce n’est pas un échec : c’est un souffle.',
    'La Taverne était plus tranquille. Les héros ont aussi besoin de repos.',
    'Une période creuse n’efface rien de ce que {name} a bâti.',
    'Moins d’élan cette fois-ci. Le prochain pas compte plus que ceux qui manquent.',
  ],
  flat: [
    'Une période régulière pour {name} : {done} quêtes, {xp} XP, un rythme tenu.',
    'Stable comme un roc : {name} garde le cap.',
    'Pas de grandes vagues, mais une marche régulière. C’est ainsi qu’on va loin.',
    'La constance est une qualité discrète. {name} l’a cultivée.',
    'Le rythme est le même que la fois d’avant. La régularité fait son chemin.',
    'Ni plus ni moins que d’habitude : un équilibre solide.',
  ],
  first: [
    'Premier bilan pour {name} : {done} quêtes accomplies et {xp} XP pour commencer.',
    'Tout commence ici : {done} quêtes à ton actif, c’est déjà un début d’histoire.',
    'Les premières pages du journal sont écrites : {xp} XP gagnés.',
    'Une première période se referme. {name} a posé les premières pierres.',
    'Le voyage ne fait que commencer, et il a déjà de la couleur.',
    'Un premier pas, puis un autre : {done} quêtes, c’est un bon départ.',
  ],
};

const bestByAbility = {
  FOR: [
    'La Force a mené la danse : {name} a poussé, porté et tenu plus que d’habitude.',
    'La Force est en tête : les séances musculaires ont payé.',
    'Beaucoup d’effort physique cette période, et la Force en profite.',
    'C’est la Force qui a porté la période, répétition après répétition.',
    'Des muscles sollicités, des séries tenues : la Force tire la fiche vers le haut.',
    'La Force est en tête, et le reste du corps en bénéficie.',
  ],
  DEX: [
    'La Dextérité a pris les devants : souplesse, coordination et réflexes ont travaillé.',
    'La Dextérité a mené la période : étirements, jonglage, précision du geste.',
    'Beaucoup d’agilité cette fois : {name} a bougé avec plus de finesse.',
    'C’est la Dextérité qui a nourri la période, du corps à l’esprit vif.',
    'Des mains adroites, un esprit rapide : la Dextérité s’est imposée.',
    'La Dextérité est en tête, et tout paraît plus fluide.',
  ],
  CON: [
    'La Constitution a pris les devants : sommeil, repas et marche ont suivi.',
    'Le corps a répondu présent : la Constitution est en tête.',
    'Des nuits tenues et de bons repas : la Constitution s’en souvient.',
    'La Constitution s’est construite sur la régularité, la meilleure des bases.',
    'La Constitution a mené la danse, et tout le reste s’en est mieux porté.',
    'On sent que le corps a été entretenu : la Constitution est en tête.',
  ],
  INT: [
    'L’Intelligence a mené la danse : {name} a lu, appris, pratiqué.',
    'Beaucoup d’heures d’apprentissage cette période : l’Intelligence en récolte les fruits.',
    'L’Intelligence a pris la tête, nourrie par des pages, des cours et de la pratique.',
    'La tête a travaillé : l’Intelligence est en tête.',
    'L’Intelligence est la caractéristique qui a le plus progressé.',
    'Les livres sont restés ouverts : l’Intelligence a avancé.',
  ],
  SAG: [
    'La Sagesse a gagné du terrain : respirations, pauses et regard apaisé.',
    'Le calme a fait son chemin : la Sagesse est en tête.',
    'La Sagesse a porté la période, discrètement et efficacement.',
    'Beaucoup d’attention à soi cette fois : la Sagesse progresse.',
    'Moments de silence, journal, retour sur soi : la Sagesse a avancé.',
    'La Sagesse a pris les devants, et tout le reste en respire mieux.',
  ],
  CHA: [
    'Le Charisme a été à l’honneur : appels, messages et rencontres.',
    'Beaucoup de temps donné aux autres, et le Charisme en est renforcé.',
    'Le Charisme a pris la tête, nourri par l’écoute et les conversations.',
    'Les rencontres ont compté : le Charisme avance.',
    'Le Charisme est en tête, et c’est sans doute la plus belle des victoires.',
    'Entouré, présent, à l’écoute : le Charisme a mené la période.',
  ],
};

const weakByAbility = {
  FOR: [
    'La Force est restée en retrait : une courte séance de pompes ou de squats la réveillerait.',
    'Pense à ta Force : dix minutes de renforcement, et elle reprend sa place.',
    'La Force attend son heure. Une petite séance, et c’est reparti.',
    'La Force a un peu dormi : elle n’attend qu’un peu de charge à porter.',
    'Il y a de la Force à reprendre : commence par dix minutes de gainage.',
    'La Force gagnerait à être sollicitée : quelques séries par semaine suffisent.',
  ],
  DEX: [
    'Du côté de la Dextérité, c’était calme : dix minutes de souplesse ou de coordination, et tout repart.',
    'La Dextérité a été oubliée : étirements, équilibre ou jonglage lui rendraient vie.',
    'Pense à ta Dextérité : un peu de mobilité, un peu d’adresse, chaque jour.',
    'La Dextérité s’est mise en veille, mais elle se réveille vite.',
    'La Dextérité attend son tour : dix minutes d’étirements, de réflexes ou d’adresse manuelle.',
    'Un peu d’agilité ferait du bien à l’ensemble de la fiche.',
  ],
  CON: [
    'La Constitution demande de l’attention : une marche, de l’eau, un coucher plus tôt.',
    'Le corps aimerait qu’on pense à lui : la Constitution reste en retrait.',
    'Pense à ta Constitution : de petits gestes de santé, chaque jour.',
    'La Constitution s’essouffle un peu : une promenade lui rendrait le sourire.',
    'La Constitution reste à renforcer : sommeil et repas seront ses alliés.',
    'Une marche régulière et des horaires de coucher fixes redonneraient de la vigueur à la Constitution.',
  ],
  INT: [
    'Les livres sont restés fermés : l’Intelligence t’attend quand tu voudras.',
    'L’Intelligence aimerait un peu de curiosité : vingt minutes de lecture ou de cours.',
    'Pense à ton Intelligence : un quart d’heure d’étude par jour change la donne.',
    'L’Intelligence est en retrait. Une petite leçon et elle repart.',
    'L’Intelligence est restée sur l’étagère : reprends-la, même cinq minutes.',
    'Un peu d’étude fera du bien à ton Intelligence.',
  ],
  SAG: [
    'La Sagesse est en retrait : cinq minutes de silence suffiraient à la ramener.',
    'Pense à ta Sagesse : respirer, observer, écrire quelques lignes.',
    'La Sagesse aimerait un peu de calme : un souffle, une pause, un regard au loin.',
    'Un peu d’attention à soi remettrait la Sagesse en marche.',
    'Ta Sagesse a besoin de silence : dix minutes de méditation lui feront du bien.',
    'La Sagesse n’a pas eu sa part : réserve-lui un moment tranquille.',
  ],
  CHA: [
    'Le Charisme a été un peu délaissé : un message, un appel, un café.',
    'Pense à ton Charisme : un mot sincère à quelqu’un qui compte.',
    'Le Charisme attend un geste simple : écouter, remercier, inviter.',
    'Un petit signe à un proche relancerait le Charisme.',
    'Le Charisme est resté discret : une conversation suffirait à le raviver.',
    'Un peu de chaleur humaine, et le Charisme repart.',
  ],
};

const closers = {
  week: [
    'À la semaine prochaine, {name}.',
    'La route continue : la semaine qui vient a ses propres quêtes.',
    'Prends un instant pour être fier du chemin parcouru.',
    'Une nouvelle semaine s’ouvre : choisis tes quêtes avec envie.',
    'Respire, relis, repars. Le Tableau d’Affichage t’attend.',
    'Cette semaine n’est plus à refaire. La prochaine est à écrire.',
    'Garde ce qui t’a fait du bien, laisse le reste de côté.',
    'Un pas après l’autre, la semaine suivante ne demande pas plus.',
    'La régularité n’est pas un sprint : continue à ton rythme.',
    'Demain est un autre jour de jeu.',
    'Le tavernier a déjà préparé de nouvelles quêtes pour toi.',
    'Le chemin se construit en marchant. Bonne semaine, {name}.',
  ],
  month: [
    'Un mois de plus dans ton histoire. Elle commence à prendre forme.',
    'Le mois est terminé : regarde ce que tu as bâti, et choisis la suite.',
    'Un nouveau mois commence, avec ses propres défis à relever.',
    'Garde ce mois comme un repère : tu pourras y revenir quand le doute viendra.',
    'Un mois de petits pas, c’est déjà un voyage.',
    'Tu as vécu un mois entier d’aventure. Les prochains t’attendent.',
    'Prends le temps de te féliciter : c’est aussi une manière d’avancer.',
    'Le mois prochain sera ce que tu en feras. Il est déjà bien parti.',
    'Rien ne s’est perdu : tout s’est empilé.',
    'Chaque mois laisse sa trace : ceux-ci ne s’effacent pas.',
    'Un bilan n’est pas un jugement, c’est un point sur la carte.',
    'Merci pour ce mois, {name}. La Taverne t’attend pour le suivant.',
  ],
};

const templates = {
  openers: Object.entries(openers).flatMap(([trend, arr]) => arr.map((text) => ({ trend, text }))),
  best: Object.entries(bestByAbility).flatMap(([ability, arr]) => arr.map((text) => ({ ability, text }))),
  weak: Object.entries(weakByAbility).flatMap(([ability, arr]) => arr.map((text) => ({ ability, text }))),
  closers: Object.entries(closers).flatMap(([kind, arr]) => arr.map((text) => ({ kind, text }))),
};
export default templates;
