// Messages du tavernier : [texte, conditions?]. Variables : {name} {streak} {weakest} {strongest} {level}
const rows = [
  // ── Série (22)
  ['Ta série tient depuis {streak} jours. Les bardes commencent à chanter ton nom.', { streakMin: 7 }],
  ['{streak} jours d’affilée. Le feu de la cheminée n’a jamais brûlé aussi régulièrement.', { streakMin: 5 }],
  ['Une série de {streak} jours : la Taverne a gardé ta place près du feu.', { streakMin: 10 }],
  ['Trois jours de suite, {name}. C’est comme ça que les habitudes naissent.', { streakMin: 3, streakMax: 4 }],
  ['Deux jours d’affilée. Un pas, puis un autre : tu viens de tracer un chemin.', { streakMin: 2, streakMax: 2 }],
  ['Une semaine entière sans faillir ! Le tavernier a servi une tournée en ton honneur.', { streakMin: 7, streakMax: 8 }],
  ['Quatorze jours. Même les anciens murmurent que tu as la flamme.', { streakMin: 14, streakMax: 15 }],
  ['{streak} jours : tu n’es plus un voyageur de passage, tu es un habitué.', { streakMin: 20 }],
  ['Un mois de constance. Il y a des royaumes qui se sont construits avec moins.', { streakMin: 30, streakMax: 32 }],
  ['{streak} jours de suite. Le tavernier n’a plus besoin de te demander ta commande.', { streakMin: 40 }],
  ['Cent jours de flamme. On raconte ton histoire aux nouveaux arrivants.', { streakMin: 100 }],
  ['Une série si longue qu’elle a sa propre chaise à la Taverne. {streak} jours, {name}.', { streakMin: 60 }],
  ['Chaque jour compte, {name}. Aujourd’hui encore, une seule quête suffit à garder la flamme.', { streakMin: 1, daily: 'none' }],
  ['Ta flamme brille depuis {streak} jours. Il suffit d’une petite quête pour l’entretenir.', { streakMin: 3, daily: 'none' }],
  ['Pas de série pour l’instant ? Aujourd’hui est un excellent jour pour en commencer une.', { streakMax: 0, daily: 'none' }],
  ['La flamme s’est éteinte, mais les braises sont encore chaudes. Une quête, et le feu repart.', { streakMax: 0, levelMin: 2 }],
  ['Ta série est en sécurité pour aujourd’hui. Le tavernier t’en félicite.', { streakMin: 1, daily: 'some' }],
  ['Encore une quête et ta journée est complète. La flamme n’attend que ça.', { daily: 'some', streakMin: 3 }],
  ['Tu approches de la semaine pleine. Plus que quelques jours avant une nouvelle Inspiration.', { streakMin: 4, streakMax: 6 }],
  ['Sept jours de plus et tu gagnes un point d’Inspiration. Le tavernier compte avec toi.', { streakMin: 1, streakMax: 6 }],
  ['Le tavernier ne dit rien, mais il a retiré ton nom de la liste des absents. {streak} jours, bravo.', { streakMin: 6 }],
  ['Tu reviens toujours à la même table, avec le même sourire. Bonne série, {name}.', { streakMin: 8 }],
  // ── Caractéristique la plus faible (30)
  ['Ta Sagesse s’endort. Une quête t’attend de ce côté-là.', { weakest: 'SAG' }],
  ['Ton Intelligence attend son tour avec patience. Aujourd’hui, peut-être ?', { weakest: 'INT' }],
  ['Ton Charisme s’endort un peu. Un message à quelqu’un te ferait du bien aujourd’hui.', { weakest: 'CHA' }],
  ['Ta Constitution demande un peu d’air : une marche, un verre d’eau, un coucher tôt.', { weakest: 'CON' }],
  ['Ta Dextérité est restée au repos. Dix minutes de souplesse ou d’adresse, et elle se réveille.', { weakest: 'DEX' }],
  ['Ta Force attend sa petite séance du jour. Rien de grand : dix minutes suffisent.', { weakest: 'FOR' }],
  ['{weakest} est ta caractéristique la plus discrète. Elle aimerait qu’on lui parle.', { streakMin: 0 }],
  ['Le Tableau d’Affichage a quelques idées pour {weakest}. Va jeter un œil.', { streakMin: 0 }],
  ['Tes autres caractéristiques te remercient. La caractéristique {weakest} aimerait un peu d’attention.', { streakMin: 0 }],
  ['Un héros équilibré avance plus loin. Cap sur {weakest} aujourd’hui ?', { streakMin: 0 }],
  ['Un peu de {weakest} fera du bien à l’ensemble de ta fiche.', { streakMin: 0 }],
  ['Ton point fort, c’est {strongest}. Mais la force d’un héros se mesure à son maillon faible.', { streakMin: 0 }],
  ['{strongest} te porte depuis un moment. Donne un coup de pouce à {weakest}, ça te le rendra.', { streakMin: 0 }],
  ['Répartis ton effort : quand une caractéristique dort, les autres portent la charge.', { streakMin: 0 }],
  ['Le tavernier a remarqué que ta caractéristique {weakest} ne s’est pas montrée depuis un moment.', { streakMin: 0 }],
  ['Ce matin, une quête de {weakest} a l’air de te chercher. Rencontre fortuite ?', { streakMin: 0 }],
  ['Tout va bien, sauf peut-être {weakest}. Pas d’urgence : un petit geste suffira.', { streakMin: 0 }],
  ['Ta fiche aime l’équilibre. Aujourd’hui, que dirais-tu d’une quête de {weakest} ?', { streakMin: 0 }],
  ['Un peu de {weakest}, juste pour voir ? Le tavernier te prépare une quête sur mesure.', { streakMin: 0 }],
  ['Tu avances bien, {name}. Une pensée pour {weakest}, qui aimerait être de la partie.', { streakMin: 0 }],
  ['La Sagesse ne se mesure pas en kilos ni en pages lues. Elle se mesure à la qualité de ton attention.', { weakest: 'SAG', daily: 'none' }],
  ['Un livre qui attend sur la table, un mot nouveau à apprendre : ton Intelligence fait la sieste.', { weakest: 'INT', daily: 'none' }],
  ['Appeler quelqu’un, remercier, écouter : ton Charisme aime les petits gestes.', { weakest: 'CHA', daily: 'none' }],
  ['Marche, eau, sommeil : trois mots qui font beaucoup pour ta Constitution.', { weakest: 'CON', daily: 'none' }],
  ['Un étirement, un équilibre sur un pied, un geste précis : ta Dextérité n’en demande pas plus.', { weakest: 'DEX', daily: 'none' }],
  ['Quelques pompes, un sac à porter, une minute de gainage : ta Force se réveille vite.', { weakest: 'FOR', daily: 'none' }],
  ['Ta Sagesse en a besoin : cinq minutes de silence valent mieux que cinq heures d’agitation.', { weakest: 'SAG', daily: 'some' }],
  ['Il te reste une quête à faire, et c’est peut-être celle qui comptera le plus pour ta caractéristique {weakest}.', { daily: 'some' }],
  ['Même les héros les plus forts ont une faiblesse. La tienne s’appelle {weakest}, et c’est adorable.', { streakMin: 0 }],
  // ── Jour de la semaine (21)
  ['Lundi, nouvelle semaine : le Tableau d’Affichage a été mis à jour.', { monday: true }],
  ['C’est lundi. Les quêtes hebdomadaires t’attendent, choisis celles qui te donnent envie.', { monday: true }],
  ['Un lundi à la Taverne : la bière est tiède, mais le départ est tout neuf.', { monday: true }],
  ['Mardi : le jour où l’on prend son rythme. Les routes sont encore longues, mais dégagées.', { weekdays: [2] }],
  ['Mardi tranquille. Une quête, deux quêtes, et la semaine prend forme.', { weekdays: [2] }],
  ['Mercredi, le milieu du chemin. Regarde d’où tu viens, regarde où tu vas.', { weekdays: [3] }],
  ['Mercredi : le col est franchi, la descente commence. Garde ton souffle.', { weekdays: [3] }],
  ['Jeudi : l’avant-veille de la veille du week-end. Reste concentré encore un peu.', { weekdays: [4] }],
  ['Jeudi. La Taverne est calme, la route est belle. Profites-en pour avancer.', { weekdays: [4] }],
  ['Vendredi ! Dernière ligne droite avant le repos. Termine ce que tu as commencé.', { weekdays: [5] }],
  ['Le week-end approche, mais les héros n’ont pas d’horaires. Une petite quête, et tu es libre.', { weekdays: [5] }],
  ['Vendredi : avant de rentrer, vérifie si ta semaine est bien remplie.', { weekdays: [5] }],
  ['Samedi : le temps est à toi. Pourquoi pas une quête qui te fait vraiment plaisir ?', { weekdays: [6] }],
  ['Un samedi sans pression. Les quêtes libres du Tableau sont là, à ton rythme.', { weekdays: [6] }],
  ['Samedi matin : les routes sont libres, les idées aussi.', { weekdays: [6], hourMax: 12 }],
  ['Dimanche : le jour du bilan et du repos. Prends le temps de regarder ta semaine.', { weekdays: [7] }],
  ['Dimanche. Le Tableau d’Affichage se prépare pour la nouvelle semaine. Et toi ?', { weekdays: [7] }],
  ['Dimanche calme, quêtes douces. Il est temps de faire respirer ton héros.', { weekdays: [7] }],
  ['Dimanche soir : prépare ton lundi, un petit pas à la fois.', { weekdays: [7], hourMin: 17 }],
  ['Un jour de repos est permis une fois par semaine. Si tu en as besoin, déclare-le.', { weekdays: [6, 7], daily: 'none' }],
  ['La fin de semaine approche : les quêtes hebdomadaires se terminent bientôt.', { weekdays: [6, 7], daily: 'some' }],
  // ── Heure (16)
  ['Bonjour, {name}. Le feu est allumé, le café chaud, la journée est à toi.', { hourMin: 5, hourMax: 9 }],
  ['Un matin comme les autres, et pourtant il n’y en a pas deux pareils.', { hourMin: 5, hourMax: 9 }],
  ['Tôt levé, bien parti. Le Tableau d’Affichage attend tes premiers pas.', { hourMin: 5, hourMax: 8 }],
  ['Le soleil se lève sur la Taverne. Une quête avant le petit-déjeuner ?', { hourMin: 5, hourMax: 8, daily: 'none' }],
  ['Mi-journée : le tavernier sert la soupe. Prends une pause, puis une quête.', { hourMin: 11, hourMax: 14 }],
  ['L’après-midi s’étire. C’est le bon moment pour une petite quête qui te fera du bien.', { hourMin: 14, hourMax: 17 }],
  ['Le coup de mou de l’après-midi : une marche de quelques minutes vaut mieux qu’un café de plus.', { hourMin: 14, hourMax: 16 }],
  ['Le soleil descend. Il est encore temps de finir ce que tu as commencé.', { hourMin: 17, hourMax: 20, daily: 'some' }],
  ['Le soir tombe sur la Taverne. Les quêtes de la journée sont presque terminées.', { hourMin: 18, hourMax: 21, daily: 'some' }],
  ['Bonsoir, {name}. Le feu crépite, les chandelles sont allumées.', { hourMin: 18, hourMax: 23 }],
  ['Il est tard, {name}. Une dernière petite quête, puis dors bien.', { hourMin: 21, hourMax: 23, daily: 'some' }],
  ['La journée touche à sa fin. Tout ce que tu as fait compte, même ce qui n’a pas été fait.', { hourMin: 20, hourMax: 23 }],
  ['Les chandelles s’éteignent bientôt. Repose-toi, la Taverne t’attend demain.', { hourMin: 22, hourMax: 23 }],
  ['Encore debout ? Les nuits sont faites pour le repos des héros.', { hourMin: 0, hourMax: 4 }],
  ['La nuit porte conseil, mais elle porte surtout du sommeil. Va dormir, tu as bien travaillé.', { hourMin: 0, hourMax: 4 }],
  ['Veilleur de nuit ? La journée de jeu s’achève bientôt, et les quêtes se renouvellent à l’aube.', { hourMin: 1, hourMax: 3 }],
  // ── État du jour (20)
  ['Journée accomplie. La Taverne te remercie pour cette belle journée.', { daily: 'all' }],
  ['Toutes tes quêtes sont faites. Le tavernier te tend une chope bien méritée.', { daily: 'all' }],
  ['Rien à ajouter : tu as tout fait. Profite du reste de la journée.', { daily: 'all' }],
  ['Les quêtes du jour sont terminées. Si tu veux aller plus loin, le Tableau a des quêtes libres.', { daily: 'all' }],
  ['Tu as fait ce qu’il fallait. Maintenant, laisse reposer.', { daily: 'all' }],
  ['Ta fiche s’est enrichie aujourd’hui. Demain, une nouvelle page.', { daily: 'all' }],
  ['Un pas après l’autre : voilà ce que ça donne. Bravo pour aujourd’hui, {name}.', { daily: 'all' }],
  ['Le Tableau d’Affichage est vide, la Taverne est paisible. Bien joué.', { daily: 'all' }],
  ['Un bon début, {name}. Tu as déjà fait une quête aujourd’hui.', { daily: 'some', hourMax: 12 }],
  ['Il te reste quelques quêtes. Pas de pression : chaque pas compte.', { daily: 'some' }],
  ['Tu es en chemin, {name}. Encore un peu et la journée sera complète.', { daily: 'some' }],
  ['Une quête de faite, c’est déjà un bon pas dans la bonne direction.', { daily: 'some' }],
  ['Aujourd’hui n’a pas encore commencé pour ton héros. Une toute petite quête pour lancer la machine ?', { daily: 'none' }],
  ['Le Tableau d’Affichage a de nouvelles quêtes pour toi. Commence par la plus facile.', { daily: 'none' }],
  ['Pas encore de quête aujourd’hui ? Les journées se remplissent mieux à petits pas.', { daily: 'none' }],
  ['Une quête de 5 minutes suffit pour lancer la journée. Laquelle choisis-tu ?', { daily: 'none' }],
  ['Commence petit, {name}. La première quête est toujours la plus difficile.', { daily: 'none' }],
  ['Les petits pas n’ont pas besoin d’être beaux, juste d’exister.', { daily: 'none' }],
  ['Le tavernier garde ta place. Prends ton temps.', { daily: 'none' }],
  ['Tu n’as pas à tout faire, juste à commencer. Le reste suivra.', { daily: 'none' }],
  // ── Début de mois (5)
  ['Nouveau mois, nouveau défi. Le Tableau d’Affichage a été mis à jour.', { firstOfMonth: true }],
  ['Le premier du mois : un cahier neuf, des pages blanches. Qu’y écriras-tu ?', { firstOfMonth: true }],
  ['Un nouveau mois commence. Regarde les quêtes mensuelles : l’une d’elles te fera grandir.', { firstOfMonth: true }],
  ['C’est le début du mois : le bon moment pour fixer un cap.', { firstOfMonth: true }],
  ['Les saisons passent, les héros restent. Bon début de mois, {name}.', { firstOfMonth: true }],
  // ── Niveau (12)
  ['Bienvenue à la Taverne, {name}. Ici, on avance à son rythme.', { newPlayer: true }],
  ['Premier jour d’aventure ! Le tavernier t’a préparé quelques quêtes pour te lancer.', { newPlayer: true }],
  ['Chaque légende commence par une première quête. Voici la tienne.', { newPlayer: true }],
  ['Tu es nouveau ici ? Le tavernier t’explique : une quête, un pas, un peu d’XP.', { newPlayer: true }],
  ['Niveau {level} déjà. Le tavernier t’a réservé la meilleure table.', { levelMin: 5, levelMax: 9 }],
  ['Niveau {level} : les clients te saluent en entrant. Tu es devenu quelqu’un ici.', { levelMin: 10, levelMax: 14 }],
  ['Niveau {level}. On parle de toi jusque dans les villages voisins.', { levelMin: 15, levelMax: 19 }],
  ['Niveau 20 : le tavernier t’appelle Légende, mais il t’offre quand même ton verre.', { levelMin: 20 }],
  ['Niveau {level}, {name}. Chaque jour, tu écris un peu plus de ton histoire.', { levelMin: 2, levelMax: 4 }],
  ['Les débutants se reconnaissent à leur enthousiasme. Garde le tien, {name}.', { levelMax: 3 }],
  ['Les vétérans de la Taverne te regardent avec respect : tu avances.', { levelMin: 8 }],
  ['Plus tu montes, plus les quêtes sont belles. Le Grimoire te réserve de beaux défis.', { levelMin: 5 }],
  // ── Inspiration (6)
  ['Tu as une Inspiration en poche. Elle peut relancer une quête ou doubler une victoire.', { inspirationMin: 1 }],
  ['Tes Inspirations sont prêtes. Un coup de pouce du destin n’est jamais loin.', { inspirationMin: 2 }],
  ['Trois Inspirations ! Ton réservoir est plein : n’hésite pas à en profiter.', { inspirationMin: 3 }],
  ['Utilise une Inspiration pour doubler l’XP d’une quête qui te tient à cœur.', { inspirationMin: 1, daily: 'some' }],
  ['Une quête qui ne te dit rien ? Une Inspiration peut la relancer.', { inspirationMin: 1, daily: 'none' }],
  ['Chaque 7 jours de série, une Inspiration. Le tavernier tient le compte.', { streakMin: 1, streakMax: 6 }],
  // ── Retour (8)
  ['Te revoilà, {name} ! Le tavernier a gardé ta place au chaud.', { awayMin: 3 }],
  ['Tu as manqué à la Taverne. Quelques quêtes douces pour te remettre en route ?', { awayMin: 3 }],
  ['Pas de reproche : on revient quand on peut. Une petite quête, et c’est reparti.', { awayMin: 5 }],
  ['Les braises étaient encore chaudes. Bienvenue de retour.', { awayMin: 7 }],
  ['Une semaine d’absence ? Le Tableau d’Affichage t’a gardé des surprises.', { awayMin: 7 }],
  ['Les héros reviennent toujours. Le tien est de retour, et il n’a rien oublié.', { awayMin: 14 }],
  ['Tu reprends doucement, c’est parfait. Une quête à la fois.', { awayMin: 10 }],
  ['Un mois loin de la Taverne ? Le tavernier t’offre un repas de bienvenue.', { awayMin: 30 }],
  // ── Divers (10)
  ['Un petit pas, un grand élan. C’est le mot d’ordre de la maison.', {}],
  ['Il n’y a pas de mauvais début, seulement des débuts qui n’ont pas encore eu lieu.', {}],
  ['Dans cette Taverne, on ne juge personne. On trinque aux petits pas.', {}],
  ['Les grandes aventures sont faites de petits matins.', {}],
  ['La régularité bat l’intensité. Retiens-le, {name}.', {}],
  ['Un héros n’est pas quelqu’un qui ne tombe pas, c’est quelqu’un qui revient à la Taverne.', {}],
  ['Chaque quête accomplie est une pierre posée sur ton chemin.', {}],
  ['Tu n’as pas besoin d’être parfait, {name}. Juste présent.', {}],
  ['Aujourd’hui est un bon jour pour être fier de toi, un petit peu.', {}],
  ['Le tavernier te sourit. Il sait qu’on se débrouille toujours mieux quand on avance ensemble.', {}],
  ['Rien ne presse : le feu brûle, la table est dressée, et ton prochain pas t’attend.', {}],
];

export default rows;
