// INT — Intelligence : apprendre, qu’il s’agisse d’informations ou de compétences. Lecture, cours, langues, pratique guidée, mémoire.
// [difficulté, périodes (J/S/M/E), titre, ambiance (pourquoi), objectif, [conseils], validation, [tags]]
// validation : s | c:cible:unité | t:minutes | e:étape1|étape2 | j
export default [
  // ── Faciles (14)
  ['easy', 'J', 'Lecture, 10 minutes', 'Dix minutes de lecture par jour représentent un livre entier par mois.', 'Lire 10 minutes d’un livre, d’un essai ou d’un long article, sans écran de notifications.', ['Mets ton téléphone en mode silencieux.', 'Garde un livre à portée de main.'], 't:10', ['lecture', 'moins de 10 min']],
  ['easy', 'J', 'Vocabulaire de langue, 10 minutes', 'La régularité compte plus que la durée pour retenir du vocabulaire.', 'Pendant 10 minutes, apprendre ou réviser du vocabulaire dans une langue étrangère, avec une application ou des fiches.', ['Dis les mots à voix haute.', 'Révise les mots d’hier avant d’en apprendre de nouveaux.'], 't:10', ['langue', 'moins de 10 min']],
  ['easy', 'J', 'Cartes mémoire, 10 minutes', 'La révision espacée fixe l’information en mémoire à long terme.', 'Pendant 10 minutes, réviser des cartes mémoire (papier ou application) sur un sujet que tu apprends.', ['Reviens plus souvent aux cartes que tu rates.', 'Crée trois nouvelles cartes à chaque séance.'], 't:10', ['moins de 10 min']],
  ['easy', 'J', 'Podcast éducatif, 15 minutes', 'Le temps de trajet ou de ménage peut devenir du temps d’apprentissage.', 'Écouter 15 minutes d’un podcast ou d’une conférence sur un sujet que tu veux comprendre.', ['Choisis un sujet précis.', 'Note une idée à retenir à la fin.'], 't:15', ['culture']],
  ['easy', 'J', 'Tutoriel d’une compétence, 15 minutes', 'Un tutoriel court suffit pour poser les bases d’une compétence utile.', 'Suivre pendant 15 minutes un tutoriel ou un cours sur une compétence que tu veux acquérir.', ['Fais l’exercice en même temps, ne te contente pas de regarder.', 'Mets la vidéo en pause pour essayer.'], 't:15', ['numérique']],
  ['easy', 'J', 'Article de fond et résumé, 10 minutes', 'Résumer ce qu’on lit est le moyen le plus rapide de le retenir.', 'Lire un article de fond pendant 10 minutes, puis le résumer en trois phrases.', ['Écris le résumé de tête avant de relire.', 'Une seule idée par phrase.'], 't:10', ['lecture', 'moins de 10 min']],
  ['easy', 'J', 'Un fait nouveau, 5 minutes', 'Apprendre un fait par jour fait 365 connaissances en un an.', 'Pendant 5 minutes, chercher et noter un fait nouveau sur un sujet qui t’intrigue.', ['Vérifie ta source.', 'Raconte-le à quelqu’un.'], 't:5', ['moins de 10 min']],
  ['easy', 'J', 'Exercices de code, 15 minutes', 'Programmer par petites séances est plus efficace que d’attendre une grande plage de temps.', 'Pendant 15 minutes, faire des exercices de programmation sur un site d’apprentissage.', ['Commence par des exercices simples.', 'Réécris sans copier la solution.'], 't:15', ['numérique']],
  ['easy', 'J', 'Documentaire court, 20 minutes', 'Un documentaire donne une vue d’ensemble d’un sujet en peu de temps.', 'Regarder 20 minutes d’un documentaire sur un sujet nouveau pour toi.', ['Prends deux ou trois notes.', 'Cherche ensuite un mot ou un lieu cité.'], 't:20', ['culture']],
  ['easy', 'J', 'Mémorisation, 10 minutes', 'Mémoriser un texte ou une liste entraîne la mémoire de travail.', 'Pendant 10 minutes, mémoriser un court poème, une liste ou un extrait que tu veux retenir.', ['Apprends par blocs de deux lignes.', 'Récite sans regarder, puis vérifie.'], 't:10', ['moins de 10 min']],
  ['easy', 'J', 'Prise de notes, 10 minutes', 'Reformuler à l’écrit transforme une information en connaissance.', 'Pendant 10 minutes, noter à la main ce que tu as appris récemment, avec tes propres mots.', ['Fais un schéma si c’est plus clair.', 'Relis demain pour tester ta mémoire.'], 't:10', ['moins de 10 min']],
  ['easy', 'J', 'Cours en ligne, 15 minutes', 'Un cours structuré donne un cadre que les vidéos isolées n’ont pas.', 'Suivre 15 minutes d’un cours en ligne structuré (université, plateforme, formation).', ['Avance dans l’ordre du cours.', 'Note les questions pour la séance suivante.'], 't:15', ['numérique']],
  ['easy', 'J', 'Prendre en main un outil, 15 minutes', 'Maîtriser un logiciel fait gagner du temps toute l’année.', 'Pendant 15 minutes, apprendre une fonction nouvelle d’un outil que tu utilises déjà (tableur, traitement de texte, éditeur).', ['Choisis une fonction précise.', 'Note comment la refaire.'], 't:15', ['numérique']],
  ['easy', 'J', 'Explorer un sujet inconnu, 10 minutes', 'Sortir de ses sujets habituels élargit les points de repère.', 'Pendant 10 minutes, lire sur un sujet que tu ne connais pas du tout (encyclopédie, article, vidéo).', ['Choisis un sujet au hasard.', 'Écris une question que tu te poses ensuite.'], 't:10', ['culture', 'moins de 10 min']],
  // ── Modérées (12)
  ['medium', 'JS', 'Lecture, 30 minutes', 'Une demi-heure permet d’entrer dans un livre plutôt que de l’effleurer.', 'Lire 30 minutes d’un livre sans interruption.', ['Choisis un endroit calme.', 'Pose ton téléphone dans une autre pièce.'], 't:30', ['lecture']],
  ['medium', 'JS', 'Langue étrangère, 20 minutes', 'Alterner vocabulaire, écoute et expression ancre mieux la langue.', 'Pendant 20 minutes, travailler une langue étrangère : vocabulaire, écoute et une phrase écrite ou parlée.', ['Termine par une phrase de ta création.', 'Écoute une courte vidéo sans sous-titres.'], 't:20', ['langue']],
  ['medium', 'J', 'Cours en ligne, 30 minutes', 'Une séance longue permet de comprendre un concept de bout en bout.', 'Suivre 30 minutes d’un cours en ligne structuré et noter les points clés.', ['Fais les exercices proposés.', 'Écris deux questions à creuser.'], 't:30', ['numérique']],
  ['medium', 'S', 'Lecture, 120 minutes dans la semaine', 'Deux heures de lecture par semaine avancent un livre régulièrement.', 'Cumuler 120 minutes de lecture sur la semaine.', ['Lis 20 minutes chaque soir.', 'Ajoute les minutes après chaque lecture.'], 'c:120:minutes', ['lecture']],
  ['medium', 'JS', 'Compétence pratique, 30 minutes', 'Pratiquer après avoir regardé un tutoriel fixe l’apprentissage.', 'Pendant 30 minutes, apprendre une compétence pratique : 10 minutes de tutoriel puis 20 minutes à pratiquer.', ['Fais l’exercice avant de regarder la solution.', 'Note ce qui t’a bloqué.'], 't:30', ['numérique']],
  ['medium', 'S', 'Langue, 90 minutes dans la semaine', 'Cinq courtes séances par semaine donnent de meilleurs résultats qu’une longue.', 'Cumuler 90 minutes de travail d’une langue étrangère sur la semaine.', ['Quinze minutes par jour.', 'Alterne écoute, vocabulaire et expression.'], 'c:90:minutes', ['langue']],
  ['medium', 'JS', 'Révision active, 20 minutes', 'Se tester soi-même est plus efficace que relire.', 'Pendant 20 minutes, réviser en te testant : cartes mémoire, questions, résumé de mémoire.', ['Cache tes notes et récite.', 'Reviens sur les erreurs.'], 't:20', ['sans matériel']],
  ['medium', 'J', 'Documentaire ou conférence, 40 minutes', 'Un format long permet d’approfondir un sujet avec des exemples et des nuances.', 'Regarder 40 minutes d’un documentaire ou d’une conférence, et écrire trois idées à retenir.', ['Note trois idées à la fin.', 'Parle-en à quelqu’un.'], 't:40', ['culture']],
  ['medium', 'S', 'Apprentissage, 120 minutes', 'Deux heures par semaine sur un seul sujet donnent une vraie progression.', 'Cumuler 120 minutes d’apprentissage sur un sujet précis : cours, lecture, exercices.', ['Choisis un seul sujet.', 'Alterne apport de contenu et pratique.'], 'c:120:minutes', ['numérique']],
  ['medium', 'JS', 'Programmation, 30 minutes', 'Un petit projet apprend plus que des exercices isolés.', 'Pendant 30 minutes, programmer : exercices, mini-projet ou correction d’un bug.', ['Fixe un petit objectif avant de commencer.', 'Teste ton code souvent.'], 't:30', ['numérique']],
  ['medium', 'S', 'Fiches de synthèse, 60 minutes', 'Synthétiser force à comprendre et à hiérarchiser l’information.', 'Cumuler 60 minutes à rédiger des fiches de synthèse sur un sujet appris récemment.', ['Une page par chapitre.', 'Relis-les après deux jours.'], 'c:60:minutes', ['sans matériel']],
  ['medium', 'J', 'Résumé écrit, 25 minutes', 'Expliquer avec ses propres mots est le meilleur test de compréhension.', 'Pendant 25 minutes, lire un chapitre ou un article, puis rédiger un résumé d’une demi-page de mémoire.', ['Écris sans regarder le texte.', 'Compare ensuite avec l’original.'], 't:25', ['lecture']],
  // ── Audacieuses (9)
  ['high', 'S', 'Lecture, 4 heures dans la semaine', 'Quatre heures de lecture par semaine, c’est un livre de 300 pages tous les quinze jours.', 'Cumuler 4 heures de lecture sur la semaine.', ['Lis le matin ou le soir à heure fixe.', 'Alterne lecture longue et courts articles.'], 'c:240:minutes', ['lecture']],
  ['high', 'S', 'Langue, 150 minutes dans la semaine', 'Deux heures et demie par semaine permettent de progresser visiblement.', 'Cumuler 150 minutes de travail d’une langue étrangère sur la semaine.', ['Alterne leçon, vocabulaire et conversation.', 'Parle à voix haute au moins 15 minutes.'], 'c:150:minutes', ['langue']],
  ['high', 'JS', 'Session d’étude, 60 minutes', 'Une heure complète d’étude concentrée permet d’aborder des notions difficiles.', 'Étudier 60 minutes sur un sujet exigeant, avec pauses de 5 minutes toutes les 25 minutes.', ['Supprime les notifications.', 'Prépare ton matériel avant de commencer.'], 't:60', ['numérique']],
  ['high', 'S', 'Compétence, 180 minutes', 'Trois heures sur une compétence en une semaine donnent un premier résultat concret.', 'Cumuler 180 minutes d’apprentissage et de pratique d’une compétence sur la semaine.', ['Divise en séances de 30 à 45 minutes.', 'Vise un résultat concret à la fin.'], 'c:180:minutes', ['numérique']],
  ['high', 'SM', 'Un livre complet, 8 heures de lecture', 'Huit heures de lecture permettent de finir un livre de taille moyenne.', 'Cumuler 8 heures de lecture sur la période, en finissant un livre ou un gros dossier.', ['Lis chaque jour 30 minutes.', 'Prends des notes sur les passages clés.'], 'c:480:minutes', ['lecture']],
  ['high', 'S', 'Code ou cours, 150 minutes', 'Deux heures et demie de pratique structurée donnent des progrès durables.', 'Cumuler 150 minutes de cours ou de programmation sur la semaine.', ['Fais un petit projet à la fin.', 'Alterne cours et exercices.'], 'c:150:minutes', ['numérique']],
  ['high', 'M', 'Lecture, 12 heures dans le mois', 'Douze heures de lecture par mois, c’est environ trois livres.', 'Cumuler 12 heures de lecture sur le mois.', ['Lis 25 minutes par jour.', 'Alterne romans et essais.'], 'c:720:minutes', ['lecture']],
  ['high', 'M', 'Langue, 10 heures dans le mois', 'Dix heures de langue étrangère en un mois donnent une vraie différence.', 'Cumuler 10 heures de travail d’une langue étrangère sur le mois.', ['Quinze à vingt minutes par jour.', 'Parle ou écris au moins une fois par semaine.'], 'c:600:minutes', ['langue']],
  ['high', 'M', 'Compétence, 12 heures dans le mois', 'Douze heures d’apprentissage et de pratique donnent un résultat visible.', 'Cumuler 12 heures d’apprentissage d’une compétence sur le mois, avec un résultat concret à la fin.', ['Fixe-toi un projet final.', 'Pratique plus que tu ne regardes.'], 'c:720:minutes', ['numérique']],
  // ── Légendaires (5)
  ['expert', 'M', 'Lecture, 20 heures dans le mois', 'Vingt heures de lecture par mois, c’est cinq à six livres.', 'Cumuler 20 heures de lecture sur le mois.', ['Lis une heure par jour en deux fois.', 'Garde un carnet des idées marquantes.'], 'c:1200:minutes', ['lecture']],
  ['expert', 'ME', 'Compétence maîtrisée, 50 heures', 'Cinquante heures de pratique mènent à un niveau solide pour la plupart des compétences.', 'Cumuler 50 heures d’apprentissage et de pratique d’une même compétence, jusqu’à produire un résultat concret.', ['Fixe un projet final dès le départ.', 'Note chaque séance pour mesurer ta progression.'], 'c:3000:minutes', ['numérique']],
  ['expert', 'SM', 'Immersion d’étude, 10 heures', 'Dix heures concentrées sur un seul sujet créent une vraie compréhension.', 'Cumuler 10 heures d’étude sur un seul sujet, en variant lecture, cours et exercices.', ['Planifie des blocs de 45 minutes.', 'Fais une pause régulière.'], 'c:600:minutes', ['numérique']],
  ['expert', 'ME', 'Langue étrangère, 60 heures', 'Soixante heures de pratique donnent un niveau de conversation de base.', 'Cumuler 60 heures de travail d’une langue étrangère : cours, vocabulaire, écoute, conversation.', ['Parle avec quelqu’un chaque semaine.', 'Alterne les compétences orale et écrite.'], 'c:3600:minutes', ['langue']],
  ['expert', 'M', 'Étude structurée, 25 heures', 'Un cours complet ou un programme de formation se termine en un mois à ce rythme.', 'Cumuler 25 heures d’un parcours d’étude structuré sur le mois : cours, exercices et révisions.', ['Planifie ton parcours semaine par semaine.', 'Teste-toi à la fin de chaque module.'], 'c:1500:minutes', ['numérique']],
];
