// CHA — Charisme : le social. Écouter, parler, donner des nouvelles, aider les autres, prendre la parole.
// [difficulté, périodes (J/S/M/E), titre, ambiance (pourquoi), objectif, [conseils], validation, [tags]]
// validation : s | c:cible:unité | t:minutes | e:étape1|étape2 | j
export default [
  // ── Faciles (14)
  ['easy', 'J', 'Appeler un proche', 'Un coup de fil entretient un lien mieux qu’un message.', 'Appeler un proche (famille ou ami) et prendre de ses nouvelles.', ['Demande des nouvelles précises, pas seulement « ça va ».', 'Appelle à un moment où vous êtes tous deux disponibles.'], 's', ['social']],
  ['easy', 'J', 'Repas sans écran avec quelqu’un', 'Parler à table crée du lien sans effort particulier.', 'Partager un repas avec quelqu’un en discutant, sans écran.', ['Pose des questions ouvertes.', 'Range les téléphones.'], 's', ['social']],
  ['easy', 'J', 'Deux questions ouvertes', 'Écouter vraiment est la base de tout lien durable.', 'Poser 2 questions ouvertes à quelqu’un (« comment… », « qu’est-ce qui… ») et écouter les réponses sans l’interrompre.', ['Évite les questions auxquelles on répond par oui ou non.', 'Rebondis sur ce que l’autre dit.'], 'c:2:questions', ['social', 'moins de 10 min']],
  ['easy', 'J', 'Donner des nouvelles à deux personnes', 'Un petit message suffit souvent à rouvrir un lien.', 'Écrire à 2 personnes que tu n’as pas contactées depuis longtemps.', ['Personnalise chaque message.', 'Pose une question ouverte.'], 'c:2:messages', ['social', 'moins de 10 min']],
  ['easy', 'J', 'Discuter avec un voisin', 'Les petites conversations de tous les jours entretiennent l’aisance sociale.', 'Échanger quelques mots avec un voisin, un commerçant ou un inconnu et lui poser une vraie question.', ['Commence par un sujet simple : la météo, le quartier.', 'Pose une question ouverte.'], 's', ['social', 'moins de 10 min']],
  ['easy', 'J', 'Message de remerciement précis', 'Remercier précisément fait plaisir et renforce le lien.', 'Écrire un message de remerciement détaillé à quelqu’un.', ['Cite un geste précis.', 'Dis ce que ça t’a apporté.'], 's', ['social', 'moins de 10 min']],
  ['easy', 'J', 'Un café avec quelqu’un', 'Un moment informel avec quelqu’un d’autre compte plus qu’il n’y paraît.', 'Prendre un café ou un thé avec un collègue, un voisin ou un ami.', ['Propose-le simplement.', 'Garde le téléphone dans la poche.'], 's', ['social']],
  ['easy', 'J', 'Message vocal à un ami', 'Une voix transmet plus d’émotion qu’un texte.', 'Enregistrer et envoyer un message vocal à un ami qui vit loin.', ['Raconte ta journée simplement.', 'Pose une question à la fin.'], 's', ['social', 'moins de 10 min']],
  ['easy', 'J', 'Trois réponses en retard', 'Répondre aux messages en attente libère l’esprit et rassure les autres.', 'Répondre à 3 messages ou courriers personnels qui traînent.', ['Commence par les plus anciens.', 'Une réponse courte vaut mieux que pas de réponse.'], 'c:3:réponses', ['social', 'numérique']],
  ['easy', 'J', 'Une partie à plusieurs', 'Jouer ensemble crée du lien et de la complicité.', 'Jouer au moins une partie d’un jeu de société ou de cartes avec une autre personne.', ['Choisis un jeu simple.', 'Le but est de rire, pas de gagner.'], 's', ['social', 'jeu']],
  ['easy', 'J', 'Une anecdote à voix haute', 'S’entraîner à parler fort et clairement donne de l’aisance à l’oral.', 'Raconter à voix haute, devant un miroir ou en t’enregistrant, une anecdote d’une minute environ, puis te réécouter.', ['Articule et ralentis.', 'Note un point à améliorer.'], 's', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Petit service rendu', 'Aider quelqu’un sans qu’on le demande crée de la confiance.', 'Rendre un petit service à quelqu’un autour de toi : porter, expliquer, dépanner.', ['Propose avant d’agir.', 'Reste disponible sans en faire trop.'], 's', ['social']],
  ['easy', 'J', 'Deux compliments sincères', 'Un compliment sincère change la journée de quelqu’un.', 'Faire 2 compliments sincères et précis à des personnes différentes.', ['Sois précis et sincère.', 'Évite les formules toutes faites.'], 'c:2:compliments', ['social', 'moins de 10 min']],
  ['easy', 'J', 'Parler à trois personnes différentes', 'Un vrai échange, même court, vaut mieux qu’un bonjour distrait.', 'Échanger avec 3 personnes différentes au-delà d’un simple bonjour : « comment allez-vous ? », une question, une vraie réponse.', ['Écoute la réponse et rebondis dessus.', 'Voisins, commerçants, collègues, famille : tout compte.'], 'c:3:personnes', ['social', 'moins de 10 min']],
  // ── Modérées (12)
  ['medium', 'J', 'Appeler quelqu’un perdu de vue', 'Reprendre contact avec un vieux lien le réveille plus vite qu’on ne le croit.', 'Appeler quelqu’un à qui tu n’as pas parlé depuis plus de trois mois.', ['Commence par « je pensais à toi ».', 'Pose des questions sur sa vie actuelle.'], 's', ['social']],
  ['medium', 'S', 'Deux rencontres en personne', 'Voir quelqu’un en vrai renforce le lien plus que mille messages.', 'Rencontrer 2 fois un ou plusieurs proches en personne dans la semaine (café, balade, repas, visite).', ['Propose un café ou une promenade.', 'Fixe une date précise dès maintenant.'], 'c:2:rencontres', ['social']],
  ['medium', 'S', 'Retrouver deux personnes', 'Rétablir le contact avec des personnes perdues de vue entretient un réseau.', 'Contacter 2 personnes que tu n’as pas vues depuis plus de six mois et proposer un moment ensemble.', ['Commence par les plus faciles.', 'Propose une date précise.'], 'c:2:personnes', ['social']],
  ['medium', 'J', 'Un vrai repas partagé', 'Un vrai repas partagé donne le temps de se parler vraiment.', 'Partager un repas avec une ou plusieurs personnes, sans écran, en prenant le temps de discuter.', ['Cuisinez ensemble si possible.', 'Pose des questions sur l’actualité de chacun.'], 's', ['social', 'alimentation']],
  ['medium', 'JS', 'Écoute active, trois reformulations', 'Reformuler montre à l’autre qu’il est vraiment entendu.', 'Pendant une conversation, reformuler 3 fois ce que dit l’autre (« si je comprends bien… ») sans donner de conseil non demandé.', ['Laisse des silences.', 'Pose « et ensuite ? » plutôt que de donner un avis.'], 'c:3:reformulations', ['social']],
  ['medium', 'S', 'Une activité à plusieurs', 'Faire quelque chose ensemble rapproche plus que parler.', 'Faire une activité à plusieurs dans la semaine : sport, cuisine, jeu, balade, atelier.', ['Invite quelqu’un à te rejoindre.', 'Propose une activité simple.'], 'c:1:activité', ['social']],
  ['medium', 'JS', 'Préparer et dire un court exposé', 'S’entraîner à structurer son discours donne de l’assurance.', 'Préparer puis prononcer à voix haute un court exposé sur un sujet de ton choix, devant quelqu’un ou en t’enregistrant.', ['Fais trois parties : début, milieu, fin.', 'Réécoute-toi pour repérer un point à améliorer.'], 'e:Choisir un sujet et noter trois idées|M’entraîner à voix haute|Le présenter à quelqu’un ou en m’enregistrant', ['sans matériel']],
  ['medium', 'S', 'Aider un voisin ou un proche', 'Donner un coup de main concret est l’une des plus belles façons d’entretenir un lien.', 'Rendre un service concret à un voisin ou à un proche dans la semaine : courses, bricolage, déménagement, démarches, garde.', ['Propose une aide précise plutôt que « dis-moi si tu as besoin ».', 'Pense aux personnes âgées ou seules autour de toi.'], 's', ['social']],
  ['medium', 'J', 'Une vraie question à quelqu’un', 'Une question sincère ouvre plus de portes que dix banalités.', 'Poser à quelqu’un une vraie question sur sa vie, ses projets ou ce qu’il ressent, et l’écouter jusqu’au bout.', ['Choisis quelqu’un avec qui tu es à l’aise.', 'Pose des questions plutôt que de donner ton avis.'], 's', ['social']],
  ['medium', 'S', 'Deux nouvelles têtes', 'Élargir son cercle demande de sortir de ses habitudes.', 'Échanger avec 2 personnes que tu ne connais pas encore dans la semaine : événement, association, cours, voisins.', ['Présente-toi simplement.', 'Retiens un prénom et une information sur chaque personne.'], 'c:2:personnes', ['social']],
  ['medium', 'J', 'Jeu de société à trois', 'Les jeux à plusieurs créent des souvenirs partagés.', 'Jouer à un jeu de société avec au moins deux autres personnes.', ['Choisis un jeu que tout le monde connaît.', 'Garde la bonne humeur.'], 's', ['social', 'jeu']],
  ['medium', 'S', 'Deux mots de remerciement', 'Remercier fait toujours plaisir, surtout quand c’est inattendu.', 'Écrire 2 messages ou cartes de remerciement à des personnes qui ont compté pour toi.', ['Cite un souvenir précis.', 'Poste-les ou envoie-les tout de suite.'], 'c:2:messages', ['social']],
  // ── Audacieuses (9)
  ['high', 'S', 'Voir trois personnes différentes', 'Entretenir plusieurs liens en parallèle, c’est ce qui fait un cercle solide.', 'Voir 3 personnes différentes dans la semaine, en personne ou en visio.', ['Prévois deux ou trois moments fixes.', 'Alterne famille, amis et collègues.'], 'c:3:personnes', ['social']],
  ['high', 'S', 'Deux heures auprès de ceux qui en ont besoin', 'Donner du temps à quelqu’un qui en a vraiment besoin donne du sens et crée des liens durables.', 'Passer au moins 2 heures avec une personne dans le besoin ou dans le cadre d’une association : aide, visite, accompagnement, bénévolat.', ['Repère une association proche de chez toi.', 'Pense à une personne âgée, malade ou isolée de ton entourage.'], 'c:2:heures', ['social']],
  ['high', 'JS', 'Sortir avec des amis', 'Une sortie partagée construit des souvenirs communs.', 'Sortir avec des amis ou des proches : restaurant, balade, bar, cinéma, concert, soirée jeux.', ['Invite plusieurs personnes.', 'Prévois un point de rendez-vous clair.'], 's', ['social']],
  ['high', 'S', 'Prendre la parole deux fois en groupe', 'Parler en groupe, c’est la meilleure façon de gagner en assurance.', 'Prendre la parole 2 fois en groupe dans la semaine : réunion, club, impro, présentation, assemblée.', ['Prépare trois phrases clés.', 'Parle plus lentement que tu ne le crois nécessaire.'], 'c:2:interventions', ['social']],
  ['high', 'SM', 'Quatre nouvelles rencontres', 'Rencontrer de nouvelles personnes de façon régulière élargit le cercle.', 'Faire la connaissance de 4 nouvelles personnes sur la période : associations, cours, événements, voisinage.', ['Participe à un événement régulier.', 'Échange tes coordonnées avec au moins une personne.'], 'c:4:personnes', ['social']],
  ['high', 'S', 'Deux conversations de fond', 'Quelques vraies discussions dans la semaine nourrissent les liens.', 'Avoir 2 conversations profondes dans la semaine, en personne ou par téléphone.', ['Choisis des sujets importants.', 'Garde le téléphone de côté pendant les échanges.'], 'c:2:conversations', ['social']],
  ['high', 'M', 'Un moment partagé par semaine', 'Un rendez-vous social par semaine tient un cercle en vie sans effort.', 'Organiser ou rejoindre 4 moments partagés dans le mois (repas, sortie, soirée, activité), à raison d’un par semaine.', ['Planifie le moment dès le début du mois.', 'Varie les personnes.'], 'c:4:moments', ['social']],
  ['high', 'M', 'Bénévolat, 6 heures dans le mois', 'Quelques heures d’engagement dans le mois forment une vraie contribution.', 'Donner 6 heures de bénévolat, d’entraide ou d’engagement associatif sur le mois, en une ou plusieurs fois.', ['Choisis une cause qui te parle.', 'Vise une mission régulière, même courte.'], 'c:6:heures', ['social']],
  ['high', 'M', 'Trois prises de parole', 'Quelques prises de parole dans le mois changent l’aisance en public.', 'Prendre la parole en groupe 3 fois dans le mois : club d’éloquence, réunion, présentation, impro, toast.', ['Rejoins un groupe pour t’entraîner.', 'Réécoute-toi ou demande un retour après chaque fois.'], 'c:3:prises de parole', ['social']],
  // ── Légendaires (5)
  ['expert', 'M', 'Huit moments partagés dans le mois', 'Huit moments de qualité avec ton entourage, c’est deux par semaine : un vrai engagement.', 'Vivre 8 moments partagés avec des proches dans le mois : repas, appels longs, sorties, activités.', ['Planifie tes moments à l’avance.', 'Équilibre famille, amis et nouvelles rencontres.'], 'c:8:moments', ['social']],
  ['expert', 'ME', 'Bénévolat, 12 heures', 'Douze heures d’aide aux autres marquent un vrai engagement dans la durée.', 'Cumuler 12 heures de bénévolat, d’entraide ou d’engagement associatif.', ['Choisis une mission régulière.', 'Note ce que tu apprends à chaque fois.'], 'c:12:heures', ['social']],
  ['expert', 'SM', 'Un discours devant un vrai public', 'Un exposé devant un vrai public est le meilleur test d’assurance.', 'Préparer, répéter puis prononcer un exposé ou un discours devant un public réel.', ['Prépare ton propos en trois parties.', 'Répète devant un ami avant le jour J.'], 'e:Choisir mon sujet|Rédiger mon texte en trois parties|Répéter devant un ami|Prononcer le discours devant un public', ['social']],
  ['expert', 'ME', 'Quinze nouvelles rencontres', 'Quinze nouvelles personnes rencontrées bâtissent un réseau solide.', 'Faire la connaissance de 15 nouvelles personnes : événements, associations, cours, voisinage.', ['Participe à des événements réguliers.', 'Entretiens les contacts avec un message de suivi.'], 'c:15:personnes', ['social']],
  ['expert', 'M', 'Huit appels dans le mois', 'Des appels réguliers entretiennent un cercle solide, même à distance.', 'Appeler des proches 8 fois dans le mois, en variant les personnes.', ['Planifie deux appels par semaine.', 'Note qui tu n’as pas appelé depuis longtemps.'], 'c:8:appels', ['social']],
];
