// DEX — Dextérité : souplesse, équilibre, coordination, habileté manuelle, vitesse mentale.
// [difficulté, périodes (J/S/M/E), titre, ambiance (pourquoi), objectif, [conseils], validation, [tags]]
// validation : s | c:cible:unité | t:minutes | e:étape1|étape2 | j
export default [
  // ── Faciles (14)
  ['easy', 'J', 'Étirements complets, 6 zones', 'Un corps souple se blesse moins et bouge avec plus d’aisance.', 'Étirer successivement nuque, épaules, dos, hanches, cuisses et mollets, 30 secondes par zone.', ['Respire lentement dans chaque position.', 'Ne force jamais jusqu’à la douleur.'], 'c:6:zones', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Équilibre sur une jambe, 4 tenues', 'L’équilibre se travaille comme un muscle et protège contre les chutes.', 'Tenir en équilibre sur une jambe 4 fois (2 par jambe), 30 secondes chacune, yeux ouverts.', ['Fixe un point devant toi.', 'Garde un mur à portée de main au début.'], 'c:4:tenues', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Jonglage, 5 tentatives', 'Le jonglage entraîne la coordination œil-main et la concentration.', 'Tenter 5 fois une cascade de trois balles (ou foulards, ou chaussettes roulées), même si elle ne tient que quelques lancers.', ['Commence avec deux balles.', 'Lance à hauteur des yeux, regarde le sommet de la trajectoire.'], 'c:5:tentatives', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Mobilité épaules et hanches', 'Ces deux articulations limitent beaucoup de gestes : elles méritent un travail régulier.', 'Faire 10 rotations lentes et amples de chaque épaule et de chaque hanche.', ['Bouge lentement, sans à-coups.', 'Respire normalement.'], 's', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Corde à sauter, 50 sauts', 'Sauter à la corde améliore le rythme, la coordination et la légèreté des appuis.', 'Faire 50 sauts à la corde (ou mimer le geste sans corde), en séries libres.', ['Saute à peine, sur la pointe des pieds.', 'Fais des séries de 10 si tu débutes.'], 'c:50:sauts', ['moins de 10 min', 'sport']],
  ['easy', 'J', 'Calcul mental, 10 opérations', 'La vitesse de calcul mental entretient la vivacité d’esprit.', 'Résoudre 10 calculs mentaux sans calculatrice, en essayant d’aller plus vite à chaque série.', ['Invente-les ou prends-en dans une application.', 'Commence par des additions, puis monte en difficulté.'], 'c:10:calculs', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Cinq lignes de la main faible', 'Utiliser l’autre main bouscule les habitudes du cerveau et affine le geste.', 'Écrire 5 lignes de la main non dominante, en visant la lisibilité plutôt que la vitesse.', ['Tiens le stylo détendu.', 'Écris lentement, lettre par lettre.'], 'c:5:lignes', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Taper un paragraphe sans regarder', 'Taper vite et sans regarder le clavier fait gagner du temps chaque jour.', 'Recopier un paragraphe au clavier sans regarder les touches.', ['Place bien tes doigts sur la rangée de repos.', 'Va lentement : la vitesse viendra après la précision.'], 's', ['numérique']],
  ['easy', 'J', 'Pas de coordination, 10 enchaînements', 'Coordonner bras et jambes dans un rythme demande au corps d’apprendre vite.', 'Réussir 10 enchaînements de pas chassés, pas croisés et sauts latéraux sur un rythme régulier.', ['Compte à voix haute.', 'Prends un morceau avec un tempo lent.'], 'c:10:enchaînements', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Réflexes contre un mur, 30 rattrapages', 'Rattraper une balle améliore la vitesse de réaction et la précision.', 'Lancer une balle contre un mur et la rattraper 30 fois, en alternant la main droite et la main gauche.', ['Recule d’un pas quand tu maîtrises.', 'Reste sur la pointe des pieds.'], 'c:30:rattrapages', ['moins de 10 min', 'sport']],
  ['easy', 'J', 'Une grille de logique', 'Résoudre un problème sous contrainte rend l’esprit plus réactif.', 'Résoudre une grille de logique : sudoku, mots fléchés, énigme ou puzzle.', ['Choisis un niveau facile pour commencer.', 'Passe à la suite si tu bloques trop longtemps.'], 's', ['jeu']],
  ['easy', 'J', 'Mobilité du dos, 15 mouvements', 'Un dos mobile facilite tous les mouvements du quotidien.', 'Faire 15 mouvements de mobilité du dos : chat-vache, rotations, bascule du bassin.', ['Bouge lentement et respire.', 'Ne force pas dans les amplitudes.'], 'c:15:mouvements', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Un nœud ou un origami', 'Les gestes fins entraînent la précision des doigts et la patience.', 'Réussir un nœud utile ou un petit origami en suivant un tutoriel.', ['Suis le tutoriel pas à pas.', 'Recommence-le une deuxième fois sans aide.'], 's', ['sans matériel']],
  ['easy', 'J', 'Danse libre, 2 morceaux', 'Bouger au rythme de la musique entraîne la coordination et l’expression corporelle.', 'Danser librement sur 2 morceaux, en variant les mouvements et les rythmes.', ['Ferme la porte et ose.', 'Bouge tout le corps, pas seulement les jambes.'], 'c:2:morceaux', ['sans matériel', 'moins de 10 min', 'sport']],
  // ── Modérées (12)
  ['medium', 'J', 'Séance de souplesse, 10 étirements', 'Une séance complète apporte des gains de souplesse plus durables que quelques étirements.', 'Faire 10 étirements différents en tenant chacun 30 à 45 secondes.', ['Échauffe-toi quelques minutes avant.', 'Ne force jamais jusqu’à la douleur.'], 'c:10:étirements', ['sans matériel', 'sport']],
  ['medium', 'J', 'Équilibre yeux fermés, 6 tenues', 'Travailler l’équilibre sollicite les petits muscles stabilisateurs des chevilles et des genoux.', 'Tenir en équilibre sur une jambe 6 fois (3 par jambe) : 3 yeux ouverts, 3 yeux fermés, 30 secondes chacune.', ['Garde un mur à portée de main.', 'Ferme les yeux seulement quand tu es stable.'], 'c:6:tenues', ['sans matériel', 'sport']],
  ['medium', 'S', 'Mobilité, 4 séances dans la semaine', 'Quelques séances courtes de mobilité valent mieux qu’une longue séance isolée.', 'Faire 4 séances de mobilité ou d’étirements dans la semaine, de la durée de ton choix.', ['Répartis sur 4 jours différents.', 'Note chaque séance dans un calendrier.'], 'c:4:séances', ['sport']],
  ['medium', 'J', 'Jonglage, 10 cascades', 'Passer à des figures plus complexes développe la coordination fine.', 'Réussir 10 cascades de trois balles d’au moins six lancers chacune.', ['Lance régulièrement, à la même hauteur.', 'Reprends la cascade dès qu’une balle tombe.'], 'c:10:cascades', ['sans matériel']],
  ['medium', 'JS', 'Corde à sauter, 200 sauts', 'Le travail à la corde développe l’agilité des appuis et l’endurance.', 'Faire 200 sauts à la corde en alternant pas simples, pieds joints et pas de course.', ['Fais des séries de 30 à 50.', 'Garde les coudes près du corps.'], 'c:200:sauts', ['sport']],
  ['medium', 'S', 'Geste précis, 4 séances', 'La pratique régulière d’un geste précis (instrument, dessin, couture, modélisme) affine la dextérité manuelle.', 'Pratiquer 4 fois dans la semaine un geste précis : instrument, dessin, couture, calligraphie, modélisme.', ['Répartis sur 4 jours.', 'Ne cherche pas la perfection, cherche la régularité.'], 'c:4:séances', ['sans matériel']],
  ['medium', 'JS', 'Une partie de réflexes', 'Les sports de raquette ou de balle entraînent la vitesse de réaction et le placement.', 'Jouer une partie de tennis de table, badminton, ballon ou autre jeu de réflexes avec quelqu’un.', ['Reste sur la pointe des pieds.', 'Regarde la balle jusqu’au contact.'], 's', ['sport', 'jeu']],
  ['medium', 'J', 'Trois énigmes variées', 'Une série de problèmes variés entraîne le passage rapide d’une idée à l’autre.', 'Résoudre 3 énigmes différentes : logique, calcul mental, mots croisés ou casse-tête.', ['Change de type d’énigme à chaque fois.', 'Cherche seul avant de regarder la solution.'], 'c:3:énigmes', ['jeu']],
  ['medium', 'S', 'Yoga ou assouplissements, 3 séances', 'Le yoga combine souplesse, équilibre et concentration.', 'Faire 3 séances de yoga ou d’assouplissements dirigés dans la semaine.', ['Une vidéo guidée aide à suivre.', 'Garde un jour de repos entre les séances.'], 'c:3:séances', ['sport']],
  ['medium', 'JS', 'Parcours d’agilité, 5 tours', 'Slalomer, sauter et changer de direction entraîne les appuis et la vivacité.', 'Faire 5 tours d’un parcours d’agilité : slalom entre des plots, sauts latéraux, changements de direction.', ['Marque le parcours avec des objets du quotidien.', 'Commence lentement, accélère quand tu maîtrises.'], 'c:5:tours', ['sport']],
  ['medium', 'S', 'Nouvelle activité de coordination, 2 séances', 'Découvrir un nouveau mouvement oblige le cerveau à s’adapter.', 'Faire 2 séances d’une activité de coordination nouvelle pour toi : danse, escalade, arts martiaux, jonglage, sport de raquette.', ['Choisis quelque chose qui te fait un peu peur.', 'Accepte d’être maladroit au début.'], 'c:2:séances', ['sport']],
  ['medium', 'JS', 'Dactylographie, 3 tests', 'La vitesse de frappe se gagne par séances courtes et régulières.', 'Faire 3 tests de dactylographie en ligne et essayer d’améliorer ton score à chaque fois.', ['Concentre-toi sur la précision d’abord.', 'Ne regarde pas le clavier.'], 'c:3:tests', ['numérique']],
  // ── Audacieuses (9)
  ['high', 'S', 'Souplesse, 5 séances', 'Cinq séances de souplesse par semaine débloquent des amplitudes que les séances courtes ne donnent pas.', 'Faire 5 séances de souplesse dans la semaine : étirements tenus, yoga, mobilité.', ['Quelques minutes chaque jour suffisent.', 'Reste progressif sur les amplitudes.'], 'c:5:séances', ['sport']],
  ['high', 'S', 'Coordination, 3 séances dans la semaine', 'Une pratique régulière de la coordination change la façon de bouger.', 'Faire 3 séances de coordination dans la semaine : danse, arts martiaux, escalade, sports de raquette.', ['Choisis une activité qui te plaît.', 'Varie les exercices à chaque séance.'], 'c:3:séances', ['sport']],
  ['high', 'JS', 'Séance complète de yoga', 'Une séance longue permet d’aller jusqu’à des postures plus exigeantes.', 'Faire une séance complète de yoga ou d’assouplissements, avec échauffement, postures et retour au calme.', ['Suis une vidéo de niveau intermédiaire.', 'Respire profondément dans chaque posture.'], 's', ['sport']],
  ['high', 'S', 'Habileté manuelle, 5 séances', 'Plusieurs séances de pratique manuelle par semaine donnent des progrès visibles en dextérité.', 'Pratiquer 5 fois dans la semaine un geste précis : instrument, dessin, couture, calligraphie, modélisme.', ['Pratique à heure fixe.', 'Garde une trace de ton travail pour voir ta progression.'], 'c:5:séances', ['sans matériel']],
  ['high', 'SM', 'Jonglage, de la cascade à la figure', 'Quelques séances de jonglage suffisent en général pour maîtriser la cascade de trois balles et une figure.', 'Passer de la cascade de trois balles à une nouvelle figure de jonglage.', ['Pratique un peu chaque jour plutôt qu’une fois longuement.', 'Filme-toi pour repérer les erreurs.'], 'e:Réussir 20 lancers de cascade d’affilée|Réussir 50 lancers d’affilée|Apprendre une nouvelle figure', ['sans matériel']],
  ['high', 'S', 'Agilité mentale, 5 parties', 'Jouer à des jeux de stratégie et de logique entraîne la vitesse de réflexion.', 'Jouer 5 parties d’un jeu d’agilité mentale dans la semaine : échecs, logique, calcul, jeu de cartes.', ['Joue contre un adversaire de ton niveau.', 'Analyse une partie perdue.'], 'c:5:parties', ['jeu']],
  ['high', 'M', 'Mobilité, 12 séances dans le mois', 'Douze séances de mobilité par mois, c’est trois par semaine : de quoi transformer sa souplesse.', 'Faire 12 séances de mobilité, d’étirements ou de yoga sur le mois.', ['Garde un calendrier de séances.', 'Alterne haut et bas du corps.'], 'c:12:séances', ['sport']],
  ['high', 'M', 'Pratique manuelle, 10 séances', 'Dix séances en un mois suffisent à apprendre un geste complexe.', 'Faire 10 séances de pratique d’un geste précis sur le mois : instrument, dessin, modélisme, couture, calligraphie.', ['Planifie deux à trois séances par semaine.', 'Fixe-toi un petit objectif à chaque séance.'], 'c:10:séances', ['sans matériel']],
  ['high', 'M', 'Coordination, 8 séances', 'Un mois de pratique régulière transforme la coordination.', 'Faire 8 séances de sport de coordination sur le mois : escalade, danse, arts martiaux, sports de raquette.', ['Cherche un club ou un cours près de chez toi.', 'Deux séances par semaine sont idéales.'], 'c:8:séances', ['sport']],
  // ── Légendaires (5)
  ['expert', 'M', 'Souplesse, 20 séances dans le mois', 'Vingt séances de souplesse en un mois, c’est presque une par jour : une vraie transformation du corps.', 'Faire 20 séances de souplesse, de yoga ou de mobilité sur le mois. Adapte à ta condition et consulte un professionnel au besoin.', ['Quelques minutes par jour suffisent.', 'Écoute ton corps et respecte tes limites.'], 'c:20:séances', ['sport']],
  ['expert', 'ME', 'Geste maîtrisé, un vrai projet', 'Maîtriser un geste précis passe par un vrai projet, avec un résultat à montrer.', 'Mener un projet de pratique d’un geste manuel précis (instrument, dessin, couture, calligraphie) jusqu’à un résultat présentable.', ['Choisis un objectif concret.', 'Garde des traces de ta progression.'], 'e:Choisir un geste et un objectif|Pratiquer au moins 20 séances|Présenter le résultat à quelqu’un', ['sans matériel']],
  ['expert', 'SM', 'Agilité totale, 8 séances', 'Souplesse, réflexes, équilibre et coordination : toutes les formes d’agilité travaillées ensemble.', 'Faire 8 séances d’agilité variée sur la période : souplesse, équilibre, coordination, réflexes. Adapte à ta condition.', ['Change de type d’exercice à chaque séance.', 'Note ce qui te semble le plus difficile.'], 'c:8:séances', ['sport']],
  ['expert', 'ME', 'Coordination, 40 séances', 'Quarante séances suffisent pour passer d’un débutant maladroit à un pratiquant à l’aise.', 'Faire 40 séances d’une activité de coordination : danse, escalade, arts martiaux, sport de raquette. Adapte à ta condition et consulte un professionnel au besoin.', ['Choisis une activité qui te plaît vraiment.', 'Fixe-toi un objectif mesurable.'], 'c:40:séances', ['sport']],
  ['expert', 'M', 'Agilité mentale, 20 parties', 'Vingt parties de stratégie et de logique dans le mois forment un esprit vif et rapide.', 'Jouer 20 parties de jeux de stratégie, de logique ou de calcul sur le mois : échecs, go, énigmes, jeux de cartes.', ['Joue régulièrement, de préférence contre quelqu’un de meilleur.', 'Analyse tes défaites.'], 'c:20:parties', ['jeu']],
];
