// FOR — Force : le physique pur. Pousser, tirer, porter, tenir. Les quêtes se jugent en répétitions et en séances, pas au chronomètre.
// [difficulté, périodes (J/S/M/E), titre, ambiance (pourquoi), objectif, [conseils], validation, [tags]]
// validation : s | c:cible:unité | t:minutes | e:étape1|étape2 | j
export default [
  // ── Faciles (14)
  ['easy', 'J', 'Pompes, 20 aujourd’hui', 'Les pompes travaillent pectoraux, épaules et triceps sans aucun matériel.', 'Faire 20 pompes dans la journée, en autant de séries que nécessaire (sur les genoux autorisé).', ['Mieux vaut des séries propres que des répétitions bâclées.', 'Découpe en 4 séries de 5 si tu débutes.'], 'c:20:pompes', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Squats, 30 aujourd’hui', 'Les cuisses et les fessiers sont les plus gros muscles du corps : on les sollicite en premier.', 'Faire 30 squats dans la journée, dos droit et talons au sol, en une ou plusieurs séries.', ['Imagine que tu t’assois sur une chaise derrière toi.', 'Descends moins bas si tes genoux tirent.'], 'c:30:squats', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Gainage, 3 planches', 'Un tronc solide protège le dos et rend tous les autres efforts plus faciles.', 'Tenir 3 planches dans la journée, de 20 à 30 secondes chacune, avec du repos entre.', ['Coudes sous les épaules, corps aligné.', 'Mets-toi à genoux si c’est trop dur.'], 'c:3:planches', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Fentes, 20 aujourd’hui', 'Les fentes renforcent chaque jambe séparément et corrigent les déséquilibres.', 'Faire 20 fentes dans la journée (10 par jambe), avant ou arrière.', ['Garde le buste droit et le genou avant au-dessus du pied.', 'Tiens-toi à un mur au début si tu perds l’équilibre.'], 'c:20:fentes', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Chaise murale, 3 tenues', 'Tenir une position statique fatigue les cuisses plus qu’on ne le croit.', 'Tenir la position de la chaise contre un mur 3 fois, aussi longtemps que tu peux (visé : 20 à 30 secondes).', ['Cuisses à l’horizontale, dos plaqué au mur.', 'Repose-toi une minute entre les tenues.'], 'c:3:tenues', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Dips sur chaise, 15 aujourd’hui', 'Les triceps font la moitié du travail de poussée du haut du corps.', 'Faire 15 dips sur une chaise stable dans la journée, en une ou plusieurs séries.', ['Cale la chaise contre un mur pour qu’elle ne glisse pas.', 'Garde les épaules loin des oreilles.'], 'c:15:dips', ['moins de 10 min', 'sport']],
  ['easy', 'J', 'Abdominaux, 30 aujourd’hui', 'Les abdominaux stabilisent le tronc dans presque tous les mouvements de force.', 'Faire 30 abdominaux dans la journée (crunchs, relevés de jambes ou ciseaux), en séries courtes.', ['Mains près des tempes, sans tirer sur la nuque.', 'Souffle pendant l’effort.'], 'c:30:abdos', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Portage de courses à pied', 'Porter du poids sollicite tout le corps, comme dans la vraie vie.', 'Porter une charge à la main sur au moins 200 mètres : courses, packs d’eau ou sac chargé de livres.', ['Garde le dos droit et la charge près du corps.', 'Change de main à mi-parcours.'], 's', ['sport']],
  ['easy', 'J', 'Pont fessier, 20 aujourd’hui', 'Des fessiers forts soulagent le bas du dos et stabilisent le bassin.', 'Faire 20 ponts fessiers dans la journée, en marquant une pause d’une seconde en haut.', ['Pousse avec les talons, pas avec les orteils.', 'Passe sur une jambe quand c’est facile.'], 'c:20:ponts', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Escaliers à pied, 3 étages', 'Monter à pied est un effort de force et de souffle gratuit, que tu croises chaque jour.', 'Monter 3 étages à pied dans la journée, au total, plutôt que de prendre l’ascenseur.', ['Pose le pied entier sur la marche.', 'Monte une marche sur deux si tu te sens à l’aise.'], 'c:3:étages', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Circuit express, 4 exercices', 'Un circuit court sollicite tous les groupes musculaires en peu de temps.', 'Enchaîner 4 exercices l’un après l’autre : 10 pompes, 15 squats, 20 fentes (10 par jambe), 30 secondes de gainage.', ['Repose-toi à ton rythme entre les exercices.', 'Coche chaque exercice au fur et à mesure.'], 'e:10 pompes|15 squats|20 fentes|30 secondes de gainage', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Soulevés de charge, 15', 'Savoir soulever correctement protège le dos pour tous les jours qui viennent.', 'Faire 15 soulevés de charge (sac lesté, bidon d’eau) en gardant le dos droit.', ['Fléchis les genoux, ne plie pas le dos.', 'Garde la charge collée contre toi.'], 'c:15:soulevés', ['sport']],
  ['easy', 'J', 'Tirages et rowing, 20', 'Le dos fait contrepoids à tout ce qu’on pousse : il se travaille aussi.', 'Faire 20 tirages dans la journée avec un élastique, un sac chargé ou une table solide.', ['Tire les coudes vers l’arrière, pas les épaules vers les oreilles.', 'Contrôle la descente.'], 'c:20:tirages', ['moins de 10 min', 'sport']],
  ['easy', 'J', 'Burpees, 10 aujourd’hui', 'Le burpee réveille tout le corps en un seul mouvement.', 'Faire 10 burpees dans la journée, en séries de 3 à 5 si besoin.', ['Supprime le saut ou la pompe si c’est trop dur.', 'Garde un rythme régulier plutôt que de te presser.'], 'c:10:burpees', ['sans matériel', 'moins de 10 min', 'sport']],
  // ── Modérées (12)
  ['medium', 'J', 'Pompes, 40 aujourd’hui', 'Doubler la dose du jour fait franchir un cap sans mettre en danger les épaules.', 'Faire 40 pompes dans la journée, en autant de séries que nécessaire.', ['Fais 4 séries de 10 réparties dans la journée.', 'Note ton total pour battre ton record demain.'], 'c:40:pompes', ['sans matériel', 'sport']],
  ['medium', 'J', 'Squats, 60 aujourd’hui', 'Un volume de squats régulier construit des jambes solides pour la vie.', 'Faire 60 squats dans la journée, en séries de 15 à 20 avec du repos entre.', ['Descends en contrôle, remonte avec force.', 'Garde les genoux dans l’axe des pieds.'], 'c:60:squats', ['sans matériel', 'sport']],
  ['medium', 'S', 'Pompes, 200 dans la semaine', 'Quelques séries par jour s’additionnent vite : 200 pompes, c’est 30 par jour.', 'Cumuler 200 pompes sur la semaine, en autant de séries et de jours que tu veux.', ['Fais 30 pompes par jour pendant 7 jours.', 'Ajoute tes pompes après chaque série.'], 'c:200:pompes', ['sans matériel', 'sport']],
  ['medium', 'JS', 'Séance au poids du corps', 'Une séance structurée progresse plus vite que des séries lancées au hasard.', 'Faire une séance complète : échauffement, 3 séries de 10 pompes, 3 séries de 15 squats et 3 gainages de 30 secondes.', ['Repos de 45 à 60 secondes entre les séries.', 'Coche chaque bloc au fur et à mesure.'], 'e:Échauffement|3 séries de 10 pompes|3 séries de 15 squats|3 gainages de 30 secondes', ['sans matériel', 'sport']],
  ['medium', 'S', 'Squats, 300 dans la semaine', 'Le bas du corps se construit au volume, jour après jour.', 'Cumuler 300 squats sur la semaine, répartis comme tu veux.', ['Une série de 50 par jour suffit largement.', 'Passe aux squats lestés quand ça devient facile.'], 'c:300:squats', ['sans matériel', 'sport']],
  ['medium', 'JS', 'Gainage, 6 planches', 'Six planches, c’est un vrai travail du tronc, loin de la routine.', 'Tenir 6 planches (face et côtés), de 30 à 45 secondes chacune, avec du repos entre.', ['Garde le corps aligné, sans cambrer.', 'Repose-toi dès que la forme se dégrade.'], 'c:6:planches', ['sans matériel', 'sport']],
  ['medium', 'S', 'Abdominaux, 200 dans la semaine', 'Un tronc solide protège le dos dans tous les efforts.', 'Cumuler 200 abdominaux (crunchs, relevés de jambes, ciseaux) sur la semaine.', ['Fais 30 par jour en deux séries.', 'Varie les exercices pour ne pas t’ennuyer.'], 'c:200:abdos', ['sans matériel', 'sport']],
  ['medium', 'J', 'Pompes et dips, 30 de chaque', 'Pousser sur deux plans différents travaille mieux les épaules et les triceps.', 'Faire 30 pompes et 30 dips dans la journée, en séries libres.', ['Alterne pompes et dips pour reposer chaque groupe.', 'Cale bien la chaise des dips contre un mur.'], 'c:60:répétitions', ['sport']],
  ['medium', 'S', 'Séances de force, 3 dans la semaine', 'Trois séances de force par semaine suffisent à progresser régulièrement.', 'Faire 3 séances de renforcement musculaire sur la semaine, de n’importe quelle durée, avec au moins un jour de repos entre.', ['Répartis par exemple lundi, mercredi, vendredi.', 'Pas besoin de matériel : le poids du corps suffit.'], 'c:3:séances', ['sport']],
  ['medium', 'JS', 'Tirages, 30 répétitions', 'Tractions, rowing et élastiques équilibrent la poussée et protègent les épaules.', 'Faire 30 tirages (tractions, rowing, élastique) en séries de 6 à 12.', ['Une barre de porte ou une table solide suffit.', 'Aide-toi d’un élastique pour les tractions.'], 'c:30:tirages', ['sport']],
  ['medium', 'S', 'Fentes, 150 dans la semaine', 'Les fentes bâtissent des jambes stables et corrigent les déséquilibres entre droite et gauche.', 'Cumuler 150 fentes (avant ou arrière) sur la semaine.', ['Environ 25 fentes par jour, en alternant les jambes.', 'Garde le buste droit.'], 'c:150:fentes', ['sans matériel', 'sport']],
  ['medium', 'J', 'Circuit de 3 tours', 'Un circuit répété installe la force et l’endurance musculaire à la fois.', 'Faire 3 tours d’un circuit : 10 pompes, 15 squats, 10 fentes par jambe et 20 secondes de gainage.', ['Repose-toi 1 minute entre les tours.', 'Garde la même qualité de mouvement du premier au dernier tour.'], 'e:Tour 1|Tour 2|Tour 3', ['sans matériel', 'sport']],
  // ── Audacieuses (9)
  ['high', 'S', 'Pompes, 400 dans la semaine', 'Quatre cents pompes dans la semaine font franchir un palier visible.', 'Cumuler 400 pompes sur la semaine, soit environ 60 par jour.', ['Prévois 3 séries par jour.', 'Garde un jour plus léger pour récupérer.'], 'c:400:pompes', ['sans matériel', 'sport']],
  ['high', 'S', 'Séances de force, 4 dans la semaine', 'Quatre séances de force par semaine installent un vrai rythme d’entraînement.', 'Faire 4 séances de renforcement ou de musculation sur la semaine, en gardant au moins un jour de repos complet.', ['Alterne haut et bas du corps.', 'Note chaque séance dans un carnet.'], 'c:4:séances', ['sport']],
  ['high', 'JS', 'Pompes, 80 en séries', 'Un gros volume de pompes en une fois demande de la gestion d’effort.', 'Faire 80 pompes en séries de ton choix, avec repos libre entre les séries.', ['Fais des séries de 10 à 15 pour garder de la qualité.', 'Passe sur les genoux dès que la forme se dégrade.'], 'c:80:pompes', ['sans matériel', 'sport']],
  ['high', 'S', 'Squats, 500 dans la semaine', 'Cinq cents squats dans la semaine, c’est l’équivalent de quelques séries par jour.', 'Cumuler 500 squats sur la semaine, avec ou sans charge.', ['Environ 70 par jour en 3 séries.', 'Ajoute du poids quand c’est facile.'], 'c:500:squats', ['sans matériel', 'sport']],
  ['high', 'SM', 'Gainage, 25 planches', 'Un gainage régulier sculpte un tronc stable et résistant.', 'Tenir 25 planches sur la période, de 30 secondes à 1 minute chacune.', ['Note chaque planche pour suivre ton total.', 'Varie face, côtés et dos.'], 'c:25:planches', ['sans matériel', 'sport']],
  ['high', 'S', 'Portage lourd, 5 sorties', 'Travailler la force fonctionnelle, c’est porter lourd, sur une vraie distance.', 'Faire 5 portages de charge lourde dans la semaine : sacs, packs, bidons ou valises, sur au moins 200 mètres chacun.', ['Charge à 60 % de ce que tu peux porter.', 'Repose-toi dès que ton dos s’arrondit.'], 'c:5:portages', ['extérieur', 'sport']],
  ['high', 'M', 'Pompes, 1 000 dans le mois', 'Mille pompes en un mois, c’est environ 35 par jour : un défi classique, et très accessible.', 'Cumuler 1 000 pompes sur le mois, en autant de séries que nécessaire.', ['Planifie 35 pompes par jour, ou 50 un jour sur deux.', 'Ajoute tes pompes après chaque série.'], 'c:1000:pompes', ['sans matériel', 'sport']],
  ['high', 'M', 'Séances de force, 12 dans le mois', 'Douze séances par mois, c’est trois par semaine : un rythme durable.', 'Faire 12 séances de renforcement musculaire sur le mois.', ['Planifie trois créneaux fixes par semaine.', 'Alterne séances courtes et longues.'], 'c:12:séances', ['sport']],
  ['high', 'M', 'Tirages, 150 dans le mois', 'Un bon équilibre entre pousser et tirer protège les épaules.', 'Cumuler 150 tirages (tractions, rowing, élastique) sur le mois.', ['Environ 5 par jour, ou 15 trois fois par semaine.', 'Contrôle la descente à chaque répétition.'], 'c:150:tirages', ['sport']],
  // ── Légendaires (5)
  ['expert', 'M', 'Pompes, 2 000 dans le mois', 'Deux mille pompes en un mois : un vrai défi de constance.', 'Cumuler 2 000 pompes sur le mois, soit environ 70 par jour. Adapte à ta condition et consulte un professionnel au besoin.', ['Fais 3 à 4 séries réparties dans la journée.', 'Garde au moins un jour de repos par semaine.'], 'c:2000:pompes', ['sans matériel', 'sport']],
  ['expert', 'ME', 'Record de pompes à battre', 'Mesurer, s’entraîner, puis mesurer encore : la forme la plus honnête de progression.', 'Mesurer ton maximum de pompes d’affilée, t’entraîner 4 semaines, puis refaire le test et améliorer ton record. Adapte à ta condition.', ['Note ton record de départ sur papier.', 'Entraîne-toi 3 fois par semaine avec des séries sous ton maximum.'], 'e:Mesurer mon maximum de pompes d’affilée|S’entraîner pendant 4 semaines|Refaire le test et battre mon record', ['sans matériel', 'sport']],
  ['expert', 'SM', 'Séances de force, 20 au total', 'Vingt séances de force cumulées demandent de la discipline sur la durée.', 'Faire 20 séances de renforcement musculaire sur la période. Adapte à ta condition et à ton niveau de récupération.', ['Prévois des créneaux fixes dans ton agenda.', 'Alterne les groupes musculaires.'], 'c:20:séances', ['sport']],
  ['expert', 'ME', 'Squats, 5 000 au total', 'Cinq mille squats : un grand cycle de jambes, du premier jour au dernier.', 'Cumuler 5 000 squats, avec ou sans charge, sur la durée. Adapte à ta condition et consulte un professionnel au besoin.', ['Environ 150 par jour pendant un peu plus d’un mois.', 'Ajoute du poids progressivement.'], 'c:5000:squats', ['sans matériel', 'sport']],
  ['expert', 'M', 'Force, 16 séances dans le mois', 'Seize séances de force dans le mois, c’est quatre par semaine sans exception.', 'Faire 16 séances de renforcement musculaire sur le mois. Adapte à ta condition et garde deux jours de repos par semaine.', ['Planifie tes séances dans ton agenda.', 'Alterne séances lourdes et séances légères.'], 'c:16:séances', ['sport']],
];
