// SAG — Sagesse : prendre soin de soi à l’intérieur. Calme, émotions, attention, silence, retour sur sa journée.
// [difficulté, périodes (J/S/M/E), titre, ambiance (pourquoi), objectif, [conseils], validation, [tags]]
// validation : s | c:cible:unité | t:minutes | e:étape1|étape2 | j
export default [
  // ── Faciles (14)
  ['easy', 'J', 'Respiration calme, 5 minutes', 'Respirer lentement active le système nerveux qui apaise le corps.', 'Pendant 5 minutes, respirer lentement : inspirer 4 secondes, expirer 6 secondes, assis ou allongé.', ['Pose une main sur le ventre.', 'Si ton esprit part, reviens simplement à la respiration.'], 't:5', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Méditation, 10 minutes', 'Dix minutes de méditation entraînent la capacité à rester présent.', 'Méditer 10 minutes, assis, en portant l’attention sur la respiration, avec ou sans guidage.', ['Utilise une application guidée au début.', 'Revenir à la respiration cent fois, c’est la pratique.'], 't:10', ['sans matériel']],
  ['easy', 'J', 'Journal du soir, 10 minutes', 'Écrire fait redescendre les tensions et aide à voir clair dans sa journée.', 'Pendant 10 minutes, écrire dans un carnet ce qui s’est passé aujourd’hui et ce que tu as ressenti.', ['Écris sans te corriger.', 'Quelques phrases suffisent.'], 't:10', ['moins de 10 min']],
  ['easy', 'J', 'Gratitude, 5 minutes', 'Chercher le positif entraîne l’attention vers ce qui va bien.', 'Pendant 5 minutes, noter trois choses précises pour lesquelles tu es reconnaissant aujourd’hui, et pourquoi.', ['Sois concret : un geste, une personne, un moment.', 'Évite de répéter celles d’hier.'], 't:5', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Balayage corporel, 5 minutes', 'Repérer les tensions est le premier pas pour les relâcher.', 'Pendant 5 minutes, parcourir mentalement ton corps des pieds à la tête, en relâchant chaque zone.', ['Allonge-toi si possible.', 'Respire plus lentement sur chaque zone tendue.'], 't:5', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Silence sans écran, 10 minutes', 'Le silence laisse l’esprit retomber après une journée de sollicitations.', 'Rester 10 minutes dans le silence, sans écran, sans musique, sans lecture, assis ou en marchant lentement.', ['Éteins le téléphone ou mets-le dans une autre pièce.', 'Regarde par la fenêtre.'], 't:10', ['détox', 'sans matériel']],
  ['easy', 'J', 'Promenade attentive, 15 minutes', 'Marcher en observant calme l’esprit mieux qu’une marche pressée.', 'Marcher 15 minutes sans écran ni écouteurs, en remarquant ce que tu vois, entends et sens.', ['Choisis un chemin calme.', 'Compte cinq choses que tu n’avais jamais remarquées.'], 't:15', ['extérieur', 'nature']],
  ['easy', 'J', 'Cohérence cardiaque, 5 minutes', 'Respirer à ce rythme régulier apaise le rythme cardiaque et l’anxiété.', 'Pendant 5 minutes, respirer au rythme de 6 respirations par minute : 5 secondes pour inspirer, 5 secondes pour expirer.', ['Utilise un minuteur ou une application dédiée.', 'Respire par le nez.'], 't:5', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Nommer ses émotions, 5 minutes', 'Mettre un mot sur une émotion réduit son intensité.', 'Pendant 5 minutes, repérer ce que tu ressens maintenant, le nommer précisément et noter ce qui l’a provoqué.', ['Sois précis : agacé, inquiet, fatigué, déçu.', 'Accepte l’émotion sans la juger.'], 't:5', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Rituel du soir apaisant, 10 minutes', 'Un rituel court prépare le corps et l’esprit au repos.', 'Pendant 10 minutes avant de dormir, enchaîner des gestes calmes : lumière douce, étirements lents, lecture légère.', ['Garde le même ordre chaque soir.', 'Évite les écrans pendant ce temps.'], 't:10', ['sommeil', 'détox']],
  ['easy', 'J', 'Temps pour soi, 15 minutes', 'Prendre du temps pour soi n’est pas un luxe, c’est de l’entretien.', 'Prendre 15 minutes pour une activité calme et personnelle, sans obligation : thé, musique douce, lecture, dessin.', ['Planifie-les dans ton agenda.', 'Éloigne-toi des sollicitations.'], 't:15', ['sans matériel']],
  ['easy', 'J', 'Relaxation musculaire, 10 minutes', 'Contracter puis relâcher chaque groupe de muscles fait baisser la tension.', 'Pendant 10 minutes, contracter puis relâcher successivement chaque groupe musculaire, des pieds à la tête.', ['Contracte 5 secondes, relâche 10 secondes.', 'Respire lentement entre les groupes.'], 't:10', ['sans matériel']],
  ['easy', 'J', 'Bilan de journée, 5 minutes', 'Un retour sur la journée transforme l’expérience en apprentissage.', 'Pendant 5 minutes, noter ce qui s’est bien passé, ce qui a été difficile et une chose à faire autrement demain.', ['Trois lignes suffisent.', 'Sois bienveillant avec toi-même.'], 't:5', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Une seule chose, 10 minutes', 'Faire une seule chose à la fois entraîne l’attention.', 'Pendant 10 minutes, faire une seule tâche (vaisselle, marche, repas) en y portant toute ton attention, sans autre activité.', ['Pas de téléphone, pas de musique.', 'Remarque les gestes, les odeurs, les textures.'], 't:10', ['sans matériel']],
  // ── Modérées (12)
  ['medium', 'JS', 'Méditation, 15 minutes', 'Quinze minutes permettent de dépasser l’agitation du début de séance.', 'Méditer 15 minutes, assis, en portant l’attention sur la respiration.', ['Utilise une méditation guidée si tu débutes.', 'Installe-toi à la même heure.'], 't:15', ['sans matériel']],
  ['medium', 'JS', 'Journal, 15 minutes', 'Une écriture libre régulière aide à comprendre ses pensées.', 'Écrire pendant 15 minutes sur ta journée, tes émotions ou une question qui te préoccupe.', ['Écris sans te relire.', 'Termine par une phrase de décision.'], 't:15', ['sans matériel']],
  ['medium', 'J', 'Nature sans écran, 30 minutes', 'Le contact avec la nature réduit le stress mesurable en quelques minutes.', 'Passer 30 minutes dans un parc, une forêt ou au bord de l’eau, sans écran.', ['Laisse ton téléphone en mode avion.', 'Assieds-toi quelques minutes et observe.'], 't:30', ['extérieur', 'nature', 'détox']],
  ['medium', 'S', 'Méditation, 60 minutes dans la semaine', 'Une pratique régulière compte plus qu’une longue séance isolée.', 'Cumuler 60 minutes de méditation ou de respiration guidée sur la semaine.', ['Dix minutes par jour, six jours sur sept.', 'Ajoute les minutes après chaque séance.'], 'c:60:minutes', ['sans matériel']],
  ['medium', 'JS', 'Une heure sans écran', 'Une heure déconnectée laisse la place à autre chose que les notifications.', 'Passer 60 minutes sans écran de loisir (téléphone, télévision, jeux) et faire autre chose à la place.', ['Prévois une activité de remplacement.', 'Mets le téléphone dans une autre pièce.'], 't:60', ['détox']],
  ['medium', 'S', 'Journal, 60 minutes dans la semaine', 'Écrire régulièrement aide à repérer ses schémas et ses progrès.', 'Cumuler 60 minutes d’écriture dans un journal sur la semaine.', ['Dix minutes chaque soir.', 'Relis la semaine à la fin.'], 'c:60:minutes', ['sans matériel']],
  ['medium', 'JS', 'Relaxation et respiration, 20 minutes', 'Un temps de détente plus long détend vraiment le corps.', 'Pendant 20 minutes, enchaîner respiration profonde, détente musculaire et visualisation calme.', ['Choisis un endroit où personne ne te dérange.', 'Mets une alarme douce.'], 't:20', ['sans matériel']],
  ['medium', 'J', 'Silence et solitude, 25 minutes', 'Être seul avec ses pensées, sans distraction, apprend à les connaître.', 'Passer 25 minutes seul avec toi-même : sans écran, sans musique, sans activité. Juste être là.', ['Assieds-toi confortablement.', 'Laisse les pensées passer sans les suivre.'], 't:25', ['détox', 'sans matériel']],
  ['medium', 'S', 'Temps pour soi, 120 minutes', 'Deux heures par semaine de temps réservé à soi font déjà une différence.', 'Cumuler 120 minutes de temps pour toi sur la semaine : activité calme, passion, repos, sans obligation.', ['Réserve les créneaux dans ton agenda.', 'Protège-les comme un rendez-vous.'], 'c:120:minutes', ['sans matériel']],
  ['medium', 'JS', 'Écriture libre, 20 minutes', 'Écrire sans filtre laisse sortir ce qui encombre l’esprit.', 'Écrire 20 minutes sans t’arrêter ni te corriger, sur ce qui te traverse l’esprit.', ['Si tu bloques, écris « je ne sais pas quoi écrire » jusqu’à ce que ça vienne.', 'Ne relis pas tout de suite.'], 't:20', ['sans matériel']],
  ['medium', 'S', 'Nature, 90 minutes dans la semaine', 'Quatre-vingt-dix minutes de nature par semaine améliorent l’humeur et le stress.', 'Cumuler 90 minutes dans la nature, sans écran, sur la semaine : parc, forêt, bord de rivière, jardin.', ['Plusieurs sorties courtes comptent aussi.', 'Pose ton téléphone dans ta poche.'], 'c:90:minutes', ['extérieur', 'nature']],
  ['medium', 'J', 'Bilan approfondi, 20 minutes', 'Un bilan plus long aide à prendre du recul sur ce qui compte.', 'Pendant 20 minutes, faire le bilan écrit de ta semaine ou de ta journée : réussites, difficultés, leçons, décisions.', ['Pose trois questions et réponds-y.', 'Termine par une intention pour demain.'], 't:20', ['sans matériel']],
  // ── Audacieuses (9)
  ['high', 'S', 'Méditation, 105 minutes dans la semaine', 'Quinze minutes par jour installent une pratique durable.', 'Cumuler 105 minutes de méditation sur la semaine, soit 15 minutes par jour en moyenne.', ['Médite à la même heure chaque jour.', 'Utilise une application pour ne pas décrocher.'], 'c:105:minutes', ['sans matériel']],
  ['high', 'S', 'Journal, 120 minutes dans la semaine', 'Deux heures d’écriture par semaine permettent un vrai travail sur soi.', 'Cumuler 120 minutes d’écriture réflexive sur la semaine : journal, bilan, lettres que tu n’enverras pas.', ['Alterne écriture libre et bilan structuré.', 'Relis-toi le dimanche.'], 'c:120:minutes', ['sans matériel']],
  ['high', 'JS', 'Méditation longue, 30 minutes', 'Une séance longue approfondit la concentration et la détente.', 'Méditer 30 minutes d’affilée, assis, sans interruption.', ['Commence par 5 minutes de respiration profonde.', 'Accepte les moments d’agitation.'], 't:30', ['sans matériel']],
  ['high', 'S', 'Nature, 180 minutes dans la semaine', 'Trois heures de nature par semaine changent la perception du stress.', 'Cumuler 180 minutes dans la nature, sans écran, sur la semaine.', ['Une sortie longue le week-end.', 'Pose ton téléphone dans ton sac.'], 'c:180:minutes', ['extérieur', 'nature']],
  ['high', 'SM', 'Déconnexion, 5 heures sans écran', 'Cinq heures hors écran de loisir sont un vrai reset.', 'Cumuler 5 heures sans écran de loisir sur la période, en les passant à autre chose : balade, lecture, repos, activité manuelle.', ['Choisis des plages fixes.', 'Prévois une activité pour ne pas te remettre sur ton téléphone.'], 'c:300:minutes', ['détox']],
  ['high', 'S', 'Silence et solitude, 120 minutes', 'Passer du temps seul avec soi-même apprend à se connaître.', 'Cumuler 120 minutes de silence et de solitude sur la semaine, sans écran ni musique.', ['Plusieurs séances de 20 à 30 minutes.', 'Marche ou assieds-toi sans rien faire.'], 'c:120:minutes', ['détox']],
  ['high', 'M', 'Méditation, 8 heures dans le mois', 'Huit heures de méditation, c’est environ 16 minutes par jour.', 'Cumuler 8 heures de méditation ou de pleine conscience sur le mois.', ['Pratique chaque matin ou chaque soir.', 'Garde un suivi simple.'], 'c:480:minutes', ['sans matériel']],
  ['high', 'M', 'Journal, 6 heures dans le mois', 'Six heures d’écriture sur un mois donnent un vrai recul sur sa vie.', 'Cumuler 6 heures d’écriture réflexive sur le mois.', ['Dix à quinze minutes par jour.', 'Relis ton mois à la fin.'], 'c:360:minutes', ['sans matériel']],
  ['high', 'M', 'Temps pour soi, 12 heures', 'Douze heures par mois, c’est environ 25 minutes par jour de temps personnel.', 'Cumuler 12 heures de temps pour toi sur le mois : activité calme, passion personnelle, repos conscient.', ['Réserve tes créneaux à l’avance.', 'Dis non aux sollicitations sur ces créneaux.'], 'c:720:minutes', ['sans matériel']],
  // ── Légendaires (5)
  ['expert', 'M', 'Méditation, 30 jours de suite', 'Trente jours de pratique installent un vrai rendez-vous quotidien avec soi.', 'Méditer au moins 10 minutes par jour pendant 30 jours dans le mois.', ['Choisis un horaire qui ne bouge pas.', 'Si tu rates un jour, reprends le lendemain.'], 'c:30:jours', ['sans matériel']],
  ['expert', 'ME', 'Pratique intérieure, 30 heures', 'Trente heures de méditation, de journal ou de silence approfondissent durablement le rapport à soi.', 'Cumuler 30 heures de pratiques intérieures : méditation, écriture réflexive, silence, respiration.', ['Fixe une pratique quotidienne légère.', 'Note ce qui change après quelques semaines.'], 'c:1800:minutes', ['sans matériel']],
  ['expert', 'SM', 'Retraite numérique, 12 heures', 'Douze heures hors écran de loisir, c’est une journée presque complète de déconnexion.', 'Cumuler 12 heures sans écran de loisir sur la période, hors travail et besoins utiles, à consacrer à autre chose.', ['Prévois une journée ou deux demi-journées.', 'Prépare des activités à l’avance.'], 'c:720:minutes', ['détox']],
  ['expert', 'ME', 'Journal, 25 heures d’écriture', 'Vingt-cinq heures d’écriture réflexive forment un travail de fond sur soi.', 'Cumuler 25 heures d’écriture réflexive : journal, bilans, lettres, retours sur ton parcours.', ['Garde un carnet unique.', 'Relis-le tous les mois.'], 'c:1500:minutes', ['sans matériel']],
  ['expert', 'M', 'Un mois de calme, 15 heures', 'Quinze heures de pratiques calmes dans le mois changent la façon de réagir au stress.', 'Cumuler 15 heures de pratiques calmes sur le mois : méditation, respiration, silence, nature sans écran, journal.', ['Planifie une pratique quotidienne de 30 minutes.', 'Varie les formes pour tenir.'], 'c:900:minutes', ['sans matériel']],
];
