// FOR — Force : le physique pur. Pousser, tirer, porter, tenir. Les quêtes se jugent au temps d’effort.
// [difficulté, périodes (J/S/M/E), titre, ambiance (pourquoi), objectif, [conseils], validation, [tags]]
// validation : s | c:cible:unité | t:minutes | e:étape1|étape2 | j
export default [
  // ── Faciles (14)
  ['easy', 'J', 'Pompes en séries, 5 minutes', 'Les pompes travaillent pectoraux, épaules et triceps sans aucun matériel.', 'Pendant 5 minutes, enchaîner des séries de pompes (sur les genoux autorisé) avec un repos libre entre les séries.', ['Mieux vaut des séries propres que des répétitions bâclées.', 'Expire en poussant, inspire en descendant.'], 't:5', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Squats en séries, 5 minutes', 'Les cuisses et les fessiers sont les plus gros muscles du corps : on les sollicite en premier.', 'Pendant 5 minutes, enchaîner des séries de squats, dos droit et talons au sol.', ['Imagine que tu t’assois sur une chaise derrière toi.', 'Descends moins bas si tes genoux tirent.'], 't:5', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Gainage, 5 minutes au total', 'Un tronc solide protège le dos et rend tous les autres efforts plus faciles.', 'Tenir des planches (face et côtés) pendant 5 minutes en tout, repos compris, en une ou plusieurs séries.', ['Coudes sous les épaules, corps aligné.', 'Fractionne en séries de 20 à 30 secondes si besoin.'], 't:5', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Fentes alternées, 5 minutes', 'Les fentes renforcent chaque jambe séparément et corrigent les déséquilibres.', 'Pendant 5 minutes, enchaîner des fentes avant ou arrière en alternant les jambes.', ['Garde le buste droit et le genou avant au-dessus du pied.', 'Tiens-toi à un mur au début si tu perds l’équilibre.'], 't:5', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Chaise murale, 3 minutes cumulées', 'Tenir une position statique fatigue les cuisses plus qu’on ne le croit.', 'Tenir la position de la chaise contre un mur pendant 3 minutes cumulées, en plusieurs fois si nécessaire.', ['Cuisses à l’horizontale, dos plaqué au mur.', 'Commence par des tenues de 20 secondes.'], 't:3', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Dips sur chaise, 5 minutes', 'Les triceps font la moitié du travail de poussée du haut du corps.', 'Pendant 5 minutes, enchaîner des séries de dips sur une chaise stable, repos libre entre les séries.', ['Cale la chaise contre un mur pour qu’elle ne glisse pas.', 'Garde les épaules loin des oreilles.'], 't:5', ['moins de 10 min', 'sport']],
  ['easy', 'J', 'Abdominaux, 5 minutes', 'Les abdominaux stabilisent le tronc dans presque tous les mouvements de force.', 'Pendant 5 minutes, alterner abdominaux, relevés de jambes et crunchs en séries courtes.', ['Mains près des tempes, sans tirer sur la nuque.', 'Souffle pendant l’effort.'], 't:5', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Portage avec charge, 5 minutes', 'Porter du poids sollicite tout le corps, comme dans la vraie vie.', 'Marcher pendant 5 minutes en portant une charge : sac chargé de livres, packs d’eau ou courses.', ['Garde le dos droit et la charge près du corps.', 'Change de main ou de côté à mi-parcours.'], 't:5', ['moins de 10 min', 'sport']],
  ['easy', 'J', 'Pont fessier, 5 minutes', 'Des fessiers forts soulagent le bas du dos et stabilisent le bassin.', 'Pendant 5 minutes, enchaîner des séries de ponts fessiers, en marquant une pause d’une seconde en haut.', ['Pousse avec les talons, pas avec les orteils.', 'Passe sur une jambe quand c’est facile.'], 't:5', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Poigne et avant-bras, 5 minutes', 'La poigne limite beaucoup d’exercices de tirage : c’est un point faible fréquent.', 'Pendant 5 minutes, travailler la poigne : serrer une balle, suspendre à une barre ou porter une charge à bout de bras.', ['Alterne les mains et laisse 30 secondes de repos entre les séries.', 'Une serviette roulée peut servir de balle.'], 't:5', ['moins de 10 min', 'sport']],
  ['easy', 'J', 'Circuit corps entier, 10 minutes', 'Un circuit court sollicite tous les groupes musculaires en peu de temps.', 'Pendant 10 minutes, enchaîner pompes, squats, gainage et fentes, un exercice après l’autre, sans pause longue.', ['Fais 30 secondes par exercice puis passe au suivant.', 'Reprends ton souffle entre les tours.'], 't:10', ['sans matériel', 'sport']],
  ['easy', 'J', 'Gainage latéral, 4 minutes au total', 'Les muscles latéraux du tronc protègent la colonne dans les efforts de portage.', 'Tenir le gainage latéral pendant 4 minutes cumulées, soit 2 minutes de chaque côté, en plusieurs séries.', ['Coude sous l’épaule, hanches hautes.', 'Séries de 15 à 30 secondes selon ta forme.'], 't:4', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Soulevé de charge, 10 minutes', 'Savoir soulever correctement protège le dos pour tous les jours qui viennent.', 'Pendant 10 minutes, enchaîner des séries de soulevés de charge (sac lesté, bidon d’eau) en gardant le dos droit.', ['Fléchis les genoux, ne plie pas le dos.', 'Garde la charge collée contre toi.'], 't:10', ['sport']],
  ['easy', 'J', 'Tirage et rowing, 5 minutes', 'Le dos fait contrepoids à tout ce qu’on pousse : il se travaille aussi.', 'Pendant 5 minutes, enchaîner des séries de rowing avec un élastique, un sac chargé ou une table solide.', ['Tire les coudes vers l’arrière, pas les épaules vers les oreilles.', 'Contrôle la descente.'], 't:5', ['moins de 10 min', 'sport']],
  // ── Modérées (12)
  ['medium', 'JS', 'Haut du corps, 20 minutes', 'Une séance structurée progresse plus vite qu’une série isolée.', 'Pendant 20 minutes, enchaîner pompes, dips, rowing et gainage en séries de 8 à 15 répétitions.', ['Note le nombre de répétitions pour progresser la fois suivante.', 'Repos de 45 à 60 secondes entre les séries.'], 't:20', ['sport']],
  ['medium', 'JS', 'Bas du corps, 20 minutes', 'Un bas du corps solide aide à marcher, monter et se relever toute la vie.', 'Pendant 20 minutes, enchaîner squats, fentes, ponts fessiers et montées sur marche en séries de 10 à 15 répétitions.', ['Descends en contrôle, remonte avec force.', 'Garde les genoux dans l’axe des pieds.'], 't:20', ['sport']],
  ['medium', 'S', 'Renforcement, 60 minutes dans la semaine', 'Deux ou trois courtes séances par semaine suffisent à progresser en force.', 'Cumuler 60 minutes de renforcement musculaire sur la semaine, en plusieurs séances.', ['Répartis sur 2 ou 3 jours avec un jour de repos entre.', 'Ajoute les minutes après chaque séance.'], 'c:60:minutes', ['sport']],
  ['medium', 'J', 'Circuit corps entier, 25 minutes', 'Un circuit complet fait travailler force et endurance musculaire à la fois.', 'Pendant 25 minutes, enchaîner un circuit de 6 exercices (pompes, squats, gainage, fentes, rowing, abdos) en plusieurs tours.', ['40 secondes d’effort, 20 secondes de repos.', 'Prépare l’ordre des exercices avant de commencer.'], 't:25', ['sport']],
  ['medium', 'JS', 'Gainage varié, 10 minutes', 'Plusieurs variantes de gainage sollicitent tout le tronc, pas seulement le ventre.', 'Pendant 10 minutes, enchaîner planche, planche latérale et planche dos, en séries de 30 à 45 secondes.', ['Garde le corps aligné, sans cambrer.', 'Repose-toi dès que la forme se dégrade.'], 't:10', ['sans matériel', 'sport']],
  ['medium', 'S', 'Portage de charges, 30 minutes', 'Porter, c’est la force utile : courses, valises, enfants, déménagement.', 'Cumuler 30 minutes de portage sur la semaine : marche avec sac lesté, courses à pied ou charge à bout de bras.', ['Commence léger et ajoute du poids semaine après semaine.', 'Garde le dos droit.'], 'c:30:minutes', ['extérieur', 'sport']],
  ['medium', 'JS', 'Pompes variées, 15 minutes', 'Changer de variante de pompe travaille d’autres fibres et évite le plateau.', 'Pendant 15 minutes, alterner pompes classiques, serrées, surélevées et lentes en séries de 6 à 12.', ['Passe à la variante plus facile quand la forme baisse.', 'Descends en 3 secondes pour plus d’effet.'], 't:15', ['sans matériel', 'sport']],
  ['medium', 'J', 'Squats lestés, 15 minutes', 'Ajouter du poids est la façon la plus directe de gagner de la force.', 'Pendant 15 minutes, enchaîner des squats avec un sac à dos chargé ou un poids dans les bras.', ['Charge assez pour que 10 répétitions soient exigeantes.', 'Garde le sac collé au dos.'], 't:15', ['sport']],
  ['medium', 'S', 'Haltères ou élastiques, 90 minutes', 'Un travail avec charge, régulier, construit la force sur la durée.', 'Cumuler 90 minutes de travail avec haltères, élastiques ou machines sur la semaine.', ['Trois séances de 30 minutes font l’affaire.', 'Varie les groupes musculaires d’une séance à l’autre.'], 'c:90:minutes', ['sport']],
  ['medium', 'JS', 'Séance haut et bas, 30 minutes', 'Une séance mixte progresse bien quand on manque de temps.', 'Pendant 30 minutes, alterner des exercices de haut du corps et de bas du corps, en séries de 8 à 12 répétitions.', ['Alterne pour reposer chaque groupe pendant que l’autre travaille.', 'Écris la séance à l’avance.'], 't:30', ['sport']],
  ['medium', 'S', 'Travail de tirage, 40 minutes', 'Tractions, rowings et tirages équilibrent les muscles de la poussée et protègent les épaules.', 'Cumuler 40 minutes d’exercices de tirage sur la semaine : tractions, rowing, élastiques.', ['Une barre de porte ou une table solide suffit.', 'Aide-toi d’un élastique pour les tractions.'], 'c:40:minutes', ['sport']],
  ['medium', 'JS', 'Séance de force complète, 30 minutes', 'Une vraie séance de force, échauffement inclus, ancre l’habitude.', 'Faire une séance de force de 30 minutes : 5 minutes d’échauffement puis 25 minutes d’exercices variés.', ['Échauffe-toi avec du mouvement léger.', 'Termine par 2 minutes d’étirements.'], 't:30', ['sport']],
  // ── Audacieuses (9)
  ['high', 'S', 'Force, 120 minutes dans la semaine', 'Quatre séances de force par semaine font franchir un palier visible.', 'Cumuler 120 minutes de renforcement ou de musculation sur la semaine.', ['Prévois quatre créneaux de 30 minutes.', 'Garde un jour de repos complet.'], 'c:120:minutes', ['sport']],
  ['high', 'S', 'Pompes et dips, 45 minutes', 'Un volume régulier de poussée développe la force du haut du corps.', 'Cumuler 45 minutes de travail de poussée (pompes, dips, développés) sur la semaine.', ['Répartis sur 3 séances de 15 minutes.', 'Augmente d’une répétition à chaque séance.'], 'c:45:minutes', ['sport']],
  ['high', 'JS', 'Séance de force intense, 45 minutes', 'Un format long permet de travailler plus de volume et de charge.', 'Pendant 45 minutes, faire une séance de force complète avec charge, échauffement et retour au calme inclus.', ['Planifie 5 exercices et 3 séries chacun.', 'Hydrate-toi pendant les repos.'], 't:45', ['sport']],
  ['high', 'S', 'Jambes et fessiers, 60 minutes', 'Le bas du corps est le plus gros réservoir de force du corps.', 'Cumuler 60 minutes de travail des jambes et des fessiers sur la semaine : squats, fentes, ponts, montées de marche.', ['Deux séances de 30 minutes.', 'Descends lentement, remonte avec puissance.'], 'c:60:minutes', ['sport']],
  ['high', 'SM', 'Gainage, 30 minutes cumulées', 'Un gainage long et régulier sculpte un tronc stable et résistant.', 'Cumuler 30 minutes de gainage sur la période, en séries de 30 secondes à 2 minutes.', ['Note chaque série pour suivre ton total.', 'Varie face, côtés et dos.'], 'c:30:minutes', ['sans matériel', 'sport']],
  ['high', 'S', 'Portage lourd, 45 minutes', 'Travailler la force fonctionnelle, c’est porter lourd, longtemps.', 'Cumuler 45 minutes de portage de charges lourdes sur la semaine : sacs, packs, bidons, valises.', ['Charge à 60 % de ce que tu peux porter.', 'Repose-toi dès que ton dos s’arrondit.'], 'c:45:minutes', ['extérieur', 'sport']],
  ['high', 'M', 'Force, 6 heures dans le mois', 'Six heures de force par mois, c’est environ 90 minutes par semaine.', 'Cumuler 6 heures de renforcement musculaire sur le mois.', ['Planifie 3 séances par semaine.', 'Les minutes d’échauffement comptent.'], 'c:360:minutes', ['sport']],
  ['high', 'M', 'Poussée et tirage, 4 heures', 'Un bon équilibre entre pousser et tirer protège les épaules.', 'Cumuler 4 heures de travail de poussée et de tirage sur le mois, à parts à peu près égales.', ['Alterne les séances poussée et tirage.', 'Garde un cahier de répétitions.'], 'c:240:minutes', ['sport']],
  ['high', 'M', 'Corps entier, 5 heures dans le mois', 'Un volume mensuel régulier est ce qui change vraiment le corps.', 'Cumuler 5 heures de séances de force corps entier sur le mois.', ['Quatre séances par semaine de 20 minutes suffisent.', 'Mesure ta progression à la fin du mois.'], 'c:300:minutes', ['sport']],
  // ── Légendaires (5)
  ['expert', 'M', 'Force, 12 heures dans le mois', 'Douze heures de force par mois : un vrai engagement d’entraînement.', 'Cumuler 12 heures de renforcement musculaire sur le mois. Adapte à ta condition et consulte un professionnel au besoin.', ['Planifie tes séances dans ton agenda.', 'Garde au moins deux jours de repos par semaine.'], 'c:720:minutes', ['sport']],
  ['expert', 'ME', 'Force, 20 heures de travail', 'Vingt heures de force cumulées demandent de la constance sur la durée.', 'Cumuler 20 heures de renforcement musculaire en visant un objectif de progression mesurable. Adapte à ta condition.', ['Fixe un objectif précis (nombre de pompes, charge) au départ.', 'Mesure-toi au début et à la fin.'], 'c:1200:minutes', ['sport']],
  ['expert', 'SM', 'Séances de force, 5 heures', 'Cinq heures de force dans la période demandent une vraie discipline.', 'Cumuler 5 heures de séances de force sur la période. Adapte à ta condition et à ton niveau de récupération.', ['Prévois des créneaux fixes.', 'Alterne les groupes musculaires.'], 'c:300:minutes', ['sport']],
  ['expert', 'ME', 'Progression de force, 25 heures', 'Un grand cycle de force, du premier jour à la mesure finale.', 'Suivre un cycle d’entraînement de force de 25 heures en tout, avec une mesure de départ et une mesure d’arrivée. Adapte à ta condition.', ['Teste-toi avant (pompes maximum, gainage maximum).', 'Programme plusieurs semaines pour récupérer correctement.'], 'c:1500:minutes', ['sport']],
  ['expert', 'M', 'Force et portage, 15 heures', 'Un mois de force utile : renforcement, portage et gainage.', 'Cumuler 15 heures de renforcement, portage de charges et gainage sur le mois. Adapte à ta condition.', ['Reste à l’écoute de tes articulations.', 'Alterne séances lourdes et séances légères.'], 'c:900:minutes', ['sport']],
];
