// CON — Constitution : la santé du corps. Heure de coucher et de lever, repas, hydratation, marche, endurance, récupération.
// [difficulté, périodes (J/S/M/E), titre, ambiance (pourquoi), objectif, [conseils], validation, [tags]]
// validation : s | c:cible:unité | t:minutes | e:étape1|étape2 | j
export default [
  // ── Faciles (14)
  ['easy', 'J', 'Marche, 15 minutes', 'Marcher un quart d’heure par jour est le geste de santé le plus simple et le plus efficace.', 'Marcher 15 minutes, dehors si possible, à un rythme soutenu, d’une traite ou en plusieurs fois.', ['Un peu d’air, sans écran.', 'Tu peux les répartir en deux sorties de 8 minutes.'], 't:15', ['extérieur', 'sport']],
  ['easy', 'J', 'Coucher avant 23 heures', 'Se coucher tôt allonge le sommeil et améliore l’énergie du lendemain.', 'Être couché, lumière éteinte, avant 23 heures ce soir.', ['Prépare tes affaires du lendemain avant 22 h.', 'Mets une alarme de rappel une heure avant.'], 's', ['sommeil']],
  ['easy', 'J', 'Écrans coupés avant dormir', 'La lumière bleue retarde l’endormissement : couper les écrans aide à s’endormir.', 'Éteindre tous les écrans (téléphone, télévision, ordinateur) avant de dormir, le plus tôt possible dans la soirée.', ['Prépare une lecture ou une musique douce.', 'Mets le téléphone à charger hors de la chambre.'], 's', ['sommeil', 'détox']],
  ['easy', 'J', 'Un repas équilibré', 'Un repas équilibré stabilise l’énergie et évite les fringales.', 'Prendre un repas avec une protéine, un légume et un féculent.', ['Œufs, poisson, volaille ou légumineuses pour la protéine.', 'Remplis la moitié de l’assiette de légumes.'], 's', ['alimentation']],
  ['easy', 'J', 'Marche après le repas, 10 minutes', 'Dix minutes de marche après manger facilitent la digestion et stabilisent la glycémie.', 'Marcher 10 minutes juste après le déjeuner ou le dîner, à un rythme tranquille.', ['Dehors de préférence.', 'Un tour du quartier suffit.'], 't:10', ['extérieur', 'moins de 10 min']],
  ['easy', 'J', 'Régler le réveil de demain', 'Un réveil à heure fixe se prépare la veille : c’est ce soir que ça se joue.', 'Ce soir, choisir l’heure de lever de demain, régler le réveil et te coucher en conséquence.', ['Choisis une heure réaliste, la même chaque jour.', 'Pose le réveil loin du lit pour devoir te lever.'], 's', ['sommeil']],
  ['easy', 'J', 'Six verres d’eau', 'Boire régulièrement évite les maux de tête et la fatigue de milieu d’après-midi.', 'Boire 6 verres d’eau dans la journée : au réveil, à chaque repas et en fin d’après-midi.', ['Garde une gourde à portée de main.', 'Ajoute du citron ou de la menthe si tu trouves l’eau fade.'], 'c:6:verres', ['alimentation']],
  ['easy', 'J', 'Cuisiner un repas maison', 'Cuisiner soi-même permet de maîtriser le sel, le sucre et les matières grasses.', 'Cuisiner un plat maison avec des légumes plutôt que de commander ou réchauffer.', ['Une soupe ou une poêlée suffisent.', 'Fais-en un peu plus pour le lendemain.'], 's', ['alimentation', 'cuisine']],
  ['easy', 'J', 'Repas assis, sans écran', 'Manger lentement, sans écran, aide à reconnaître la satiété.', 'Prendre un repas assis, sans écran, en mâchant lentement.', ['Pose tes couverts entre les bouchées.', 'Mâche lentement.'], 's', ['alimentation', 'détox']],
  ['easy', 'J', 'Cinq portions de fruits et légumes', 'Cinq portions par jour, c’est la recommandation de santé la plus connue, et elle est atteignable.', 'Manger 5 portions de fruits et de légumes dans la journée.', ['Un fruit au petit-déjeuner, des crudités et un légume cuit au déjeuner et au dîner.', 'Une portion, c’est environ une poignée.'], 'c:5:portions', ['alimentation']],
  ['easy', 'J', 'Zéro boisson sucrée', 'Supprimer les boissons sucrées est l’un des changements les plus rentables pour la santé.', 'Ne boire aucune boisson sucrée aujourd’hui : sodas, jus du commerce, boissons énergisantes.', ['Remplace par de l’eau, du thé ou de l’eau pétillante.', 'Garde une bouteille d’eau sur toi.'], 's', ['alimentation']],
  ['easy', 'J', 'Préparer le petit-déjeuner de demain', 'Un petit-déjeuner prêt la veille, c’est un bon début de journée sans effort.', 'Ce soir, préparer le petit-déjeuner de demain : sortir les bols, préparer les flocons, le pain ou les fruits.', ['Pense à une protéine : œufs, yaourt, fromage blanc.', 'Prépare-le avant de te coucher.'], 's', ['alimentation', 'matin']],
  ['easy', 'J', 'Quatre pauses debout', 'Rester assis des heures abîme le dos : se lever régulièrement est un geste de santé simple.', 'Se lever et bouger 4 fois dans la journée (marcher, s’étirer, monter un escalier) au lieu de rester assis.', ['Mets une alarme toutes les heures pendant le travail.', 'Profite d’un appel pour marcher.'], 'c:4:pauses', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Étirements du dos et de la nuque', 'Des étirements de posture soulagent le dos après de longues heures assis.', 'Faire une série d’étirements du dos et de la nuque : redressement, épaules en arrière, rotation de la nuque, chat-vache.', ['Place le dos contre un mur pour sentir l’alignement.', 'Respire lentement dans chaque position.'], 's', ['sans matériel', 'moins de 10 min']],
  // ── Modérées (12)
  ['medium', 'JS', 'Marche rapide, 30 minutes', 'Trente minutes de marche rapide entretiennent le cœur et les articulations.', 'Marcher 30 minutes à bon rythme, d’une traite ou en deux fois.', ['Choisis un parcours que tu aimes.', 'Un rythme où tu peux parler mais plus chanter.'], 't:30', ['extérieur', 'sport']],
  ['medium', 'JS', 'Cardio, 20 minutes', 'Le cardio régulier améliore l’endurance et l’humeur.', 'Courir, pédaler ou nager 20 minutes à une allure où tu peux encore parler.', ['Alterne course et marche si besoin.', 'Échauffe-toi quelques minutes à allure lente.'], 't:20', ['sport']],
  ['medium', 'S', 'Coucher régulier, 5 nuits sur 7', 'Une heure de coucher stable est l’un des meilleurs leviers de santé.', 'Te coucher à heure fixe (± 30 minutes) 5 soirs sur 7.', ['Fixe une alarme de coucher.', 'Garde le même horaire le week-end.'], 'c:5:nuits', ['sommeil']],
  ['medium', 'J', 'Huit verres d’eau dans la journée', 'Boire régulièrement vaut mieux que boire beaucoup d’un coup.', 'Boire 8 verres d’eau dans la journée, répartis du matin au soir.', ['Mets des alarmes discrètes.', 'Garde une bouteille visible sur ton bureau.'], 'c:8:verres', ['alimentation']],
  ['medium', 'JS', 'Vélo ou natation, 30 minutes', 'Un cardio sans impact ménage les articulations tout en entraînant le souffle.', 'Faire 30 minutes de vélo (réel ou d’appartement) ou de natation à un rythme soutenu.', ['Règle bien la selle.', 'Varie l’intensité en cours de route.'], 't:30', ['sport']],
  ['medium', 'S', 'Cuisine maison, 5 repas', 'Cuisiner maison est la façon la plus simple de mieux manger sans régime.', 'Cuisiner au moins 5 repas maison dans la semaine.', ['Prépare un menu le dimanche.', 'Cuisine en double pour le lendemain.'], 'c:5:repas', ['alimentation', 'cuisine']],
  ['medium', 'J', 'Des légumes à deux repas', 'Des légumes à chaque repas principal, c’est la base d’une alimentation qui tient la route.', 'Mettre des légumes dans tes deux repas principaux de la journée, au moins la moitié de l’assiette.', ['Surgelés, en conserve ou frais : tout compte.', 'Ajoute-les à ce que tu manges déjà.'], 'c:2:repas', ['alimentation']],
  ['medium', 'S', 'Réveil régulier, 5 jours sur 7', 'Un réveil régulier stabilise l’énergie de toute la journée.', 'Te réveiller à heure fixe (± 30 minutes) 5 jours sur 7.', ['Garde le même réveil le week-end.', 'Ouvre les volets dès le lever.'], 'c:5:jours', ['sommeil', 'matin']],
  ['medium', 'J', 'Préparer sa matinée de demain', 'Une matinée qui démarre bien se prépare la veille.', 'Ce soir, préparer demain matin : régler le réveil, sortir les vêtements, préparer le petit-déjeuner et poser le téléphone hors de la chambre.', ['Fais-le avant de te mettre en pyjama.', 'Coche chaque point au fur et à mesure.'], 'e:Régler le réveil|Sortir mes vêtements|Préparer le petit-déjeuner|Poser le téléphone hors de la chambre', ['sommeil']],
  ['medium', 'S', 'Marcher 5 fois dans la semaine', 'Marcher presque tous les jours est la base de la santé cardiovasculaire.', 'Faire 5 sorties à pied dans la semaine, d’au moins 20 minutes chacune.', ['Intègre la marche à un trajet quotidien.', 'Ajoute une sortie dès qu’elle est faite.'], 'c:5:sorties', ['extérieur', 'sport']],
  ['medium', 'JS', 'Grande sortie, 45 minutes', 'Une longue sortie combine endurance et exposition à la lumière.', 'Faire une sortie de 45 minutes à pied ou à vélo, dehors, à un rythme régulier.', ['Emporte de l’eau.', 'Prends un chemin que tu aimes.'], 't:45', ['extérieur', 'sport']],
  ['medium', 'S', 'Écrans coupés avant dormir, 5 soirs', 'Une habitude répétée finit par s’installer : cinq soirs, c’est un bon début.', 'Éteindre tous les écrans avant de dormir, 5 soirs sur 7.', ['Remplace par la lecture ou la discussion.', 'Charge le téléphone hors de la chambre.'], 'c:5:soirs', ['sommeil', 'détox']],
  // ── Audacieuses (9)
  ['high', 'S', 'Endurance, 3 séances dans la semaine', 'Trois séances d’endurance par semaine abaissent nettement les risques de santé.', 'Faire 3 séances de cardio dans la semaine (course, vélo, natation, marche rapide).', ['Répartis les séances sur la semaine.', 'Garde une allure où tu peux encore parler.'], 'c:3:séances', ['sport']],
  ['high', 'S', 'Dormir 7 à 9 heures, 6 nuits', 'Sept à neuf heures de sommeil, c’est la durée dont la plupart des adultes ont besoin.', 'Dormir entre 7 et 9 heures par nuit, 6 nuits sur 7.', ['Prépare ta chambre : fraîche, sombre, silencieuse.', 'Garde un horaire de coucher stable.'], 'c:6:nuits', ['sommeil']],
  ['high', 'JS', 'Longue marche, 90 minutes', 'Une longue marche entretient l’endurance de base et clarifie l’esprit.', 'Faire une sortie de 90 minutes à pied à un rythme régulier.', ['Emporte de l’eau et une collation.', 'Alterne montées et portions plates.'], 't:90', ['extérieur', 'sport']],
  ['high', 'S', 'Repas maison équilibré, 7 jours', 'Sept jours de repas équilibrés installent de nouvelles habitudes alimentaires.', 'Cuisiner un repas maison équilibré (protéine, légume, féculent) chaque jour pendant 7 jours.', ['Prépare les bases le dimanche.', 'Varie les légumes.'], 'c:7:jours', ['alimentation', 'cuisine']],
  ['high', 'SM', 'Cardio, 4 séances', 'Quatre séances de cardio dans la période installent une base d’endurance.', 'Faire 4 séances de cardio sur la période : course, vélo, natation ou marche rapide.', ['Prévois-les à l’avance dans ton agenda.', 'Varie les activités pour ne pas t’ennuyer.'], 'c:4:séances', ['sport']],
  ['high', 'S', 'Coucher fixe, 7 soirs sur 7', 'Une semaine sans exception, c’est la meilleure façon de caler son rythme.', 'Te coucher à heure fixe (± 30 minutes) tous les soirs pendant 7 jours.', ['Suis-le dans un calendrier.', 'Prévois une alarme de rappel.'], 'c:7:soirs', ['sommeil']],
  ['high', 'M', 'Coucher régulier, 20 nuits dans le mois', 'Un mois de nuits régulières reconstruit le sommeil en profondeur.', 'Te coucher à heure fixe (± 30 minutes) au moins 20 nuits dans le mois.', ['Suis ton coucher dans un calendrier.', 'Ne rattrape pas une mauvaise nuit en décalant tout.'], 'c:20:nuits', ['sommeil']],
  ['high', 'M', 'Marche, 20 sorties dans le mois', 'Vingt sorties à pied dans le mois, c’est presque une marche tous les deux jours.', 'Faire 20 sorties à pied dans le mois, d’au moins 20 minutes chacune.', ['Intègre la marche à un trajet quotidien.', 'Ajoute chaque sortie après coup.'], 'c:20:sorties', ['extérieur', 'sport']],
  ['high', 'M', 'Cardio, 10 séances dans le mois', 'Dix séances de cardio par mois installent une bonne base d’endurance.', 'Faire 10 séances de cardio dans le mois : course, vélo, natation, marche rapide.', ['Deux ou trois séances par semaine.', 'Varie les activités.'], 'c:10:séances', ['sport']],
  // ── Légendaires (5)
  ['expert', 'M', 'Sommeil régulier, 25 nuits', 'Vingt-cinq nuits de rythme régulier changent l’énergie, l’humeur et la santé.', 'Te coucher et te lever à heure régulière (± 30 minutes) au moins 25 nuits dans le mois.', ['Choisis un horaire de coucher qui ne dépend pas de ta soirée.', 'Prépare la chambre : fraîche, sombre, silencieuse.'], 'c:25:nuits', ['sommeil']],
  ['expert', 'ME', 'Endurance, 40 séances', 'Quarante séances d’endurance bâtissent une vraie condition physique.', 'Faire 40 séances d’endurance (marche, course, vélo, natation). Adapte à ta condition et consulte un professionnel au besoin.', ['Programme 3 séances par semaine.', 'Augmente la distance petit à petit.'], 'c:40:séances', ['sport']],
  ['expert', 'SM', 'Semaine santé, 7 jours', 'Sept jours où sommeil, repas, eau et marche sont tenus ensemble.', 'Pendant 7 jours : dormir 7 à 9 heures, marcher 30 minutes, boire 1,5 L d’eau et manger équilibré chaque jour. Adapte à ta condition.', ['Coche chaque jour réussi.', 'Prépare tes repas à l’avance.'], 'c:7:jours', ['sommeil', 'alimentation', 'sport']],
  ['expert', 'ME', 'Grande distance', 'Un grand objectif d’endurance demande une vraie préparation : semi-marathon, grande randonnée.', 'Préparer et réussir un objectif d’endurance (course, marche, vélo). Adapte à ta condition et consulte un professionnel au besoin.', ['Choisis un objectif réaliste avec une date.', 'Augmente la distance de 10 % par semaine au maximum.'], 'e:Choisir mon objectif et sa date|Suivre au moins 8 semaines de préparation|Réussir l’épreuve', ['sport']],
  ['expert', 'M', 'Un mois de cuisine maison', 'Un mois de repas maison est le plus gros changement alimentaire possible sans régime.', 'Cuisiner au moins 25 repas maison dans le mois.', ['Planifie un menu hebdomadaire.', 'Prépare en batch le dimanche.'], 'c:25:repas', ['alimentation', 'cuisine']],
];
