// SAG — Sagesse : calme, attention, conscience de soi. Respirer, écrire, se déconnecter, être présent.
// [difficulté, périodes (J/S/M/E), titre, ambiance (pourquoi), objectif, [conseils], validation, [tags]]
// validation : s | c:cible:unité | t:minutes | e:étape1|étape2 | j
export default [
  // ── Faciles (14)
  ['easy', 'J', 'Respiration calme, 5 minutes', 'Respirer lentement active le système nerveux qui apaise le corps.', 'Respirer lentement pendant 5 minutes : inspirer 4 secondes, expirer 6 secondes, assis ou allongé.', ['Pose une main sur le ventre.', 'Garde les épaules relâchées.'], 't:5', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Méditation, 10 minutes', 'Dix minutes de méditation entraînent la capacité à rester présent.', 'Méditer 10 minutes, assis, en portant l’attention sur la respiration, avec ou sans guidage.', ['Utilise une méditation guidée si tu débutes.', 'Quand l’esprit part, reviens simplement à la respiration.'], 't:10', ['sans matériel']],
  ['easy', 'J', 'Journal du soir', 'Écrire fait redescendre les tensions et aide à voir clair dans sa journée.', 'Écrire dans un carnet ce qui s’est passé aujourd’hui et ce que tu as ressenti.', ['Écris sans te relire.', 'Quelques phrases suffisent.'], 'j', ['sans matériel']],
  ['easy', 'J', 'Trois gratitudes', 'Chercher le positif entraîne l’attention vers ce qui va bien.', 'Noter 3 choses précises pour lesquelles tu es reconnaissant aujourd’hui, et pourquoi.', ['Sois précis : « le café avec Julie », pas « mes amis ».', 'Évite de répéter les mêmes d’un jour à l’autre.'], 'c:3:gratitudes', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Balayage corporel', 'Repérer les tensions est le premier pas pour les relâcher.', 'Parcourir mentalement ton corps des pieds à la tête, en relâchant chaque zone : pieds, jambes, ventre, dos, épaules, mâchoire.', ['Allonge-toi si tu peux.', 'Respire lentement entre chaque zone.'], 's', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Silence sans écran, 10 minutes', 'Le silence laisse l’esprit retomber après une journée de sollicitations.', 'Rester 10 minutes dans le silence, sans écran, sans musique, sans lecture, assis ou en marchant lentement.', ['Mets un minuteur.', 'Laisse les pensées passer sans les suivre.'], 't:10', ['détox', 'sans matériel']],
  ['easy', 'J', 'Promenade attentive', 'Marcher en observant calme l’esprit mieux qu’une marche pressée.', 'Marcher un moment sans écran ni écouteurs, en remarquant ce que tu vois, entends et sens.', ['Choisis un chemin que tu connais peu.', 'Nomme mentalement cinq choses que tu vois.'], 's', ['extérieur', 'détox']],
  ['easy', 'J', 'Cohérence cardiaque, 5 minutes', 'Respirer à ce rythme régulier apaise le rythme cardiaque et l’anxiété.', 'Respirer pendant 5 minutes au rythme de 6 respirations par minute : 5 secondes pour inspirer, 5 secondes pour expirer.', ['Utilise une application ou une vidéo de guidage.', 'Respire par le ventre.'], 't:5', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Nommer ses émotions', 'Mettre un mot sur une émotion réduit son intensité.', 'Repérer ce que tu ressens maintenant, le nommer précisément et noter ce qui l’a provoqué.', ['Sois précis : frustré, inquiet, soulagé…', 'Écris sans te juger.'], 'j', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Rituel du soir apaisant', 'Un rituel court prépare le corps et l’esprit au repos.', 'Avant de dormir, enchaîner trois gestes calmes : lumière douce, étirements lents, lecture légère ou respiration.', ['Fais-le toujours dans le même ordre.', 'Garde le téléphone hors de portée.'], 'e:Baisser la lumière|Faire des étirements lents|Lire ou respirer calmement', ['sommeil', 'détox']],
  ['easy', 'J', 'Un moment pour soi', 'Prendre du temps pour soi n’est pas un luxe, c’est de l’entretien.', 'Prendre un moment pour une activité calme et personnelle, sans obligation : thé, musique douce, lecture, dessin.', ['Choisis quelque chose qui te fait vraiment plaisir.', 'Évite les écrans.'], 's', ['sans matériel']],
  ['easy', 'J', 'Relaxation musculaire', 'Contracter puis relâcher chaque groupe de muscles fait baisser la tension.', 'Contracter puis relâcher successivement chaque groupe musculaire, des pieds à la tête, 5 secondes de contraction pour 10 de relâchement.', ['Respire en relâchant.', 'Allonge-toi dans un endroit calme.'], 's', ['sans matériel']],
  ['easy', 'J', 'Bilan de journée en trois lignes', 'Un retour sur la journée transforme l’expérience en apprentissage.', 'Noter ce qui s’est bien passé, ce qui a été difficile et une chose à faire autrement demain.', ['Trois lignes suffisent.', 'Sois bienveillant avec toi-même.'], 'j', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Une seule chose à la fois', 'Faire une seule chose à la fois entraîne l’attention.', 'Faire une seule tâche (vaisselle, marche, repas) en y portant toute ton attention, sans autre activité en parallèle.', ['Pas de téléphone, pas de musique.', 'Quand l’esprit part, reviens à la tâche.'], 's', ['sans matériel', 'moins de 10 min']],
  // ── Modérées (12)
  ['medium', 'JS', 'Méditation, 15 minutes', 'Quinze minutes permettent de dépasser l’agitation du début de séance.', 'Méditer 15 minutes, assis, en portant l’attention sur la respiration.', ['Utilise une méditation guidée si tu débutes.', 'Quand l’esprit part, reviens simplement à la respiration.'], 't:15', ['sans matériel']],
  ['medium', 'JS', 'Journal réflexif', 'Une écriture libre régulière aide à comprendre ses pensées.', 'Écrire un texte sur ta journée, tes émotions ou une question qui te préoccupe.', ['Écris sans te relire.', 'Si tu bloques, commence par « aujourd’hui, j’ai ressenti… ».'], 'j', ['sans matériel']],
  ['medium', 'J', 'Un moment dans la nature, sans écran', 'Le contact avec la nature réduit le stress mesurable en quelques minutes.', 'Passer un moment dans un parc, une forêt ou au bord de l’eau, sans écran.', ['Laisse ton téléphone dans ta poche.', 'Prends le temps de regarder autour de toi.'], 's', ['extérieur', 'détox']],
  ['medium', 'S', 'Méditation, 4 séances', 'Une pratique régulière compte plus qu’une longue séance isolée.', 'Faire 4 séances de méditation ou de respiration guidée dans la semaine, de la durée de ton choix.', ['Dix minutes par séance suffisent.', 'Médite à la même heure chaque fois.'], 'c:4:séances', ['sans matériel']],
  ['medium', 'JS', 'Une heure sans écran de loisir', 'Une heure déconnectée laisse la place à autre chose que les notifications.', 'Passer une heure sans écran de loisir (téléphone, télévision, jeux) et faire autre chose à la place.', ['Prépare une activité de remplacement.', 'Mets le téléphone dans une autre pièce.'], 's', ['détox']],
  ['medium', 'S', 'Journal, 4 entrées dans la semaine', 'Écrire régulièrement aide à repérer ses schémas et ses progrès.', 'Écrire 4 fois dans ton journal dans la semaine : événements, émotions, réflexions.', ['Quelques lignes chaque soir.', 'Relis la semaine dimanche.'], 'c:4:entrées', ['sans matériel']],
  ['medium', 'JS', 'Relaxation guidée complète', 'Un temps de détente structuré détend vraiment le corps.', 'Enchaîner respiration profonde, détente musculaire et visualisation calme dans une même séance.', ['Choisis un endroit où personne ne te dérange.', 'Une piste guidée peut t’aider.'], 'e:Respiration profonde|Détente musculaire|Visualisation calme', ['sans matériel']],
  ['medium', 'J', 'Silence et solitude', 'Être seul avec ses pensées, sans distraction, apprend à les connaître.', 'Passer un moment seul avec toi-même : sans écran, sans musique, sans activité. Juste être là.', ['Accepte l’ennui des premières minutes.', 'Observe tes pensées sans les juger.'], 's', ['détox', 'sans matériel']],
  ['medium', 'S', 'Temps pour soi, 3 moments', 'Quelques moments par semaine réservés à soi font déjà une différence.', 'Prendre 3 moments pour toi dans la semaine : activité calme, passion personnelle, repos, sans obligation.', ['Note-les dans ton agenda.', 'Protège-les comme des rendez-vous.'], 'c:3:moments', ['sans matériel']],
  ['medium', 'JS', 'Écriture libre', 'Écrire sans filtre laisse sortir ce qui encombre l’esprit.', 'Écrire sans t’arrêter ni te corriger, sur ce qui te traverse l’esprit : au moins une page.', ['Si tu bloques, écris « je ne sais pas quoi écrire » jusqu’à ce que ça vienne.', 'Ne relis pas.'], 'j', ['sans matériel']],
  ['medium', 'S', 'Nature, 2 sorties dans la semaine', 'Quelques sorties dans la nature par semaine améliorent l’humeur et le stress.', 'Faire 2 sorties dans la nature, sans écran, dans la semaine : parc, forêt, bord de l’eau.', ['Va dans un endroit calme.', 'Laisse ton téléphone en mode avion.'], 'c:2:sorties', ['extérieur', 'détox']],
  ['medium', 'J', 'Bilan approfondi', 'Un bilan plus long aide à prendre du recul sur ce qui compte.', 'Faire le bilan écrit de ta semaine ou de ta journée : réussites, difficultés, leçons, décisions.', ['Pose-toi trois questions : qu’est-ce qui a marché ? qu’est-ce que j’ai appris ? que changer ?', 'Sois honnête, pas sévère.'], 'j', ['sans matériel']],
  // ── Audacieuses (9)
  ['high', 'S', 'Méditation, 6 séances', 'Presque chaque jour de la semaine : la pratique devient une habitude.', 'Faire 6 séances de méditation dans la semaine.', ['Médite à la même heure chaque jour.', 'Dix minutes suffisent.'], 'c:6:séances', ['sans matériel']],
  ['high', 'S', 'Journal, 5 entrées', 'Écrire presque chaque jour permet un vrai travail sur soi.', 'Écrire 5 fois dans ton journal dans la semaine : journal, bilan, lettres que tu n’enverras pas.', ['Écris à heure fixe.', 'Relis une entrée ancienne pour voir ton évolution.'], 'c:5:entrées', ['sans matériel']],
  ['high', 'JS', 'Méditation longue, 20 minutes', 'Une séance longue approfondit la concentration et la détente.', 'Méditer 20 minutes d’affilée, assis, sans interruption.', ['Commence par 3 minutes de respiration profonde.', 'Accepte que l’esprit s’agite.'], 't:20', ['sans matériel']],
  ['high', 'S', 'Nature, 3 sorties', 'Plusieurs sorties dans la nature par semaine changent la perception du stress.', 'Faire 3 sorties dans la nature, sans écran, dans la semaine.', ['Une sortie plus longue le week-end.', 'Varie les lieux.'], 'c:3:sorties', ['extérieur', 'détox']],
  ['high', 'SM', 'Déconnexion, 3 demi-journées sans écran', 'Quelques demi-journées hors écran de loisir sont un vrai reset.', 'Passer 3 demi-journées sans écran de loisir sur la période, en les consacrant à autre chose : balade, lecture, repos, activité manuelle.', ['Préviens ton entourage.', 'Prévois une activité de remplacement.'], 'c:3:demi-journées', ['détox']],
  ['high', 'S', 'Silence et solitude, 3 moments', 'Passer du temps seul avec soi-même apprend à se connaître.', 'Prendre 3 moments de silence et de solitude dans la semaine, sans écran ni musique.', ['Choisis un lieu calme.', 'Note ce qui remonte, sans le juger.'], 'c:3:moments', ['détox', 'sans matériel']],
  ['high', 'M', 'Méditation, 20 séances dans le mois', 'Vingt séances en un mois installent une vraie pratique.', 'Faire 20 séances de méditation ou de pleine conscience sur le mois.', ['Pratique chaque matin ou chaque soir.', 'Ajoute chaque séance après coup.'], 'c:20:séances', ['sans matériel']],
  ['high', 'M', 'Journal, 15 entrées', 'Quinze entrées d’écriture sur un mois donnent un vrai recul sur sa vie.', 'Écrire 15 entrées de journal sur le mois, d’au moins quelques lignes chacune.', ['Une entrée tous les deux jours.', 'Relis ton mois à la fin.'], 'c:15:entrées', ['sans matériel']],
  ['high', 'M', 'Temps pour soi, 8 moments', 'Huit moments personnels dans le mois, c’est deux par semaine.', 'Prendre 8 moments pour toi sur le mois : activité calme, passion personnelle, repos conscient.', ['Planifie-les dans ton agenda.', 'Refuse ce qui les empiète.'], 'c:8:moments', ['sans matériel']],
  // ── Légendaires (5)
  ['expert', 'M', 'Méditation, 25 jours dans le mois', 'Vingt-cinq jours de pratique installent un vrai rendez-vous quotidien avec soi.', 'Méditer au moins 10 minutes par jour pendant 25 jours dans le mois.', ['Choisis un horaire qui ne bouge pas.', 'Si tu rates un jour, reprends le lendemain.'], 'c:25:jours', ['sans matériel']],
  ['expert', 'ME', 'Pratique intérieure, 60 séances', 'Soixante séances de méditation, de journal ou de silence approfondissent durablement le rapport à soi.', 'Faire 60 séances de pratiques intérieures : méditation, écriture réflexive, silence, respiration.', ['Alterne les pratiques selon les jours.', 'Tiens un carnet de suivi.'], 'c:60:séances', ['sans matériel']],
  ['expert', 'SM', 'Une journée sans écran de loisir', 'Une journée entière de déconnexion est un vrai défi dans le monde actuel.', 'Passer une journée complète sans écran de loisir, hors travail et besoins essentiels.', ['Prépare la veille ce que tu feras à la place.', 'Préviens ton entourage.'], 's', ['détox']],
  ['expert', 'ME', 'Journal, 50 entrées', 'Cinquante entrées de journal forment un travail de fond sur soi.', 'Écrire 50 entrées de journal ou de bilan : événements, émotions, leçons, retours sur ton parcours.', ['Écris à heure fixe, même quelques lignes.', 'Relis un mois entier de temps en temps.'], 'c:50:entrées', ['sans matériel']],
  ['expert', 'M', 'Un mois de calme, 20 jours', 'Vingt jours de pratiques calmes dans le mois changent la façon de réagir au stress.', 'Pratiquer une activité calme chaque jour pendant 20 jours dans le mois : méditation, respiration, silence, nature.', ['Choisis une pratique simple, faisable même un jour chargé.', 'Marque chaque jour réussi.'], 'c:20:jours', ['sans matériel']],
];
