// CHA — Charisme : le social. Écouter, parler, donner des nouvelles, passer du temps avec les autres, prendre la parole.
// [difficulté, périodes (J/S/M/E), titre, ambiance (pourquoi), objectif, [conseils], validation, [tags]]
// validation : s | c:cible:unité | t:minutes | e:étape1|étape2 | j
export default [
  // ── Faciles (14)
  ['easy', 'J', 'Appel à un proche, 10 minutes', 'Un appel de dix minutes entretient un lien mieux qu’un message.', 'Appeler un proche (famille ou ami) et parler pendant au moins 10 minutes.', ['Demande des nouvelles précises, pas seulement « ça va ».', 'Appelle à un moment où vous êtes tous deux disponibles.'], 't:10', ['social', 'moins de 10 min']],
  ['easy', 'J', 'Repas sans écran, 15 minutes d’échange', 'Parler à table crée du lien sans effort particulier.', 'Passer au moins 15 minutes à discuter avec quelqu’un pendant un repas, sans écran.', ['Pose des questions ouvertes.', 'Range les téléphones.'], 't:15', ['social']],
  ['easy', 'J', 'Écoute active, 10 minutes', 'Écouter vraiment est la base de tout lien durable.', 'Écouter quelqu’un pendant 10 minutes sans l’interrompre ni donner de conseils non demandés, puis reformuler ce qu’il a dit.', ['Regarde la personne dans les yeux.', 'Reformule avec « si je comprends bien… ».'], 't:10', ['social']],
  ['easy', 'J', 'Donner des nouvelles, 10 minutes', 'Un petit message suffit souvent à rouvrir un lien.', 'Écrire pendant 10 minutes à trois personnes que tu n’as pas contactées depuis longtemps.', ['Personnalise chaque message.', 'Pose une question ouverte.'], 't:10', ['social', 'moins de 10 min']],
  ['easy', 'J', 'Parler à un voisin ou un inconnu', 'Les petites conversations de tous les jours entretiennent l’aisance sociale.', 'Échanger quelques mots avec un voisin, un commerçant ou un inconnu pendant au moins 5 minutes.', ['Commence par un sujet simple : la météo, le quartier.', 'Pose une question ouverte.'], 't:5', ['social', 'moins de 10 min']],
  ['easy', 'J', 'Message de remerciement, 5 minutes', 'Remercier précisément fait plaisir et renforce le lien.', 'Écrire pendant 5 minutes un message de remerciement détaillé à quelqu’un.', ['Cite un geste précis.', 'Dis ce que ça t’a apporté.'], 't:5', ['social', 'moins de 10 min']],
  ['easy', 'J', 'Pause café avec quelqu’un, 15 minutes', 'Un moment informel avec quelqu’un d’autre compte plus qu’il n’y paraît.', 'Prendre 15 minutes pour un café ou un thé avec un collègue, un voisin ou un ami.', ['Propose-le simplement.', 'Garde le téléphone dans la poche.'], 't:15', ['social']],
  ['easy', 'J', 'Message vocal à un ami, 5 minutes', 'Une voix transmet plus d’émotion qu’un texte.', 'Enregistrer et envoyer un message vocal de 5 minutes à un ami qui vit loin.', ['Raconte ta journée simplement.', 'Pose une question à la fin.'], 't:5', ['social', 'moins de 10 min']],
  ['easy', 'J', 'Réponses en retard, 15 minutes', 'Répondre aux messages en attente libère l’esprit et rassure les autres.', 'Passer 15 minutes à répondre aux messages et courriers personnels en attente.', ['Commence par les plus anciens.', 'Une réponse courte vaut mieux que pas de réponse.'], 't:15', ['social', 'numérique']],
  ['easy', 'J', 'Jeu à plusieurs, 20 minutes', 'Jouer ensemble crée du lien et de la complicité.', 'Jouer 20 minutes à un jeu de société ou de cartes avec au moins une autre personne.', ['Choisis un jeu simple.', 'Le but est de rire, pas de gagner.'], 't:20', ['social', 'jeu']],
  ['easy', 'J', 'Parler à voix haute, 5 minutes', 'S’entraîner à parler fort et clairement donne de l’aisance à l’oral.', 'Pendant 5 minutes, t’entraîner à parler à voix haute devant un miroir ou en t’enregistrant : présentation de soi, histoire, opinion.', ['Articule et ralentis.', 'Réécoute-toi et note un point à améliorer.'], 't:5', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Coup de main, 15 minutes', 'Aider quelqu’un sans qu’on le demande crée de la confiance.', 'Consacrer 15 minutes à aider quelqu’un autour de toi : porter, réparer, expliquer, accompagner.', ['Propose avant d’agir.', 'Reste disponible sans en faire trop.'], 't:15', ['social']],
  ['easy', 'J', 'Marche avec quelqu’un, 15 minutes', 'Marcher côte à côte facilite les conversations.', 'Marcher 15 minutes avec quelqu’un en discutant, à pied ou par téléphone en marchant chacun de son côté.', ['Choisis un parcours agréable.', 'Évite de regarder ton téléphone.'], 't:15', ['social', 'extérieur']],
  ['easy', 'J', 'Carte ou message de compliment, 10 minutes', 'Un compliment sincère change la journée de quelqu’un.', 'Pendant 10 minutes, écrire un compliment ou un mot d’encouragement personnalisé à quelqu’un de ton entourage.', ['Sois précis et sincère.', 'Évite les formules toutes faites.'], 't:10', ['social', 'moins de 10 min']],
  // ── Modérées (12)
  ['medium', 'S', 'Rencontre en personne, 60 minutes', 'Voir quelqu’un en vrai renforce le lien plus que mille messages.', 'Cumuler 60 minutes de rencontre en personne avec un ou plusieurs proches sur la semaine.', ['Propose un café ou une promenade.', 'Ajoute le temps passé après la rencontre.'], 'c:60:minutes', ['social']],
  ['medium', 'JS', 'Appel long, 30 minutes', 'Un appel long permet d’aborder des sujets plus profonds.', 'Appeler un proche et parler pendant au moins 30 minutes.', ['Choisis une personne que tu n’as pas entendue depuis longtemps.', 'Pose des questions ouvertes.'], 't:30', ['social']],
  ['medium', 'S', 'Retrouver trois personnes', 'Rétablir le contact avec des personnes perdues de vue entretient un réseau.', 'Contacter trois personnes que tu n’as pas vues depuis plus de six mois et proposer un moment ensemble.', ['Commence par les plus faciles.', 'Propose une date précise.'], 'c:3:personnes', ['social']],
  ['medium', 'J', 'Repas partagé, 45 minutes', 'Un vrai repas partagé donne du temps pour se parler vraiment.', 'Partager un repas d’au moins 45 minutes avec une ou plusieurs personnes, sans écran.', ['Cuisinez ensemble si possible.', 'Pose des questions sur l’actualité de chacun.'], 't:45', ['social', 'alimentation']],
  ['medium', 'JS', 'Écoute active, 20 minutes', 'Une conversation longue demande de savoir écouter.', 'Écouter quelqu’un pendant 20 minutes en reformulant, en posant des questions ouvertes, sans parler de toi.', ['Laisse des silences.', 'Pose « et ensuite ? » plutôt que de donner un avis.'], 't:20', ['social']],
  ['medium', 'S', 'Activité à plusieurs, 90 minutes', 'Faire quelque chose ensemble rapproche plus que parler.', 'Cumuler 90 minutes d’activité à plusieurs sur la semaine : sport, cuisine, jeu, balade, atelier.', ['Invite quelqu’un à te rejoindre.', 'Propose une activité simple.'], 'c:90:minutes', ['social']],
  ['medium', 'JS', 'Prise de parole, 15 minutes', 'S’entraîner à structurer son discours donne de l’assurance.', 'Pendant 15 minutes, préparer puis prononcer à voix haute un court exposé ou un discours sur un sujet de ton choix.', ['Fais trois parties : début, milieu, fin.', 'Enregistre-toi pour te réécouter.'], 't:15', ['sans matériel']],
  ['medium', 'S', 'Aider les autres, 60 minutes', 'Donner du temps est l’une des plus belles façons d’entretenir un lien.', 'Cumuler 60 minutes à aider quelqu’un ou une association sur la semaine : bénévolat, coup de main, accompagnement.', ['Pense à un voisin ou un proche.', 'Propose une aide concrète et précise.'], 'c:60:minutes', ['social']],
  ['medium', 'J', 'Conversation de fond, 30 minutes', 'Parler de sujets importants, sans se juger, construit une vraie intimité.', 'Avoir une conversation de 30 minutes sur un sujet qui compte vraiment pour toi ou pour l’autre.', ['Pose des questions plutôt que de donner ton avis.', 'Reste présent, sans téléphone.'], 't:30', ['social']],
  ['medium', 'JS', 'Marche et discussion, 30 minutes', 'Marcher ensemble pendant une demi-heure donne le temps d’aller au fond des sujets.', 'Marcher 30 minutes avec quelqu’un en discutant.', ['Choisis un parcours sans bruit.', 'Pose des questions sur ses projets.'], 't:30', ['social', 'extérieur']],
  ['medium', 'S', 'Nouvelles rencontres, 45 minutes', 'Élargir son cercle demande de sortir de ses habitudes.', 'Cumuler 45 minutes à rencontrer de nouvelles personnes sur la semaine : événement, association, cours, voisins.', ['Présente-toi simplement.', 'Retiens un prénom et une information sur chaque personne.'], 'c:45:minutes', ['social']],
  ['medium', 'JS', 'Jeu de société, 40 minutes', 'Les jeux à plusieurs créent des souvenirs partagés.', 'Jouer 40 minutes à un jeu de société avec au moins deux autres personnes.', ['Choisis un jeu que tout le monde connaît.', 'Garde la bonne humeur.'], 't:40', ['social', 'jeu']],
  // ── Audacieuses (9)
  ['high', 'S', 'Temps social, 180 minutes dans la semaine', 'Trois heures de temps social par semaine entretiennent un cercle solide.', 'Cumuler 180 minutes passées avec d’autres personnes sur la semaine : repas, sorties, appels, activités.', ['Prévois deux ou trois moments fixes.', 'Alterne en personne et à distance.'], 'c:180:minutes', ['social']],
  ['high', 'S', 'Engagement pour les autres, 120 minutes', 'Deux heures de service aux autres donnent du sens et des liens.', 'Cumuler 120 minutes de bénévolat, d’entraide ou d’aide à des proches sur la semaine.', ['Repère une association proche de chez toi.', 'Commence par une mission courte.'], 'c:120:minutes', ['social']],
  ['high', 'JS', 'Sortie à plusieurs, 90 minutes', 'Une longue sortie partagée construit des souvenirs communs.', 'Passer 90 minutes avec d’autres lors d’une sortie ou d’un événement : cinéma, repas, balade, concert, soirée jeux.', ['Invite plusieurs personnes.', 'Prévois un point de rendez-vous clair.'], 't:90', ['social']],
  ['high', 'S', 'Prise de parole en groupe, 60 minutes', 'Parler en groupe, c’est la meilleure façon de gagner en assurance.', 'Cumuler 60 minutes de pratique de la prise de parole en groupe sur la semaine : réunion, club, impro, présentation.', ['Prépare trois phrases clés.', 'Parle plus lentement que tu ne le crois nécessaire.'], 'c:60:minutes', ['social']],
  ['high', 'SM', 'Nouvelles rencontres, 120 minutes', 'Rencontrer de nouvelles personnes de façon régulière élargit le cercle.', 'Cumuler 120 minutes à rencontrer de nouvelles personnes sur la période : associations, cours, événements, voisinage.', ['Participe à un événement régulier.', 'Échange tes coordonnées avec au moins une personne.'], 'c:120:minutes', ['social']],
  ['high', 'S', 'Conversations de fond, 120 minutes', 'Deux heures de vraies discussions dans la semaine nourrissent les liens.', 'Cumuler 120 minutes de conversations profondes sur la semaine, en personne ou par téléphone.', ['Choisis des sujets importants.', 'Garde le téléphone de côté pendant les échanges.'], 'c:120:minutes', ['social']],
  ['high', 'M', 'Temps social, 10 heures dans le mois', 'Dix heures par mois de temps social, c’est environ une soirée par semaine.', 'Cumuler 10 heures passées avec d’autres personnes sur le mois : repas, sorties, activités, appels.', ['Planifie un moment social par semaine.', 'Varie les personnes.'], 'c:600:minutes', ['social']],
  ['high', 'M', 'Engagement associatif, 8 heures', 'Huit heures d’engagement dans le mois forment une vraie contribution.', 'Cumuler 8 heures de bénévolat ou d’engagement associatif sur le mois.', ['Choisis une cause qui te parle.', 'Vise une mission régulière.'], 'c:480:minutes', ['social']],
  ['high', 'M', 'Prise de parole, 5 heures', 'Cinq heures de pratique à l’oral changent l’aisance en public.', 'Cumuler 5 heures de pratique de la prise de parole sur le mois : club d’éloquence, présentation, impro, enregistrement.', ['Rejoins un groupe pour t’entraîner.', 'Réécoute-toi une fois par semaine.'], 'c:300:minutes', ['social']],
  // ── Légendaires (5)
  ['expert', 'M', 'Temps social, 15 heures dans le mois', 'Quinze heures de relations de qualité dans le mois sont un vrai engagement.', 'Cumuler 15 heures de temps de qualité avec d’autres personnes sur le mois : repas, appels, sorties, activités.', ['Planifie tes moments à l’avance.', 'Équilibre famille, amis et nouvelles rencontres.'], 'c:900:minutes', ['social']],
  ['expert', 'ME', 'Engagement, 30 heures', 'Trente heures d’aide aux autres marquent un vrai engagement dans la durée.', 'Cumuler 30 heures de bénévolat, d’entraide ou d’engagement associatif.', ['Choisis une mission régulière.', 'Note ce que tu apprends.'], 'c:1800:minutes', ['social']],
  ['expert', 'SM', 'Prise de parole en public, 6 heures', 'Six heures de préparation et de pratique mènent à une vraie prise de parole en public.', 'Cumuler 6 heures de préparation et de pratique de la prise de parole, jusqu’à un exposé ou un discours devant un public réel.', ['Prépare ton propos en trois parties.', 'Répète devant un ami.'], 'c:360:minutes', ['social']],
  ['expert', 'ME', 'Réseau et rencontres, 40 heures', 'Quarante heures de rencontres et de conversations bâtissent un réseau solide.', 'Cumuler 40 heures de rencontres, d’événements et de conversations avec des personnes variées.', ['Participe à des événements réguliers.', 'Entretiens les contacts avec un message de suivi.'], 'c:2400:minutes', ['social']],
  ['expert', 'M', 'Un mois de présence, 10 heures d’appels', 'Dix heures d’appels et d’échanges dans le mois entretiennent un cercle solide, même à distance.', 'Cumuler 10 heures d’appels et de conversations avec des proches sur le mois.', ['Planifie un appel par jour ou par semaine.', 'Varie les personnes.'], 'c:600:minutes', ['social']],
];
