// INT — Intelligence : apprendre, lire, comprendre, mémoriser, pratiquer une compétence.
// [difficulté, périodes (J/S/M/E), titre, ambiance (pourquoi), objectif, [conseils], validation, [tags]]
// validation : s | c:cible:unité | t:minutes | e:étape1|étape2 | j
export default [
  // ── Faciles (14)
  ['easy', 'J', 'Lecture, 5 pages', 'Cinq pages par jour, c’est un livre de 300 pages en deux mois sans y penser.', 'Lire 5 pages d’un livre, d’un essai ou d’un long article, sans écran de notifications.', ['Mets ton téléphone en mode avion.', 'Laisse le livre à portée de main.'], 'c:5:pages', ['moins de 10 min']],
  ['easy', 'J', 'Apprendre trois capitales', 'La géographie se retient par petites touches, un pays à la fois.', 'Apprendre 3 capitales ou pays avec leur place sur la carte, puis les redire de mémoire.', ['Utilise une carte muette ou une application.', 'Associe chaque capitale à une image.'], 'c:3:capitales', ['moins de 10 min']],
  ['easy', 'J', 'Vingt cartes mémoire', 'La révision espacée fixe l’information en mémoire à long terme.', 'Réviser 20 cartes mémoire (papier ou application) sur un sujet que tu apprends.', ['Récite la réponse avant de retourner la carte.', 'Mets de côté les cartes ratées.'], 'c:20:cartes', ['moins de 10 min']],
  ['easy', 'J', 'Un épisode de podcast éducatif', 'Le temps de trajet ou de ménage peut devenir du temps d’apprentissage.', 'Écouter un épisode de podcast ou une conférence sur un sujet que tu veux comprendre.', ['Choisis un sujet que tu ne maîtrises pas.', 'Note une idée retenue à la fin.'], 's', ['numérique']],
  ['easy', 'J', 'Trois raccourcis clavier', 'Quelques raccourcis bien choisis font gagner du temps à chaque utilisation.', 'Apprendre 3 raccourcis clavier utiles (copier-coller, annuler, changer de fenêtre, rechercher) et les utiliser tout de suite.', ['Colle un pense-bête près de l’écran.', 'Utilise-les au lieu de la souris, même si c’est plus lent au début.'], 'c:3:raccourcis', ['numérique', 'moins de 10 min']],
  ['easy', 'J', 'Article de fond et résumé', 'Résumer ce qu’on lit est le moyen le plus rapide de le retenir.', 'Lire un article de fond, puis le résumer en trois phrases.', ['Écris le résumé de tête avant de relire.', 'Trois phrases : sujet, idée principale, conclusion.'], 's', ['moins de 10 min']],
  ['easy', 'J', 'Un fait nouveau', 'Apprendre un fait par jour fait 365 connaissances en un an.', 'Chercher et noter un fait nouveau sur un sujet qui t’intrigue, puis le raconter à quelqu’un.', ['Vérifie ta source.', 'Raconte-le à voix haute pour le retenir.'], 's', ['moins de 10 min']],
  ['easy', 'J', 'Deux exercices de code', 'Programmer par petites séances est plus efficace que d’attendre une grande plage de temps.', 'Résoudre 2 exercices de programmation sur un site d’apprentissage.', ['Essaie sans regarder la solution.', 'Relis ton code une fois fini.'], 'c:2:exercices', ['numérique']],
  ['easy', 'J', 'Un documentaire court', 'Un documentaire donne une vue d’ensemble d’un sujet en peu de temps.', 'Regarder un documentaire ou un reportage court sur un sujet nouveau pour toi.', ['Prends deux ou trois notes.', 'Raconte-le à quelqu’un ensuite.'], 's', ['numérique']],
  ['easy', 'J', 'Mémoriser quatre vers', 'Mémoriser un texte ou une liste entraîne la mémoire de travail.', 'Apprendre par cœur quatre vers d’un poème, un court extrait ou une liste de dix éléments.', ['Apprends par blocs d’une ligne.', 'Récite-les le lendemain pour vérifier.'], 's', ['moins de 10 min']],
  ['easy', 'J', 'Notes à la main', 'Reformuler à l’écrit transforme une information en connaissance.', 'Noter à la main, avec tes propres mots, ce que tu as appris récemment : une demi-page.', ['Fais un schéma si ça aide.', 'Ne recopie pas : reformule.'], 's', ['moins de 10 min']],
  ['easy', 'J', 'Une leçon de cours en ligne', 'Un cours structuré donne un cadre que les vidéos isolées n’ont pas.', 'Suivre une leçon d’un cours en ligne structuré (université, plateforme, formation).', ['Avance dans l’ordre du programme.', 'Fais les exercices de la leçon.'], 's', ['numérique']],
  ['easy', 'J', 'Une fonction nouvelle d’un outil', 'Maîtriser un logiciel fait gagner du temps toute l’année.', 'Apprendre une fonction nouvelle d’un outil que tu utilises déjà (tableur, traitement de texte, messagerie).', ['Cherche un tutoriel court.', 'Réutilise-la dans la journée.'], 's', ['numérique', 'moins de 10 min']],
  ['easy', 'J', 'Explorer un sujet inconnu', 'Sortir de ses sujets habituels élargit les points de repère.', 'Lire sur un sujet que tu ne connais pas du tout (encyclopédie, article, vidéo) et retenir trois choses.', ['Choisis une page au hasard dans une encyclopédie.', 'Note trois choses retenues.'], 's', ['moins de 10 min']],
  // ── Modérées (12)
  ['medium', 'J', 'Lecture, 20 pages', 'Vingt pages permettent d’entrer dans un livre plutôt que de l’effleurer.', 'Lire 20 pages d’un livre sans interruption, hors écran de notifications.', ['Choisis un endroit calme.', 'Pose ton téléphone dans une autre pièce.'], 'c:20:pages', []],
  ['medium', 'JS', 'Quiz de culture générale', 'Se tester sur des sujets variés muscle la mémoire et la curiosité.', 'Répondre à 10 questions de culture générale (quiz en ligne, jeu ou livre) et chercher les réponses ratées.', ['Note les réponses que tu ne connaissais pas.', 'Choisis des thèmes que tu connais mal.'], 'c:10:questions', ['jeu']],
  ['medium', 'J', 'Cours en ligne, 2 leçons', 'Deux leçons d’affilée permettent de comprendre un concept de bout en bout.', 'Suivre 2 leçons d’un cours en ligne structuré et noter les points clés de chacune.', ['Fais les exercices proposés.', 'Écris les idées clés sans regarder.'], 'c:2:leçons', ['numérique']],
  ['medium', 'S', 'Lecture, 100 pages dans la semaine', 'Une centaine de pages par semaine avancent un livre régulièrement.', 'Lire 100 pages dans la semaine, en autant de fois que nécessaire.', ['Lis 15 pages chaque soir.', 'Ajoute tes pages après chaque séance de lecture.'], 'c:100:pages', []],
  ['medium', 'JS', 'Compétence pratique, tutoriel puis pratique', 'Pratiquer après avoir regardé un tutoriel fixe l’apprentissage.', 'Apprendre une compétence pratique en trois temps : tutoriel, pratique par toi-même, bilan écrit.', ['Fais-le toi-même sans regarder le tutoriel.', 'Note ce qui reste difficile.'], 'e:Regarder un tutoriel|Pratiquer par moi-même|Noter ce que j’ai appris', ['numérique']],
  ['medium', 'S', 'Expliquer un concept à quelqu’un', 'Expliquer à voix haute, c’est le meilleur test de compréhension.', 'Choisir un concept appris cette semaine, le préparer, puis l’expliquer à quelqu’un sans notes.', ['Utilise un exemple concret.', 'Si l’autre ne comprend pas, reformule autrement.'], 'e:Choisir un concept appris|Préparer mon explication|L’expliquer à quelqu’un sans notes', []],
  ['medium', 'JS', 'Révision active, 30 questions', 'Se tester soi-même est plus efficace que relire.', 'Réviser en te testant : répondre à 30 questions sur un sujet, sans regarder tes notes.', ['Cache tes notes et récite.', 'Reprends les questions ratées.'], 'c:30:questions', []],
  ['medium', 'J', 'Documentaire ou conférence', 'Un format long permet d’approfondir un sujet avec des exemples et des nuances.', 'Regarder un documentaire ou une conférence entière, puis écrire trois idées retenues.', ['Prends des notes pendant le visionnage.', 'Partage-les avec quelqu’un.'], 's', ['numérique']],
  ['medium', 'S', 'Apprentissage, 4 séances sur un sujet', 'Revenir plusieurs fois sur un même sujet dans la semaine donne une vraie progression.', 'Faire 4 séances sur un seul sujet dans la semaine : cours, lecture, exercices.', ['Choisis un seul sujet.', 'Note ce que tu as appris à chaque séance.'], 'c:4:séances', []],
  ['medium', 'JS', 'Programmation, 3 exercices', 'Un petit projet apprend plus que des exercices isolés.', 'Programmer : résoudre 3 exercices, avancer sur un mini-projet ou corriger un bug.', ['Fixe un petit objectif avant de commencer.', 'Teste ton code souvent.'], 'c:3:exercices', ['numérique']],
  ['medium', 'S', 'Une séance de cinéma', 'Un film vu en salle nourrit la culture et donne matière à discuter.', 'Aller voir un film au cinéma dans la semaine, seul ou accompagné.', ['Choisis un film dont tu ne connais rien à l’avance.', 'Raconte-le ensuite à quelqu’un.'], 's', ['culture']],
  ['medium', 'J', 'Résumé écrit d’un chapitre', 'Expliquer avec ses propres mots est le meilleur test de compréhension.', 'Lire un chapitre ou un article, puis rédiger un résumé d’une demi-page de mémoire.', ['Ne regarde pas le texte pendant que tu écris.', 'Compare ensuite avec l’original.'], 'e:Lire un chapitre ou un article|Résumer de mémoire en une demi-page', []],
  // ── Audacieuses (9)
  ['high', 'S', 'Lecture, 200 pages dans la semaine', 'Deux cents pages par semaine, c’est un livre de 300 pages tous les dix jours.', 'Lire 200 pages dans la semaine.', ['Lis le matin ou le soir à heure fixe.', 'Ajoute tes pages après chaque séance.'], 'c:200:pages', []],
  ['high', 'S', 'Deux documentaires et leurs idées', 'Deux documentaires dans la semaine élargissent les points de repère.', 'Regarder ou écouter 2 documentaires sur des sujets différents, et noter 3 idées retenues pour chacun.', ['Prends des notes pendant le visionnage.', 'Raconte un des deux à quelqu’un.'], 'c:2:documentaires', ['numérique']],
  ['high', 'JS', 'Session d’étude exigeante', 'Une session d’étude concentrée permet d’aborder des notions difficiles.', 'Étudier un sujet exigeant en trois temps : fixer un objectif, travailler en deux blocs concentrés avec une pause, puis te tester sans notes.', ['Fais une pause entre les deux blocs.', 'Coupe les notifications.'], 'e:Fixer un objectif précis|Travailler en deux blocs concentrés avec une pause|Faire un quiz sans notes', []],
  ['high', 'S', 'Compétence, 5 séances', 'Cinq séances sur une compétence en une semaine donnent un premier résultat concret.', 'Faire 5 séances d’apprentissage et de pratique d’une compétence sur la semaine.', ['Divise en séances courtes et régulières.', 'Fixe-toi un petit résultat à montrer.'], 'c:5:séances', []],
  ['high', 'SM', 'Un livre complet', 'Terminer un livre entier reste l’un des meilleurs rendements de temps.', 'Finir un livre ou un gros dossier sur la période et noter trois idées retenues.', ['Lis un peu chaque jour.', 'Note tes idées au fur et à mesure.'], 'e:Choisir un livre|Lire la première moitié|Finir le livre|Noter trois idées retenues', []],
  ['high', 'S', 'Deux sorties culturelles', 'Cinéma, musée, théâtre, concert : la culture se vit mieux sur place.', 'Faire 2 sorties culturelles dans la semaine : cinéma, musée, exposition, théâtre, concert ou spectacle.', ['Regarde la programmation près de chez toi.', 'Note ce qui t’a marqué après chaque sortie.'], 'c:2:sorties', ['culture']],
  ['high', 'M', 'Lecture, 600 pages dans le mois', 'Six cents pages par mois, c’est environ deux livres.', 'Lire 600 pages dans le mois, soit une vingtaine de pages par jour.', ['Lis 20 pages par jour, ou 40 un jour sur deux.', 'Alterne romans et essais.'], 'c:600:pages', []],
  ['high', 'M', 'Culture, 4 sorties dans le mois', 'Une sortie culturelle par semaine nourrit l’esprit durablement.', 'Faire 4 sorties culturelles dans le mois : cinéma, musée, exposition, théâtre, concert.', ['Planifie une sortie par semaine.', 'Note ce qui t’a marqué après chaque sortie.'], 'c:4:sorties', ['culture']],
  ['high', 'M', 'Compétence, un projet concret', 'Un résultat concret prouve qu’on a vraiment appris.', 'Apprendre une compétence en menant un projet concret jusqu’à un résultat visible : un programme, un meuble, une recette, un morceau.', ['Choisis un projet réaliste pour un mois.', 'Avance un peu chaque semaine.'], 'e:Choisir une compétence et un objectif|Pratiquer chaque semaine|Obtenir un résultat concret', []],
  // ── Légendaires (5)
  ['expert', 'M', 'Lecture, 1 000 pages dans le mois', 'Mille pages par mois, c’est trois à quatre livres.', 'Lire 1 000 pages dans le mois, soit environ 35 pages par jour.', ['Lis le matin et le soir.', 'Garde un carnet des idées marquantes.'], 'c:1000:pages', []],
  ['expert', 'ME', 'Compétence maîtrisée', 'Maîtriser une compétence demande du suivi sur la durée, avec un test final.', 'Apprendre une même compétence jusqu’à un niveau solide, avec une évaluation de départ et une évaluation finale.', ['Fixe un objectif mesurable au départ.', 'Fais le point toutes les deux semaines.'], 'e:Mesurer mon niveau de départ|Pratiquer régulièrement pendant au moins 2 mois|Valider mon niveau par un test ou un projet', []],
  ['expert', 'SM', 'Immersion d’étude, 6 séances', 'Plusieurs séances concentrées sur un seul sujet créent une vraie compréhension.', 'Faire 6 séances d’étude sur un seul sujet, en variant lecture, cours et exercices.', ['Planifie tes séances à l’avance.', 'Termine par une synthèse écrite.'], 'c:6:séances', []],
  ['expert', 'ME', 'Un sujet étudié en profondeur', 'Creuser un seul sujet jusqu’à pouvoir le présenter, c’est la forme la plus solide d’apprentissage.', 'Choisir un sujet, lire plusieurs ouvrages ou dossiers, rédiger une synthèse, puis la présenter à quelqu’un.', ['Choisis un sujet qui te passionne vraiment.', 'Écris ta synthèse en une à deux pages.'], 'e:Choisir un sujet|Lire au moins trois ouvrages ou dossiers|Rédiger une synthèse|La présenter à quelqu’un', []],
  ['expert', 'M', 'Étude structurée, 20 leçons', 'Un cours complet ou un programme de formation se termine en un mois à ce rythme.', 'Suivre 20 leçons d’un parcours d’étude structuré sur le mois : cours, exercices et révision.', ['Une leçon par jour ouvré.', 'Fais les exercices de chaque leçon.'], 'c:20:leçons', ['numérique']],
];
