// CON — Constitution : la santé du corps. Heure de coucher et de lever, repas, hydratation, marche, endurance, récupération.
// [difficulté, périodes (J/S/M/E), titre, ambiance (pourquoi), objectif, [conseils], validation, [tags]]
// validation : s | c:cible:unité | t:minutes | e:étape1|étape2 | j
export default [
  // ── Faciles (14)
  ['easy', 'J', 'Marche, 15 minutes', 'Marcher un quart d’heure par jour est le geste de santé le plus simple et le plus efficace.', 'Marcher 15 minutes d’affilée, dehors si possible, à un rythme soutenu.', ['Un peu d’air, sans écran.', 'Tu peux les répartir en deux sorties de 8 minutes.'], 't:15', ['extérieur', 'sport']],
  ['easy', 'J', 'Coucher avant 23 heures', 'Se coucher tôt allonge le sommeil et améliore l’énergie du lendemain.', 'Être couché, lumière éteinte, avant 23 heures ce soir.', ['Prépare tes affaires du lendemain avant 22 h.', 'Mets une alarme de rappel une heure avant.'], 's', ['sommeil']],
  ['easy', 'J', 'Écrans coupés 30 minutes avant dormir', 'La lumière bleue retarde l’endormissement : une demi-heure sans écran aide à s’endormir.', 'Éteindre tous les écrans (téléphone, télévision, ordinateur) 30 minutes avant de dormir.', ['Prépare une lecture ou une musique douce.', 'Mets le téléphone à charger hors de la chambre.'], 's', ['sommeil', 'détox']],
  ['easy', 'J', 'Petit-déjeuner dans l’heure du réveil', 'Un vrai petit-déjeuner stabilise l’énergie jusqu’au déjeuner.', 'Prendre un vrai petit-déjeuner (protéines et fruit) dans l’heure qui suit le réveil.', ['Œufs, yaourt, fromage blanc, pain complet.', 'Prépare-le la veille si tu manques de temps.'], 's', ['alimentation', 'matin']],
  ['easy', 'J', 'Marche après le repas, 10 minutes', 'Dix minutes de marche après manger facilitent la digestion et stabilisent la glycémie.', 'Marcher 10 minutes juste après le déjeuner ou le dîner, à un rythme tranquille.', ['Dehors de préférence.', 'Commence dans les 20 minutes après le repas.'], 't:10', ['extérieur', 'moins de 10 min']],
  ['easy', 'J', 'Lumière du jour, 10 minutes', 'La lumière du matin cale l’horloge interne et améliore le sommeil du soir.', 'Passer 10 minutes dehors à la lumière du jour avant midi.', ['Un café en terrasse ou un tour du pâté de maisons suffit.', 'Même sous les nuages, la lumière extérieure compte.'], 't:10', ['extérieur', 'matin']],
  ['easy', 'J', 'Repos sans écran, 10 minutes', 'Une courte pause aide le corps à récupérer entre deux efforts.', 'S’allonger ou s’asseoir 10 minutes, yeux fermés ou regard au loin, sans téléphone.', ['Mets un minuteur.', 'Respire lentement par le nez.'], 't:10', ['moins de 10 min', 'détox']],
  ['easy', 'J', 'Cuisiner un repas, 20 minutes', 'Cuisiner soi-même permet de maîtriser le sel, le sucre et les matières grasses.', 'Passer 20 minutes à cuisiner un plat maison avec des légumes plutôt que de commander ou réchauffer.', ['Une soupe ou une poêlée suffit.', 'Prévois une portion pour le lendemain.'], 't:20', ['cuisine', 'alimentation']],
  ['easy', 'J', 'Repas à table, 20 minutes', 'Manger lentement, sans écran, aide à reconnaître la satiété.', 'Prendre un repas assis, sans écran, en y consacrant au moins 20 minutes.', ['Pose tes couverts entre les bouchées.', 'Mâche lentement.'], 't:20', ['alimentation', 'détox']],
  ['easy', 'J', 'Marche rapide, 10 minutes', 'Une marche rapide fait monter le cœur sans fatiguer.', 'Marcher 10 minutes d’affilée à un rythme où tu peux parler mais plus chanter.', ['Balance les bras.', 'Choisis un parcours plat si tu débutes.'], 't:10', ['extérieur', 'moins de 10 min']],
  ['easy', 'J', 'Verre d’eau à chaque repas', 'Boire régulièrement évite les maux de tête et la fatigue de milieu d’après-midi.', 'Boire un grand verre d’eau au réveil, à chaque repas et en fin d’après-midi.', ['Garde une gourde à portée de main.', 'Ajoute du citron ou de la menthe si besoin.'], 'e:Au réveil|Au déjeuner|En fin d’après-midi|Au dîner', ['alimentation']],
  ['easy', 'J', 'Réveil à heure régulière', 'Un réveil stable cale le rythme du corps, même le week-end.', 'Se réveiller à la même heure qu’hier, à 30 minutes près.', ['Mets l’alarme à la même heure chaque jour.', 'Évite de te rendormir après la première alarme.'], 's', ['sommeil', 'matin']],
  ['easy', 'J', 'Dîner 2 heures avant le coucher', 'Un dîner trop tardif gêne la digestion et le sommeil.', 'Terminer le dernier repas au moins 2 heures avant l’heure du coucher.', ['Prévois le dîner à heure fixe.', 'Une tisane suffit si tu as faim plus tard.'], 's', ['alimentation', 'sommeil']],
  ['easy', 'J', 'Posture et dos, 5 minutes', 'Des exercices de posture soulagent le dos après de longues heures assis.', 'Pendant 5 minutes, faire des exercices de posture : redressement, rétraction des épaules, étirement de la nuque.', ['Place le dos contre un mur, talons, fesses, épaules et tête collés.', 'Respire profondément pendant chaque mouvement.'], 't:5', ['sans matériel', 'moins de 10 min']],
  // ── Modérées (12)
  ['medium', 'JS', 'Marche rapide, 30 minutes', 'Trente minutes de marche rapide entretiennent le cœur et les articulations.', 'Marcher 30 minutes d’affilée à bon rythme.', ['Choisis un parcours que tu aimes.', 'Un rythme où tu peux parler mais plus chanter.'], 't:30', ['extérieur', 'sport']],
  ['medium', 'JS', 'Cardio, 20 minutes', 'Le cardio régulier améliore l’endurance et l’humeur.', 'Courir, pédaler ou nager 20 minutes à une allure où tu peux encore parler.', ['Alterne course et marche si besoin.', 'Échauffe-toi 3 minutes à allure lente.'], 't:20', ['sport']],
  ['medium', 'S', 'Coucher régulier, 5 nuits sur 7', 'Une heure de coucher stable est l’un des meilleurs leviers de santé.', 'Te coucher à heure fixe (± 30 minutes) 5 soirs sur 7.', ['Fixe une alarme de coucher.', 'Garde le même horaire le week-end.'], 'c:5:nuits', ['sommeil']],
  ['medium', 'J', 'Hydratation toute la journée', 'Boire régulièrement vaut mieux que boire beaucoup d’un coup.', 'Boire un verre d’eau toutes les 2 heures, de 8 h à 18 h.', ['Mets des alarmes discrètes.', 'Garde une bouteille visible sur ton bureau.'], 'e:8 h|10 h|12 h|14 h|16 h|18 h', ['alimentation']],
  ['medium', 'JS', 'Vélo ou natation, 30 minutes', 'Un cardio sans impact ménage les articulations tout en entraînant le souffle.', 'Faire 30 minutes de vélo (réel ou d’appartement) ou de natation à un rythme soutenu.', ['Règle bien la selle.', 'Varie les allures.'], 't:30', ['sport']],
  ['medium', 'S', 'Cuisine maison, 5 repas', 'Cuisiner maison est la façon la plus simple de mieux manger sans régime.', 'Cuisiner au moins 5 repas maison dans la semaine.', ['Prépare un menu le dimanche.', 'Cuisine en double pour le lendemain.'], 'c:5:repas', ['cuisine', 'alimentation']],
  ['medium', 'JS', 'Repas lent et sans écran, 30 minutes', 'Un repas lent améliore la digestion et réduit les grignotages.', 'Prendre un repas complet assis, sans écran, en y consacrant au moins 30 minutes.', ['Pose tes couverts entre les bouchées.', 'Arrête-toi quand tu n’as plus faim.'], 't:30', ['alimentation', 'détox']],
  ['medium', 'S', 'Réveil régulier, 5 jours sur 7', 'Un réveil régulier stabilise l’énergie de toute la journée.', 'Te réveiller à heure fixe (± 30 minutes) 5 jours sur 7.', ['Garde le même réveil le week-end.', 'Ouvre les volets dès le lever.'], 'c:5:jours', ['sommeil', 'matin']],
  ['medium', 'J', 'Marche et étirements du soir, 30 minutes', 'Une activité douce le soir aide à se détendre avant de dormir.', 'Passer 30 minutes en fin de journée à marcher puis à t’étirer tranquillement.', ['Termine au moins une heure avant le coucher.', 'Dehors si possible.'], 't:30', ['extérieur', 'sommeil']],
  ['medium', 'S', 'Marche, 150 minutes dans la semaine', 'Cent cinquante minutes par semaine, c’est la recommandation générale de santé.', 'Cumuler 150 minutes de marche sur la semaine, en plusieurs fois.', ['30 minutes, 5 jours sur 7.', 'Ajoute tes minutes après chaque sortie.'], 'c:150:minutes', ['extérieur', 'sport']],
  ['medium', 'JS', 'Sortie en extérieur, 45 minutes', 'Une longue sortie à pied ou à vélo combine endurance et exposition à la lumière.', 'Faire une sortie de 45 minutes à pied ou à vélo, dehors, à un rythme régulier.', ['Emporte de l’eau.', 'Prends un chemin que tu ne connais pas.'], 't:45', ['extérieur', 'sport']],
  ['medium', 'S', 'Écrans coupés avant dormir, 5 soirs', 'Une habitude répétée finit par s’installer : cinq soirs, c’est un bon début.', 'Éteindre tous les écrans 30 minutes avant de dormir, 5 soirs sur 7.', ['Remplace par la lecture ou la discussion.', 'Mets le téléphone dans une autre pièce.'], 'c:5:soirs', ['sommeil', 'détox']],
  // ── Audacieuses (9)
  ['high', 'S', 'Cardio, 150 minutes dans la semaine', 'Cent cinquante minutes de cardio par semaine abaissent nettement les risques de santé.', 'Cumuler 150 minutes de cardio (course, vélo, natation, marche rapide) sur la semaine.', ['Trois séances de 50 minutes ou cinq de 30.', 'Reste à une allure où tu peux parler.'], 'c:150:minutes', ['sport']],
  ['high', 'S', 'Dormir 7 à 9 heures, 6 nuits', 'Sept à neuf heures de sommeil, c’est la durée dont la plupart des adultes ont besoin.', 'Dormir entre 7 et 9 heures par nuit, 6 nuits sur 7.', ['Prépare ta chambre : fraîche, sombre, silencieuse.', 'Garde le même réveil le week-end.'], 'c:6:nuits', ['sommeil']],
  ['high', 'JS', 'Longue marche, 90 minutes', 'Une longue marche entretient l’endurance de base et clarifie l’esprit.', 'Faire une sortie de 90 minutes à pied à un rythme régulier.', ['Emporte de l’eau et une collation.', 'Alterne montées et portions plates.'], 't:90', ['extérieur', 'sport']],
  ['high', 'S', 'Repas maison équilibré, 7 jours', 'Sept jours de repas équilibrés installent de nouvelles habitudes alimentaires.', 'Cuisiner un repas maison équilibré (protéine, légume, féculent) chaque jour pendant 7 jours.', ['Prépare les bases le dimanche.', 'Cuisine en double pour le lendemain.'], 'c:7:jours', ['cuisine', 'alimentation']],
  ['high', 'SM', 'Cardio, 60 minutes cumulées', 'Une heure de cardio cumulée est un excellent minimum d’entretien.', 'Cumuler 60 minutes de cardio sur la période : course, vélo, natation, marche rapide.', ['Séances de 20 à 30 minutes.', 'Garde une allure confortable.'], 'c:60:minutes', ['sport']],
  ['high', 'S', 'Coucher fixe, 7 soirs sur 7', 'Une semaine sans exception, c’est la meilleure façon de caler son rythme.', 'Te coucher à heure fixe (± 30 minutes) tous les soirs pendant 7 jours.', ['Suis-le dans un calendrier.', 'Prévois une alarme de rappel une heure avant.'], 'c:7:nuits', ['sommeil']],
  ['high', 'M', 'Coucher régulier, 20 nuits dans le mois', 'Un mois de nuits régulières reconstruit le sommeil en profondeur.', 'Te coucher à heure fixe (± 30 minutes) au moins 20 nuits dans le mois.', ['Suis ton coucher dans un calendrier.', 'Ne rattrape pas le retard par une grasse matinée.'], 'c:20:nuits', ['sommeil']],
  ['high', 'M', 'Marche, 12 heures dans le mois', 'Douze heures de marche par mois, c’est environ 25 minutes par jour.', 'Cumuler 12 heures de marche sur le mois.', ['Intègre la marche à un trajet quotidien.', 'Ajoute tes minutes après chaque sortie.'], 'c:720:minutes', ['extérieur', 'sport']],
  ['high', 'M', 'Cardio, 10 heures dans le mois', 'Dix heures de cardio par mois installent une bonne base d’endurance.', 'Cumuler 10 heures de cardio sur le mois : course, vélo, natation, marche rapide.', ['Trois séances par semaine de 45 minutes.', 'Varie les activités pour t’amuser.'], 'c:600:minutes', ['sport']],
  // ── Légendaires (5)
  ['expert', 'M', 'Sommeil régulier, 30 nuits', 'Trente nuits de rythme régulier changent l’énergie, l’humeur et la santé.', 'Te coucher et te lever à heure régulière (± 30 minutes) pendant 30 nuits dans le mois. Adapte à ta condition.', ['Choisis un horaire réaliste.', 'Garde-le même le week-end.'], 'c:30:nuits', ['sommeil']],
  ['expert', 'ME', 'Endurance, 40 heures cumulées', 'Quarante heures d’endurance cumulées bâtissent une vraie condition physique.', 'Cumuler 40 heures de marche, course, vélo ou natation. Adapte à ta condition et consulte un professionnel au besoin.', ['Fixe un volume hebdomadaire réaliste.', 'Prévois des semaines plus légères.'], 'c:2400:minutes', ['sport']],
  ['expert', 'SM', 'Semaine santé, 7 jours', 'Sept jours où sommeil, repas, eau et marche sont tenus ensemble.', 'Pendant 7 jours : dormir 7 à 9 heures, marcher 30 minutes, boire 1,5 L d’eau et manger équilibré chaque jour. Adapte à ta condition.', ['Coche chaque jour avant de te coucher.', 'Prévois les repas à l’avance.'], 'c:7:jours', ['sport', 'sommeil', 'alimentation']],
  ['expert', 'ME', 'Grande distance, 30 heures', 'Trente heures d’endurance cumulées peuvent mener à un grand objectif : semi-marathon, grande randonnée.', 'Cumuler 30 heures de préparation à un objectif d’endurance (course, marche, vélo). Adapte à ta condition.', ['Fixe une date et un objectif.', 'Augmente le volume progressivement.'], 'c:1800:minutes', ['sport']],
  ['expert', 'M', 'Un mois de cuisine maison', 'Un mois de repas maison est le plus gros changement alimentaire possible sans régime.', 'Cuisiner au moins 25 repas maison dans le mois.', ['Planifie un menu hebdomadaire.', 'Prépare en batch le dimanche.'], 'c:25:repas', ['cuisine', 'alimentation']],
];
