// DEX — Dextérité : l’agilité sous toutes ses formes. Souplesse, équilibre, coordination, réflexes, adresse manuelle, vivacité d’esprit.
// [difficulté, périodes (J/S/M/E), titre, ambiance (pourquoi), objectif, [conseils], validation, [tags]]
// validation : s | c:cible:unité | t:minutes | e:étape1|étape2 | j
export default [
  // ── Faciles (14)
  ['easy', 'J', 'Étirements complets, 5 minutes', 'Un corps souple se blesse moins et bouge avec plus d’aisance.', 'Pendant 5 minutes, étirer successivement nuque, épaules, dos, hanches, cuisses et mollets, 30 secondes par zone.', ['Étire sans douleur : une tension douce suffit.', 'Respire lentement pendant chaque étirement.'], 't:5', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Équilibre sur une jambe, 5 minutes', 'L’équilibre se travaille comme un muscle et protège contre les chutes.', 'Pendant 5 minutes, tenir en équilibre sur une jambe puis sur l’autre, en alternant, yeux ouverts puis yeux fermés.', ['Reste près d’un mur pour te rattraper.', 'Fixe un point devant toi pour tenir plus longtemps.'], 't:5', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Jonglage, 10 minutes', 'Le jonglage entraîne la coordination œil-main et la concentration.', 'Pendant 10 minutes, s’exercer à jongler avec trois balles, des foulards ou des chaussettes roulées.', ['Commence avec une seule balle, puis deux.', 'Lance à hauteur des yeux, sans bouger les pieds.'], 't:10', ['moins de 10 min']],
  ['easy', 'J', 'Mobilité épaules et hanches, 5 minutes', 'Ces deux articulations limitent beaucoup de gestes : elles méritent un travail régulier.', 'Pendant 5 minutes, faire des rotations lentes et amples des épaules, des hanches, du bassin et du cou.', ['Fais des cercles larges et contrôlés.', 'Change de sens à mi-parcours.'], 't:5', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Corde à sauter, 5 minutes', 'Sauter à la corde améliore le rythme, la coordination et la légèreté des appuis.', 'Pendant 5 minutes, sauter à la corde (ou mimer le geste sans corde) en séries de 30 secondes.', ['Saute bas, sur la pointe des pieds.', 'Les poignets tournent, pas les bras.'], 't:5', ['moins de 10 min', 'sport']],
  ['easy', 'J', 'Calcul mental rapide, 5 minutes', 'La vitesse de calcul mental entretient la vivacité d’esprit.', 'Pendant 5 minutes, résoudre des calculs mentaux sans calculatrice, en essayant d’aller plus vite à chaque série.', ['Commence par des additions, puis des multiplications.', 'Chronomètre une série de 10 calculs pour te mesurer.'], 't:5', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Écriture de la main faible, 5 minutes', 'Utiliser l’autre main bouscule les habitudes du cerveau et affine le geste.', 'Pendant 5 minutes, écrire ou dessiner de la main non dominante, en visant la lisibilité plus que la vitesse.', ['Écris des lignes de lettres simples.', 'Détends ton poignet.'], 't:5', ['moins de 10 min']],
  ['easy', 'J', 'Dactylographie, 10 minutes', 'Taper vite et sans regarder le clavier fait gagner du temps chaque jour.', 'Pendant 10 minutes, s’entraîner à la dactylographie sur un exercice en ligne ou sur un texte recopié sans regarder le clavier.', ['Garde les doigts sur la rangée centrale.', 'Vise la précision avant la vitesse.'], 't:10', ['numérique']],
  ['easy', 'J', 'Pas de coordination, 5 minutes', 'Coordonner bras et jambes dans un rythme demande au corps d’apprendre vite.', 'Pendant 5 minutes, enchaîner pas chassés, pas croisés et sauts latéraux en suivant un rythme régulier.', ['Compte les temps à voix haute.', 'Commence lentement et accélère peu à peu.'], 't:5', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Réflexes contre un mur, 5 minutes', 'Rattraper une balle améliore la vitesse de réaction et la précision.', 'Pendant 5 minutes, lancer une balle contre un mur et la rattraper, avec une main puis l’autre.', ['Éloigne-toi peu à peu du mur.', 'Passe à des rebonds imprévisibles quand tu es à l’aise.'], 't:5', ['moins de 10 min']],
  ['easy', 'J', 'Casse-tête de logique, 10 minutes', 'Résoudre un problème sous contrainte de temps rend l’esprit plus réactif.', 'Pendant 10 minutes, résoudre des casse-tête de logique : sudoku, grilles, énigmes ou puzzles.', ['Passe au suivant si tu bloques plus de deux minutes.', 'Note ton meilleur temps.'], 't:10', ['jeu']],
  ['easy', 'J', 'Mobilité du dos, 5 minutes', 'Un dos mobile facilite tous les mouvements du quotidien.', 'Pendant 5 minutes, enchaîner des exercices de mobilité du dos : chat-vache, rotations, bascule du bassin.', ['Bouge lentement avec la respiration.', 'Reste dans une amplitude confortable.'], 't:5', ['sans matériel', 'moins de 10 min', 'sport']],
  ['easy', 'J', 'Nœuds et origami, 10 minutes', 'Les gestes fins entraînent la précision des doigts et la patience.', 'Pendant 10 minutes, apprendre ou pratiquer des nœuds, un origami ou un autre travail manuel fin.', ['Suis un tutoriel court au début.', 'Reprends le même pliage plusieurs fois pour aller plus vite.'], 't:10', ['moins de 10 min']],
  ['easy', 'J', 'Danse libre, 10 minutes', 'Bouger au rythme de la musique entraîne la coordination et l’expression corporelle.', 'Pendant 10 minutes, danser librement sur de la musique, en variant les mouvements et les rythmes.', ['Choisis une musique qui donne envie de bouger.', 'Teste des mouvements que tu n’as jamais faits.'], 't:10', ['sans matériel', 'sport']],
  // ── Modérées (12)
  ['medium', 'JS', 'Séance de souplesse, 20 minutes', 'Une séance complète apporte des gains de souplesse plus durables que quelques étirements.', 'Pendant 20 minutes, faire une séance de souplesse en tenant chaque étirement 30 à 45 secondes, sur tout le corps.', ['Échauffe-toi 2 minutes avant.', 'Respire lentement et relâche un peu plus à chaque expiration.'], 't:20', ['sport']],
  ['medium', 'JS', 'Équilibre et proprioception, 15 minutes', 'Travailler l’équilibre sollicite les petits muscles stabilisateurs des chevilles et des genoux.', 'Pendant 15 minutes, enchaîner des exercices d’équilibre : une jambe, yeux fermés, coussin instable, déplacements lents.', ['Prévois un appui proche pour te rattraper.', 'Augmente la difficulté progressivement.'], 't:15', ['sport']],
  ['medium', 'S', 'Mobilité, 60 minutes dans la semaine', 'Quelques séances courtes de mobilité valent mieux qu’une longue séance isolée.', 'Cumuler 60 minutes de mobilité ou d’étirements sur la semaine, en plusieurs séances.', ['Quatre séances de 15 minutes conviennent.', 'Ajoute tes minutes après chaque séance.'], 'c:60:minutes', ['sport']],
  ['medium', 'J', 'Jonglage progressif, 15 minutes', 'Passer à des figures plus complexes développe la coordination fine.', 'Pendant 15 minutes, s’entraîner à enchaîner des cascades de trois balles ou à apprendre une nouvelle figure de jonglage.', ['Compte le nombre de lancers sans chute et bats ton record.', 'Alterne séries courtes et pauses.'], 't:15', ['moins de 20 min']],
  ['medium', 'JS', 'Corde à sauter, 15 minutes', 'Le travail à la corde développe l’agilité des appuis et l’endurance.', 'Pendant 15 minutes, sauter à la corde en alternant pas simples, pieds joints et pas de course.', ['Alterne 1 minute d’effort et 30 secondes de repos.', 'Choisis un sol qui amortit.'], 't:15', ['sport']],
  ['medium', 'S', 'Geste précis, 90 minutes dans la semaine', 'La pratique régulière d’un geste précis (instrument, dessin, couture, modélisme) affine la dextérité manuelle.', 'Cumuler 90 minutes de pratique manuelle précise sur la semaine : instrument, dessin, couture, bricolage fin.', ['Des séances de 15 à 30 minutes suffisent.', 'Choisis une seule activité pour progresser.'], 'c:90:minutes', ['bricolage']],
  ['medium', 'JS', 'Sport de réflexes, 20 minutes', 'Les sports de raquette ou de balle entraînent la vitesse de réaction et le placement.', 'Pendant 20 minutes, pratiquer un jeu de réflexes : tennis de table, badminton, ballon, boxe contre une cible.', ['Joue avec un ami si possible.', 'Reste sur la pointe des pieds, prêt à repartir.'], 't:20', ['sport', 'extérieur']],
  ['medium', 'J', 'Agilité mentale, 20 minutes', 'Une série de problèmes variés entraîne le passage rapide d’une idée à l’autre.', 'Pendant 20 minutes, alterner logique, calcul mental, mots croisés et énigmes, en changeant de type d’exercice toutes les 5 minutes.', ['Change d’exercice même quand tu es lancé.', 'Note les types que tu fais le plus lentement.'], 't:20', ['jeu']],
  ['medium', 'S', 'Yoga ou assouplissements, 60 minutes', 'Le yoga combine souplesse, équilibre et concentration.', 'Cumuler 60 minutes de yoga ou d’assouplissements dirigés sur la semaine.', ['Une vidéo guidée aide à suivre le rythme.', 'Ne force jamais une posture.'], 'c:60:minutes', ['sport']],
  ['medium', 'JS', 'Parcours d’agilité, 20 minutes', 'Slalomer, sauter et changer de direction entraîne les appuis et la vivacité.', 'Pendant 20 minutes, faire un parcours d’agilité : slalom entre des plots, sauts latéraux, échelle de rythme, changements de direction.', ['Marque le parcours avec des bouteilles ou des chaussures.', 'Chronomètre un tour et cherche à le battre.'], 't:20', ['sport', 'extérieur']],
  ['medium', 'S', 'Activité de coordination, 45 minutes', 'Découvrir un nouveau mouvement oblige le cerveau à s’adapter.', 'Cumuler 45 minutes sur une activité de coordination nouvelle pour toi : danse, escalade, arts martiaux, patin, slackline.', ['Choisis une activité accessible près de chez toi.', 'Fais-le même si tu te sens maladroit au début.'], 'c:45:minutes', ['sport']],
  ['medium', 'JS', 'Dactylographie rapide, 20 minutes', 'La vitesse de frappe se gagne par séances courtes et régulières.', 'Pendant 20 minutes, s’exercer à la dactylographie avec des tests chronométrés et des exercices de précision.', ['Passe sur des textes longs pour tenir la cadence.', 'Corrige d’abord les erreurs récurrentes.'], 't:20', ['numérique']],
  // ── Audacieuses (9)
  ['high', 'S', 'Souplesse, 120 minutes dans la semaine', 'Deux heures de souplesse par semaine débloquent des amplitudes que les séances courtes ne donnent pas.', 'Cumuler 120 minutes de travail de souplesse sur la semaine : étirements, yoga, mobilité.', ['Prévois quatre séances de 30 minutes.', 'Reste à la limite de la gêne, pas de la douleur.'], 'c:120:minutes', ['sport']],
  ['high', 'S', 'Coordination, 90 minutes dans la semaine', 'Un volume de pratique régulier en coordination change la façon de bouger.', 'Cumuler 90 minutes de coordination sur la semaine : danse, arts martiaux, escalade, sports de balle.', ['Alterne des séances techniques et des séances de jeu.', 'Note une chose améliorée à chaque séance.'], 'c:90:minutes', ['sport']],
  ['high', 'JS', 'Yoga ou assouplissements, 45 minutes', 'Une séance longue permet d’aller jusqu’à des postures plus exigeantes.', 'Pendant 45 minutes, faire une séance complète de yoga ou d’assouplissements, avec échauffement et retour au calme.', ['Prépare un tapis et un espace dégagé.', 'Suis un cours en ligne pour ne pas t’arrêter.'], 't:45', ['sport']],
  ['high', 'S', 'Habileté manuelle, 120 minutes', 'Deux heures de pratique manuelle par semaine donnent des progrès visibles en dextérité.', 'Cumuler 120 minutes de pratique manuelle précise sur la semaine : instrument, dessin, couture, maquette, jonglage.', ['Planifie des séances de 20 à 30 minutes.', 'Fixe un objectif simple pour la semaine.'], 'c:120:minutes', ['bricolage']],
  ['high', 'SM', 'Jonglage, 60 minutes cumulées', 'Une heure de jonglage cumulée suffit en général pour maîtriser la cascade de trois balles.', 'Cumuler 60 minutes de pratique du jonglage sur la période, jusqu’à enchaîner au moins 30 lancers.', ['Entraîne-toi par séances courtes.', 'Filme-toi pour repérer les fautes.'], 'c:60:minutes', ['moins de 20 min']],
  ['high', 'S', 'Agilité mentale, 90 minutes', 'Jouer à des jeux de stratégie et de logique entraîne la vitesse de réflexion.', 'Cumuler 90 minutes de jeux d’agilité mentale sur la semaine : échecs, logique, calcul, jeux de réflexes.', ['Joue des parties rapides pour forcer la vitesse.', 'Analyse une partie perdue.'], 'c:90:minutes', ['jeu']],
  ['high', 'M', 'Mobilité, 5 heures dans le mois', 'Cinq heures de mobilité par mois, c’est 10 minutes par jour, trois jours sur quatre.', 'Cumuler 5 heures de mobilité, d’étirements ou de yoga sur le mois.', ['Garde un créneau fixe chaque jour.', 'Ajoute tes minutes dans le compteur après chaque séance.'], 'c:300:minutes', ['sport']],
  ['high', 'M', 'Pratique manuelle, 6 heures', 'Six heures de pratique manuelle en un mois suffisent à apprendre un geste complexe.', 'Cumuler 6 heures de pratique d’un geste précis sur le mois : instrument, dessin, modélisme, couture, calligraphie.', ['Choisis une seule activité.', 'Note ta progression chaque semaine.'], 'c:360:minutes', ['bricolage']],
  ['high', 'M', 'Sport de coordination, 6 heures', 'Un mois de pratique régulière transforme la coordination.', 'Cumuler 6 heures de sport de coordination sur le mois : escalade, danse, arts martiaux, sports de raquette.', ['Cherche un cours ou un club près de chez toi.', 'Mélange séances techniques et séances ludiques.'], 'c:360:minutes', ['sport']],
  // ── Légendaires (5)
  ['expert', 'M', 'Souplesse, 10 heures dans le mois', 'Dix heures de souplesse par mois, c’est une vraie transformation du corps.', 'Cumuler 10 heures de souplesse, de yoga et de mobilité sur le mois. Adapte à ta condition et ne force jamais une articulation.', ['Planifie des séances courtes presque chaque jour.', 'Mesure ta souplesse au départ (toucher les pieds) et à la fin.'], 'c:600:minutes', ['sport']],
  ['expert', 'ME', 'Geste maîtrisé, 20 heures', 'Vingt heures suffisent pour acquérir un geste précis dans une nouvelle pratique.', 'Cumuler 20 heures de pratique d’un geste manuel précis : instrument, dessin, couture, calligraphie, jonglage, lancer.', ['Choisis un objectif visible (un morceau, un dessin, une figure).', 'Garde une trace de chaque séance.'], 'c:1200:minutes', ['bricolage']],
  ['expert', 'SM', 'Agilité totale, 4 heures', 'Souplesse, réflexes, équilibre et coordination : toutes les formes d’agilité en quatre heures.', 'Cumuler 4 heures de pratique d’agilité variée : souplesse, équilibre, coordination et réflexes. Adapte à ta condition.', ['Répartis en séances de 30 à 45 minutes.', 'Change de type d’exercice à chaque séance.'], 'c:240:minutes', ['sport']],
  ['expert', 'ME', 'Activité de coordination, 30 heures', 'Trente heures suffisent pour passer d’un débutant maladroit à un pratiquant à l’aise.', 'Cumuler 30 heures de pratique d’une activité de coordination : danse, escalade, arts martiaux, sports de raquette. Adapte à ta condition.', ['Inscris-toi à un cours pour progresser plus vite.', 'Fixe-toi un petit objectif de démonstration.'], 'c:1800:minutes', ['sport']],
  ['expert', 'M', 'Agilité mentale, 12 heures', 'Douze heures de stratégie et de logique dans le mois forment un esprit vif et rapide.', 'Cumuler 12 heures de jeux de stratégie, de logique ou de calcul sur le mois : échecs, go, énigmes, calcul mental.', ['Joue contre quelqu’un de plus fort que toi.', 'Reviens sur tes erreurs après chaque partie.'], 'c:720:minutes', ['jeu']],
];
