// FOR — Courage : la puissance du geste franc, soulever, tenir, oser.
// [difficulté, périodes (J/S/M/E), titre, ambiance, objectif, [conseils], validation, [tags]]
// validation : s | c:cible:unité | t:minutes | e:étape1|étape2 | j
export default [
  // ── Faciles (14)
  ['easy', 'J', 'Le Salut du Forgeron', 'Avant d’allumer la forge, le forgeron éveille ses bras. Fais de même avant que la journée ne t’emporte.', 'Faire 20 pompes (sur les genoux autorisé), en une ou plusieurs séries.', ['Mieux vaut cinq séries propres qu’une série bâclée.', 'Expire en poussant, inspire en descendant.'], 'c:20:pompes', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'L’Échauffement du Soldat', 'Le soldat qui s’échauffe ne boite pas à la première marche. Tes jambes t’en remercieront.', 'Faire 30 squats, dos droit, talons au sol.', ['Imagine que tu t’assois sur une chaise derrière toi.', 'Descends moins bas si tes genoux tirent.'], 'c:30:squats', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'La Garde du Rempart', 'La sentinelle ne bouge pas, mais elle ne s’effondre pas non plus. Tenir est un art.', 'Tenir 1 minute de gainage (planche) au total, en une ou plusieurs fois.', ['Les coudes sous les épaules, le corps droit comme une lance.', 'Fractionne en 3 × 20 secondes si besoin.'], 't:1', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Les Marches du Beffroi', 'Les cloches sonnent mieux pour ceux qui ont gravi la tour. L’ascenseur est une facilité de roi.', 'Prendre les escaliers pour au moins 3 étages, au lieu de l’ascenseur.', ['Garde un rythme régulier, sans te presser.', 'Pas d’escaliers ? Une côte ou un trottoir en pente fait l’affaire.'], 's', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Le Réveil de la Forteresse', 'Une forteresse bien gardée commence par des fondations solides. Les tiennes passent par le ventre.', 'Faire 3 séries de 10 abdominaux ou relevés de jambes.', ['Ne tire pas sur la nuque : les mains près des tempes.', 'Souffle pendant l’effort.'], 'c:30:répétitions', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'La Bravade du Matin', 'Les gardes du nord se lavent à l’eau du torrent. Ils disent que la peur fond avant la glace.', 'Terminer ta douche par 30 secondes d’eau fraîche, si ta santé le permet.', ['Respire lentement : l’expiration longue calme le choc.', 'Commence par les jambes, puis remonte.'], 's', ['sans matériel', 'défi']],
  ['easy', 'J', 'Le Non du Rempart', 'Une porte qui ne se ferme jamais n’est plus une porte. Savoir refuser protège ce qui compte.', 'Refuser poliment une demande ou une invitation dont tu n’as pas envie.', ['Une phrase courte suffit : « Merci, mais ce n’est pas possible pour moi. »', 'Pas besoin de te justifier longuement.'], 's', ['social', 'sans matériel']],
  ['easy', 'J', 'Le Pas de Côté', 'Le voyageur qui quitte la grand-route découvre des chemins que personne ne lui avait montrés.', 'Essayer une petite nouveauté : un autre trajet, un plat, un rayon, un morceau inconnu.', ['Cela doit être nouveau pour toi, pas spectaculaire.', 'Note ce que tu as ressenti en une phrase.'], 's', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'La Charge du Porteur', 'Les caravanes ne traversent pas les cols toutes seules. Quelqu’un porte les vivres.', 'Faire 10 soulevés de charge (sac chargé de livres, packs d’eau) en gardant le dos droit.', ['Fléchis les genoux, pas le dos.', 'Choisis une charge qui reste confortable.'], 'c:10:soulevés', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Le Cheval de Bois', 'Le cavalier novice apprend d’abord sur un cheval qui ne bouge pas. Ses cuisses s’en souviennent.', 'Tenir 30 secondes en position de chaise contre un mur, deux fois.', ['Les cuisses parallèles au sol si possible.', 'Respire, ne retiens pas ton souffle.'], 'c:2:séries', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'La Parole Franche', 'Le héraut n’étouffe pas les mauvaises nouvelles. Il les annonce avec respect, et le royaume s’en porte mieux.', 'Dire à quelqu’un une chose vraie mais difficile, avec bienveillance.', ['Parle de ce que tu ressens, pas de ce qu’il est.', 'Choisis un moment calme.'], 's', ['social', 'sans matériel']],
  ['easy', 'J', 'Les Fentes du Chevalier', 'Le chevalier avance toujours d’un pied ferme. Mille fentes ont précédé son premier tournoi.', 'Faire 20 fentes (10 par jambe), buste droit.', ['Le genou avant ne dépasse pas la pointe du pied.', 'Appuie-toi sur un mur si l’équilibre manque.'], 'c:20:fentes', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'Le Pas Redoublé', 'Le tambour bat la cadence. Ceux qui suivent le rythme arrivent plus loin qu’ils ne l’espéraient.', 'Faire 3 fois 1 minute de jumping jacks ou de montées de genoux, avec 30 secondes de pause.', ['Garde un rythme que tu peux tenir.', 'Les bras suivent le mouvement des jambes.'], 'c:3:séries', ['sans matériel', 'moins de 10 min']],
  ['easy', 'J', 'La Poignée de Fer', 'La poignée de main d’un chef de guilde vaut un contrat. La tienne en dit plus que ta carte de visite.', 'Serrer un objet (balle, serviette roulée) 20 fois par main, ou tenir 30 secondes de suspension à une barre.', ['Contracte fort, relâche complètement.', 'Arrête-toi si tu sens une douleur vive.'], 's', ['sans matériel', 'moins de 10 min']],
  // ── Modérées (12)
  ['medium', 'JS', 'Le Fardeau du Porteur', 'Les caravanes ne traversent pas les cols toutes seules. Aujourd’hui, c’est toi qui portes les vivres.', 'Faire une séance de renforcement de 30 minutes : pompes, squats, gainage, fentes.', ['Alterne les exercices pour ne pas te lasser.', 'Un échauffement de 3 minutes avant, des étirements après.'], 't:30', ['sans matériel', 'sport']],
  ['medium', 'JS', 'Le Cercle du Gymnaste', 'Dans la cour des gardes, on s’entraîne sans salle ni armure. Le sol et le poids du corps suffisent.', 'Enchaîner 4 tours de : 10 pompes, 15 squats, 20 secondes de planche.', ['Repose-toi 1 minute entre les tours.', 'Garde la qualité du geste avant la vitesse.'], 'c:4:tours', ['sans matériel', 'sport']],
  ['medium', 'S', 'L’Audace du Voyageur', 'Certains pays ne s’atteignent qu’en poussant une porte inconnue. Oser est la moitié du voyage.', 'Entrer seul dans un lieu où tu ne vas jamais (cours, café, salle, atelier) et y rester au moins 20 minutes.', ['Prépare une phrase d’entrée : « Bonjour, c’est ma première fois. »', 'Il n’y a rien à prouver.'], 's', ['social', 'extérieur']],
  ['medium', 'J', 'La Lame Affûtée', 'Une lame s’émousse sans entretien. Quelques minutes bien employées valent mieux qu’un rattrapage héroïque.', 'Faire 15 minutes de renforcement ciblé sur un point faible : dos, épaules ou jambes.', ['Choisis deux exercices et fais-les bien.', 'Compte tes répétitions pour mesurer ta progression.'], 't:15', ['sans matériel', 'sport']],
  ['medium', 'JS', 'Les Murailles de la Cité', 'La cité tient parce que chaque pierre porte son poids. Toi, tu portes les tiennes.', 'Faire 60 pompes, 80 squats et 3 minutes de gainage au total sur la journée.', ['Répartis par séries courtes tout au long de la journée.', 'Compte au fur et à mesure.'], 'c:3:séries', ['sans matériel', 'sport']],
  ['medium', 'S', 'La Parole du Héraut', 'Le héraut tremble avant de parler. Puis la place se tait, et c’est lui qui décide de la suite.', 'Prendre la parole en réunion, en cours ou en groupe pour donner ton avis ou poser une question.', ['Prépare une phrase d’ouverture.', 'Parle un peu plus lentement que ce qui te semble naturel.'], 's', ['social', 'sans matériel']],
  ['medium', 'JS', 'Le Port du Bouclier', 'Un bouclier lourd ne se porte pas d’un bras mou. Il se mérite, répétition après répétition.', 'Faire 20 minutes de travail avec charge (haltères, sac lesté, bidons d’eau) en gardant un geste propre.', ['Charge modérée, mouvement lent.', 'Termine par 2 minutes d’étirements.'], 't:20', ['sport']],
  ['medium', 'J', 'La Peur Apprivoisée', 'Même le plus redouté des dragons a eu un premier jour. Le tien commence en regardant ta peur en face.', 'Faire une chose que tu repousses depuis longtemps et qui te fait un peu peur (appel, démarche, message).', ['Découpe-la en un premier geste de 5 minutes.', 'Fais-la avant midi pour ne pas la porter toute la journée.'], 's', ['sans matériel']],
  ['medium', 'S', 'Le Chemin des Cimes', 'On n’atteint pas le col sans monter. Chaque pente est un passage de grade.', 'Faire une marche ou randonnée avec au moins 200 m de dénivelé positif.', ['Prends de l’eau et un coupe-vent.', 'Monte à ton rythme, sans te presser.'], 's', ['extérieur', 'sport']],
  ['medium', 'JS', 'La Joute du Matin', 'À l’aube, la lice est vide. Ceux qui s’y entraînent déjà ont une avance que personne ne verra.', 'Faire 25 minutes de sport avant 9 h.', ['Prépare tes affaires la veille.', 'Commence doucement les 5 premières minutes.'], 't:25', ['sport']],
  ['medium', 'S', 'Le Nouveau Sentier', 'Les cartes sont toujours incomplètes. C’est aux aventuriers de les remplir.', 'Essayer une activité que tu n’as jamais faite (escalade, danse, cuisine d’un pays, atelier) pendant au moins 30 minutes.', ['Choisis l’activité qui t’intrigue le plus.', 'Les débutants sont les bienvenus presque partout.'], 's', ['extérieur']],
  ['medium', 'JS', 'Le Pas de l’Éclaireur', 'L’éclaireur court devant l’armée, léger, pour voir ce que les autres ne voient pas encore.', 'Faire 5 séries de 30 secondes de montées de genoux ou de burpees, avec 30 secondes de repos.', ['Adapte l’intensité à ta forme du jour.', 'Bois quelques gorgées d’eau après.'], 'c:5:séries', ['sans matériel', 'sport']],
  // ── Audacieuses (9)
  ['high', 'S', 'Le Siège de la Tour', 'Une tour ne tombe pas en un assaut. Elle cède sous la répétition des coups.', 'Faire 4 séances de musculation ou de renforcement de 45 minutes dans la semaine.', ['Place-les un jour sur deux pour récupérer.', 'Note tes charges pour voir ta progression.'], 'c:4:séances', ['sport']],
  ['high', 'SM', 'Le Défi de la Barre', 'Les forgerons comptent les coups de marteau. Toi, tu comptes tes tractions.', 'Battre ton record personnel sur un exercice de force (pompes, tractions, squats, gainage).', ['Mesure ton record de départ en début de période.', 'Prépare-le sur plusieurs séances.'], 's', ['sport']],
  ['high', 'JS', 'La Longue Marche', 'Les armées gagnent avec leurs jambes avant leurs lances. Marcher longtemps est un entraînement de roi.', 'Marcher 8 000 pas de plus que d’habitude dans la journée.', ['Fractionne : 20 minutes le matin, 30 le midi, 20 le soir.', 'Un podcast rend les pas plus légers.'], 'c:8000:pas', ['extérieur']],
  ['high', 'SM', 'La Prise de Parole Royale', 'Le roi écoute celui qui a préparé son discours. Le conseil retient celui qui l’a dit avec le cœur.', 'Présenter un sujet ou défendre une idée devant au moins 3 personnes.', ['Prépare trois points maximum.', 'Répète à voix haute une fois avant.'], 's', ['social']],
  ['high', 'S', 'Les Trois Armes de la Garnison', 'Une garnison solide s’entraîne à marcher, courir et porter. Elle n’en néglige aucune.', 'Faire 3 séances variées dans la semaine : une de force, une de cardio, une de mobilité.', ['Varie les plaisirs pour tenir dans la durée.', 'Chaque séance dure au moins 30 minutes.'], 'c:3:séances', ['sport']],
  ['high', 'M', 'L’Ascension du Bastion', 'Chaque bastion a commencé par un premier plan. Le tien commence par une série de séances régulières.', 'Faire au moins 12 séances de sport dans le mois.', ['Cale-les dans ton agenda dès le début du mois.', 'Une séance courte vaut mieux qu’une séance manquée.'], 'c:12:séances', ['sport']],
  ['high', 'SM', 'Le Dos du Géant', 'Un géant se reconnaît à son dos, pas à ses bras. La force vient de ce qu’on ne voit pas.', 'Faire 3 séances centrées sur le dos et le gainage dans la semaine, d’au moins 30 minutes chacune.', ['Rameur, élastique, tractions assistées ou superman.', 'Reste lent et contrôlé.'], 'c:3:séances', ['sport']],
  ['high', 'S', 'La Journée des Défis', 'Chaque semaine, le village organise un concours. Toi, tu t’inscris à celui qui te fait hésiter.', 'Participer à un défi qui te sort de ta zone de confort : cours d’essai, inscription à une course, scène ouverte.', ['Inscris-toi d’abord, réfléchis après.', 'Raconte-le à un ami pour t’engager.'], 's', ['social']],
  ['high', 'SM', 'L’Épreuve du Froid', 'Le nord ne pardonne pas aux imprudents. Mais ceux qui s’y préparent y trouvent un calme que le sud ignore.', 'Prendre 5 douches fraîches d’1 minute dans la période, après avis médical si besoin.', ['Commence tiède, termine frais, ne force pas.', 'Ne le fais pas si tu es malade ou en cas de problème cardiaque.'], 'c:5:douches', ['sans matériel']],
  // ── Légendaires (5)
  ['expert', 'M', 'L’Héritage du Titan', 'Les anciens racontent qu’un titan portait une montagne sur ses épaules. Il avait commencé par un caillou.', 'Gagner 20 % sur un exercice de référence (tractions, développé couché, squats) en un mois, mesuré au début et à la fin. Adapte à ta condition, consulte un professionnel si besoin.', ['Note ta performance de départ dès le premier jour.', 'Augmente progressivement, jamais d’un coup.'], 'e:Mesurer ma référence au départ|Planifier 12 séances|Atteindre +20 %|Mesurer ma référence finale', ['sport']],
  ['expert', 'ME', 'La Course du Héros', 'On raconte qu’un messager a couru jusqu’à l’épuisement pour annoncer la victoire. Toi, tu courras pour arriver.', 'Participer à une course officielle de 10 km ou plus, ou parcourir cette distance en une fois. Adapte à ta condition, consulte un professionnel si besoin.', ['Suis un plan d’entraînement progressif sur au moins 6 semaines.', 'Dors bien la veille.'], 'e:Choisir la course ou le parcours|Suivre mon plan d’entraînement|Courir la distance', ['sport', 'extérieur']],
  ['expert', 'SM', 'La Grande Prise de Parole', 'Le Conseil des Seigneurs n’écoute que ceux qui parlent debout. Le tien t’attend.', 'Prendre la parole devant au moins 10 personnes (présentation, discours, scène ouverte).', ['Prépare trois idées et une histoire.', 'Filme-toi une fois pour t’entendre.'], 'e:Préparer mon propos|Répéter à voix haute|Prendre la parole|Noter ce que je retiens', ['social']],
  ['expert', 'ME', 'Le Défi des Trente Jours', 'Il faut une lune entière pour changer un geste en habitude. Les anciens appelaient cela le grand cycle.', 'Faire au moins 25 séances de sport dans le mois, notées dans un carnet. Adapte à ta condition.', ['Prévois deux jours de repos par semaine.', 'Coche chaque séance sans te juger.'], 'c:25:séances', ['sport']],
  ['expert', 'M', 'La Montagne Gravie', 'Les sommets ne se prennent pas, ils se méritent. Le seul adversaire de la montagne, c’est la préparation.', 'Réaliser une randonnée d’au moins 800 m de dénivelé positif, en préparant l’itinéraire et la météo. Adapte à ta condition.', ['Pars avec quelqu’un ou préviens un proche.', 'Emporte eau, vivres et vêtements chauds.'], 'e:Choisir l’itinéraire|Vérifier la météo|Faire la randonnée', ['extérieur', 'sport']],
];
